IXS-Finance/interface

package.json
yarn.lock

Liquidity page is crashing due to the `WETH9` address is undefined.
SDK-core : v1.3.2: https://github.com/IX-Swap/sdk-core/commit/435d5c9858de5918dbb170ae44a4eeb793f99d21

Upgrade sdk-core to fix liquidity page crash

---

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx
src/state/wallet/hooks.ts

- use `useSimpleTokenBalanceWithLoading` hook to load balance instead of `useBalance`.  the hook should return a isLoading boolean which is used to set to the `disabled` props of the form inputs. Form inputs will be disabled while the balance is loading
- switch the `useSimpleTokenBalanceWithLoading` implementation from using multicall to regular contract call to speed up the query response time
https://investax.atlassian.net/browse/IXSPD1-34

Ixspd1 34 Fix inssuficient balance bug on launchpad while token balance is still loading

---

package.json
src/constants/lists.ts
src/services/apiService.ts
yarn.lock

- Bump `default-token-list` version to display correct bridged USDC  info
- Add `KYC` category for API errors related to KYC
- Remove UMA token list as the link is broken https://investax-ze.sentry.io/issues/5016159586/?project=4506812121022464&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

Update usdc and sentry

---

src/hooks/useApproveCallback.ts

- Launchpad call `investPublicSale` without waiting for `approve` transaction to be confirmed. This leads to the investPublicSale failed due to `insufficient allowance` error
https://investax.atlassian.net/browse/IXSPD1-975

Fix bug: order was not executed error

---

src/components/LaunchpadIssuance/ManageOffer/presale/WhitelistList.tsx
src/components/LaunchpadIssuance/ManageOffer/presale/index.tsx

Description:
- Fix bug The registration result is not displayed immediately in the table after approving/rejecting
Bullet points of the changes:
- Pass Approved Rejected List's startARLoading and stopARLoading to OfferWhitelistList to reload the Approved Rejected table
Link to jira ticket:
https://investax.atlassian.net/browse/IXSPD1-990

Ixspd1 990 fe dev issuance dashboard the registration result is not displayed immediately in the table after approving rejecting

---

src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx

This PR is to fix an issue that  "Check Status" disappears for users that has pending/rejected whitelist approval. 
- Uncomment previous code
- In the switch case `stageStatus`, check if whitelistedStatus exist, if not then this user haven't registered for investment then we return `disabled` stage
https://investax.atlassian.net/browse/IXSPD1-925

Fix check status

---

src/pages/Launchpad/Banner.tsx

There is a discrepancy in fonts between the live version and the design. The fonts look different, even though Inter is set in the font-family (Something wrong with the letter “i”). It appears as if it is a monospaced font.
made a font-family: system-ui (just a small change)
https://investax.atlassian.net/browse/IXSPD1-875

IXSPD1-875 Font Style IXS Launchpad fixed

---

src/components/LBP/utils/calculation.ts

The page crashes when user input the maximum project token amount to buy
2. Documents:

Bug fix 116- The page crashes when user input the maximum project token amount to buy

---

src/components/LBP/InvestmentList/LbpCard.tsx
src/components/Launchpad/KYCPrompt/index.tsx
src/pages/AppRoutes.tsx

Fixed a bug on the LBP details page where users could access the public details page after disconnecting their wallet.
- Added a popup
- Restricted the URL
-
2. Documents:

Bug fixed on lbp details page where if user disconnect the wallet.

---

src/pages/AppRoutes.tsx
src/pages/LBP/PublicDetails.tsx

Removed the isKycApproved from the route and check it in detail page. Previously we are checking isKycApproved in route.
Results of that user redirected to KYC page if reload the page.
- validate user on detail page
- updated the logic
const { kyc } = useKYCState()
const isKycApproved = kyc?.status === KYCStatuses.APPROVED ?? false
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1247
2. Documents:

Removed the isKycApproved from the route and check it in detail page.

---

src/pages/LBP/LbpForm.tsx

Removed the isCreate logic and fixed the issue where clicking the submit button multiple times would cause an error. Now, the user can submit the form correctly.
- added a logic if from.id or res.data.id available then user can can sumit the form 
- from.data,id will work if user open the from in edit mode and res.data.id  will work if user will open the form in create mode
2. Documents:

Removed iscreate logic, and fixed the issue if user clicks on submit button more than one time then id have been added

---

src/components/LBP/Dashboard/InvestorInformation.tsx

Minor fixes to the admin table changed the 'download CSV' column from 'usdValue' to 'boughtShares'.
- No any big changes
-
-
2. Documents:

Minor fixes to the admin table changed the download CSV column from 'usdValue' to 'boughtShares'.

---

src/components/Header/HeaderLinks.tsx
src/components/LBP/Admin/AdminHeader.tsx
src/components/LBP/Dashboard/LbpsFull.tsx
src/components/LBP/LbpCreateButton/index.tsx
src/pages/LBP/LbpForm.tsx
src/utils/routes.ts

- Don't allow users to access LBP dashboard and its child pages via links if they are not Admin
1. Jira ticket: just on sheet, bug 155
2. Documents:

Fix don't allow users to access LBP dashboard if not admin

---

src/components/Header/index.tsx

Announcements label was not closed after the clicks on close button issue have been fixed.
- This is by mistake while the testing in FE side we made the reverse logic      {cookies.annoucementsSeen && <Announcement />} but forgot to revise this to      {!cookies.annoucementsSeen && <Announcement />} that’s why close button is behaving like this
2. Documents:

fixed the annoucements bug

---

src/pages/KYC/SecondaryContactOption.tsx

This PR addresses an issue in the KYC form V2 where users did not have an option to resend the verification code if they did not receive it the first time. The following changes have been made to improve user experience:
- After the user clicks the "Verify Code" button, a timer will be displayed, counting down from 60 seconds to 0.
- Once the timer reaches 0, the "Get New Code" button will be displayed.
- If the user clicks the "Get New Code" button, a new verification code will be sent to the provided email address.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1337
2. Documents:

IXSPD1-1337 Displayed the Resend Code button and the time counter under Verify Code button

---

src/pages/KYC/IndividualKycFormV2.tsx

IXSPD1-1393 User cannot edit email if it was pre-filled after migrating the Draft KYC issue fixed
- changed the email value from the input and handled the value in use Effect so user can edit email
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1393
2. Documents:

IXSPD1-1393 User cannot edit email if it was pre-filled after migrating the Draft KYC issue fixed

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts
src/components/LaunchpadIssuance/IssuanceForm/Information/sections/AdditionalInformation.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts

The IXSPD1-1399 and IXSPD1-1398 updates increase the token ticker length to 16 letters and expand the social network link options in issuance.
- Increased token ticker length to 16 letters.
- Added more social network link options in issuance.
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1399
https://investax.atlassian.net/browse/IXSPD1-1398
2. Documents:

The IXSPD1-1399 and IXSPD1-1398 updates increase the token ticker length to 16 letters and expand the social network link options in issuance.

---

src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
src/constants/countriesList.ts
src/pages/App.tsx

In this PR we addressed 2 issues 
Blocked user from North Korea at App Level 
Hide checkboxes on the Invest Dashboard if there are no corresponding uploaded documents
- Blocked user from KP country code that belongs to North Korea
- Conditionally render agreement checkboxes based on the existence of related documents.
- Update button disable logic to depend on the presence and agreement status of available documents.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1496
https://investax.atlassian.net/browse/IXSPD1-1485
2. Documents:

Cherry pick IXSPD1-1496 and IXSPD1-1485 Prod release 

---

src/connectors/walletConnectV2.ts

QR code is not displayed when selecting WalletConnect on Readi tenant
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1540
2. Documents:

Ixspd1 1540 QR code is not displayed when selecting WalletConnect on Readi tenant

---

src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx

Launchpad - Hide Check Status at pre-sale if user submitted NO
- update the condition isInterested !== 0 where hide the buttons
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1567
2. Documents:

Launchpad - Hide Check Status at pre-sale if user submitted NO

---

src/components/Vault/DepoistStatusInfo.tsx

IXSPD1-1009 issue fixed on Custodian wallet field has incorrect position if the amount is too long
- made this 6 digits after the decimal 
1. Jira ticket:  https://investax.atlassian.net/browse/IXSPD1-1009
2. Documents:

IXSPD1-1009 issue fixed on Custodian wallet field has incorrect position if the amount is too long

---

src/pages/AddLiquidityV2/index.tsx
src/pages/RemoveLiquidity/index.tsx

- Replace legacy useApprove with useAllowance in Liquidity as it's slow and asks user to allow max uint256
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1622
2. Documents:

IXSPD1-1622 Replace legacy useApprove with useAllowance in Liquidity

---

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx

IXSPD1-1674D isplayed token ticker instead of currency on Claim Successful dashboard
- update the logic if isSuccessfull then getTokenSymbol with tokenSymbol else investingTokenSymbol
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1674
2. Documents:

IXSPD1-1674D isplayed token ticker instead of currency on Claim Successful dashboard

---

src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx

XSPD1-1700 issue fixed Don't fill in the current time if user closes the date picker without selecting
- just update the error state
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1700
2. Documents:

XSPD1-1700 issue fixed Don't fill in the current time if user closes the date picker without selecting

---

src/chains.ts
src/pages/AddLiquidityV2/index.tsx

Fix passing wrong network name to create liquidity pool API
I Reused the current ChainNames and implemented the `chainIdToNetwork` function
```typescript
export enum NetworkName {
BASE = 'base',
POLYGON = 'polygon',
}
export const Chains = {
// network name : tesnet, mainnet
[NetworkName.BASE]: [SupportedChainId.BASE_SEPOLIA, SupportedChainId.BASE],
[NetworkName.POLYGON]: [SupportedChainId.AMOY, SupportedChainId.MATIC],
}
```
2. Documents:

Fix passing wrong network name to create liquidity pool API

---

src/pages/CreatePayoutEvent/PayoutEventBlock.tsx

issue fixed on  Cannot delete completely default 'event name' on create payout form
- issue fixed on  Cannot delete completely default 'event name' on create payout form
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1795
2. Documents:

issue fixed on  Cannot delete completely default 'event name' on create payout form

---

src/components/Header/HeaderLinks.tsx
src/components/Launchpad/Offers/Pinned.tsx

IXSPD1 1833 and IXSPD1 1834  Issues fixed highlighting 2 menu and Displayed shortDescription on the Pinned deal  (#2699)
* Displayed shortDescription on the Pinned deal instead of longDescription
* issue fixed highlighting 2 menu items at a time
* increased gap between rows
2. Documents:

IXSPD1 1833 and IXSPD1 1834  Issues fixed highlighting 2 menu and Displayed shortDescription on the Pinned deal  (#2699)

---

src/pages/PayoutItem/History/index.tsx
src/pages/PayoutItem/PayoutHeader.tsx

Minor updates on payout detail page event with airdrop type
- if secToken is available the display the logo 
- if txHash is not available then display the loader
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1932
2. Documents:

Minor updates on payout detail page event with airdrop type

---

src/components/UsersList/UserModal.tsx
src/components/UsersList/index.tsx

Issue fixed USer should be able to assign new SEC on user permission even when they have active payout and fixed the pagination on user list tables
- Issue fixed USer should be able to assign new SEC on user permission even when they have active payout
- Fixed the pagination on user list tables
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1865
2. Documents:
3. Demo UI 
a) Issue fixed USer should be able to assign new SEC on user permission even when they have active payout
b) Fixed the pagination on user list tables

Issue fixed USer should be able to assign new SEC on user permission even when they have active payout

---

src/pages/PayoutItem/PayoutHeader.tsx

issue fixed Wrong SEC token in user view when includeOriginSupply= false on header
- issue fixed Wrong SEC token in user view when includeOriginSupply= false on header
1. Jira ticket:  https://investax.atlassian.net/browse/IXSPD1-1948
2. Documents:

issue fixed Wrong SEC token in user view when includeOriginSupply= false on header

---

src/pages/KYC/CorporateKycForm.tsx

TIN number field is disabled if user selects TIN is not available
- TIN number field is disabled if user selects TIN is not available
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1943
2. Documents:

TIN number field is disabled if user selects TIN is not available

---

src/hooks/personalSign.ts
src/hooks/useFetchAccessToken.ts

Sometimes we can't sign message. Click on Sign -> doesn't do anything 
Got the errro 
"{"code":-32600,"message":"Unsupported method: personal_sign. See available methods at https://docs.alchemy.com/alchemy/documentation/apis"}"
-  Replace old implementation with useSignMessage from Wagmi
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1990
2. Documents:

IXSPD1-1990: Fix bug can't sign message

---

src/hooks/useWeb3React.ts

Favour injected provider for useWeb3React hook
Somtimes, we got the issue when execute transaction. The app is using rpc provider without a signer
```
{
"jsonrpc": "2.0",
"id": 122,
"error": {
"code": -32600,
"message": "Unsupported method: eth_sendTransaction. See available methods at https://docs.alchemy.com/alchemy/documentation/apis"
}
}
```
2. Documents:

Favour injected provider for useWeb3React hook

---

src/components/Launchpad/NetworkNotAvailable/index.tsx

- Display only 1 required network when user access a deal/RWA detail pages
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2056
2. Documents:

Ixspd1-2056 fe dev display only 1 required network when user access a deal rwa detail pages

---

src/components/LaunchpadIssuance/ManageOffer/index.tsx
src/state/launchpad/types.ts

- disable start claim button if investment amount is 0
1. Jira ticket: [IXSPD1-2200]
2. Documents:
[IXSPD1-2200]: https://investax.atlassian.net/browse/IXSPD1-2200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2200] disable start claim button if investment amount is 0

---

src/components/Launchpad/NetworkNotAvailable/index.tsx

… popup
- MultiChain - Current network is always displayed as "Ethereum" on the popup
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2220
2. Documents:

Ixspd1-2220 fe dev multi chain current network is always displayed as ethereum on the popup

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx

… with Kaia or Ozean chain
- Multichain - Investing Token cannot be displayed on the issuance form with Kaia or Ozean chain
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2265
2. Documents:

Ixspd1-2265 fe dev multichain investing token cannot be displayed on the issuance form with kaia or ozean chain

---

.env.line-next
src/components/Rewards/TaskSuccessModal.tsx
src/constants/lineRewards.ts
src/hooks/useLineReward.ts

- enable user claim reward for joining line campaign
-
-
1. Jira ticket: [IXSPD1-2332]
2. Documents:
[IXSPD1-2332]: https://investax.atlassian.net/browse/IXSPD1-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2332] enable user claim reward for joining line campaign

---

src/components/AccountDetails/Avatar.tsx
src/pages/App.tsx
src/pages/KYC/index.tsx
src/utils/index.ts

- Fix referralCode for link open modal
-
-
2. Documents:

Fix referralCode for link open modal

---

src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts

- validate presaleTokenPrice when the hasPresale is enable
-
-
1. Jira ticket: [IXSPD1-2447]
2. Documents:
[IXSPD1-2447]: https://investax.atlassian.net/browse/IXSPD1-2447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2447] validate presaleTokenPrice when the hasPresale is enable

---

src/state/launchpad/hooks.ts

- convert presale price into string once update offer
-
-
1. Jira ticket: [IXSPD1-2458]
2. Documents:
[IXSPD1-2458]: https://investax.atlassian.net/browse/IXSPD1-2458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2458] convert presale price into string once update offer

---

src/pages/DexV2/Pool/components/CreateActions.tsx

- set default token decimals if token is undefined when creating pool
-
2. Documents:

fix: set default token decimals if token is undefined when creating pool

---

src/pages/DexV2/Pool/Create/components/Steps/ChooseWeights.tsx
src/pages/DexV2/Pool/Create/index.tsx
src/pages/DexV2/Pool/components/TokenPrices.tsx

- Pool - Tokens with prices are still displayed to enter prices
- Don't proceed to the next step until user input the token price
- https://investax.atlassian.net/browse/IXSPD1-2526
- https://investax.atlassian.net/browse/IXSPD1-2627
2. Documents:

IXSPD1-2627, Ixspd1-2526 Fix Prices Modal

---

src/state/launchpad/hooks.ts

- Invalid Files when update info of old issuances
- covers 3 cases: creating offer, updating offer without file changing, updating offer with file changes
1. Jira ticket: [IXSPD1-2705]
2. Documents:
[IXSPD1-2705]: https://investax.atlassian.net/browse/IXSPD1-2705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2705] Invalid Files when update info of old issuances

---

src/components/Header/HeaderLinks.tsx

- avoid dropping the search query when clicking on Dex v2
-
-
1. Jira ticket: [IXSPD1-2711]
2. Documents:
[IXSPD1-2711]: https://investax.atlassian.net/browse/IXSPD1-2711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2711] avoid dropping the search query when clicking on Dex v2

---

src/state/dexV2/tokens/hooks/useTokens.ts

- inject token list instead of replacing
- When that code injects the tokens, actually it replaces the list of token, from list A to B. So the get token balance function will be triggered and replace the balances. That why we encounter the UI re-render when the balance change, in the list A include the balance of pool but in the list B doesn’t.
2. Documents:

fix: inject token list instead of replacing

---

src/pages/Earn/ProductDetail/components/AnnualPercentageRate.tsx
src/pages/Earn/ProductDetail/index.tsx
src/pages/Earn/components/EarnProductCard.tsx
src/pages/Earn/products.ts

**Release Date:** July 11, 2025
---
This patch focuses on updating the **Blackrock HYCB Vault APY** displayed on the IXS platform to ensure accurate yield information for users.
---
- **Earn Module Fix:**  
Resolved an issue where APR displayed as **0%** when users cleared local storage, ensuring APY and APR values are fetched and shown correctly regardless of local cache state.
- **Blackrock HYCB Vault Update:**  
Updated the **HYCB Vault APY** on IXS to reflect the latest yield data from Blackrock, improving user confidence and aligning with real-time yield offerings.
---
- **APR Display Issue:**  
Fixed an edge case where clearing local storage caused Earn module APR to reset to 0% until a full refresh.
---
- **User-facing:** Correct APY visibility in Earn for HYCB vault.  
- …

Release patch v1.7.3 - Update Blackrock HYCB Vault APY on IXS
