IXS-Finance/interface

src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

- show insufficient token amount if chose pay now for the event
- replace useApproveCallback with useAllowance react hook
- approve token flow
- show security token when edit the payout event
1. Jira ticket: [IXSPD1-1764](https://investax.atlassian.net/browse/IXSPD1-1764)
2. Documents:
[IXSPD1-1764]: https://investax.atlassian.net/browse/IXSPD1-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-1764] critical bugs in the payout creation page

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/sections/IssuanceActionButtons.tsx
src/state/launchpad/hooks.ts

-  the issuance form does not change status after admin approves issuance form
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1649
2. Documents:

IXSPD1-1649 the issuance form does not change status after admin approves issuance form

---

src/components/TmEmptyPage/index.tsx
src/components/UserPayoutEvents/AllPayoutEvents.tsx
src/components/UserPayoutEvents/EmptyState.tsx
src/components/UserPayoutEvents/styleds.ts
src/pages/App.tsx
src/pages/SecurityTokens/index.tsx
src/pages/TokenManager/index.tsx

Update styling of payout event user pages
- Update styling of payout event user pages
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1766
2. Documents:

Update styling of payout event user pages

---

src/components/Header/index.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/index.tsx
src/pages/PayoutItem/PayoutItemManager.tsx
src/pages/TokenManager/index.tsx

Show token manager button for admin role
-  Show token manager button for admin role
-  fixed issue for token manager icon is shown even when user hasn’t connected wallet 
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1769
2. Documents:

IXSPD1-1769  Show token manager button for admin role

---

src/pages/PayoutItem/ActionBlock/UserView.tsx

issue fixed on payout page continue loading spinner
- issue fixed on payout page continue loading spinner
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1774
2. Documents:

issue fixed on payout page continue loading spinner

---

src/components/Select/index.tsx
src/pages/CreatePayoutEvent/PayoutForm.tsx

- style of disable options
- disable the security tokens from other chain
-
1. Jira ticket: [IXSPD1-1771]
2. Documents:
[IXSPD1-1771]: https://investax.atlassian.net/browse/IXSPD1-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1771] disable security tokens from other chain

---

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

- enable pay only for the created event instead of publishing
1. Jira ticket: [IXSPD1-1768]
2. Documents:
[IXSPD1-1768]: https://investax.atlassian.net/browse/IXSPD1-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-1768] pay only the created events

---

src/pages/PayoutItem/ActionBlock/UserView.tsx
src/pages/PayoutItem/PayoutHeader.tsx
src/state/token-manager/types.ts

Switch chain popup opened when the user attempts to open a payout on the wrong chain
- Switch chain popup opened when the user attempts to open a payout on the wrong chain
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1780
2. Documents:

Switch chain popup opened when the user attempts to open a payout on the wrong chain

---

src/components/UsersList/UpdateSummary.tsx
src/components/UsersList/UserModal.tsx
src/components/UsersList/index.tsx
src/components/UsersList/userMobileFilters.tsx

Allowed admin role to choose managed tokens
- Allowed admin role to choose managed tokens
2. Documents:

Allowed admin role to choose managed tokens

---

src/components/Select/index.tsx
src/components/UsersList/UpdateSummary.tsx
src/components/UsersList/UserModal.tsx
src/components/UsersList/mock.ts
src/constants/roles.ts
src/services/apiUrls.ts
src/state/admin/hooks.ts

- Update FE to allow assign master tenant role
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1763
2. Documents:

Ixspd1 1763 fe update fe to allow assign master tenant role

---

src/components/LaunchpadOffer/OfferMainInfo/OfferGalleryViewer.tsx

issue fixed on Viewing Gallery is broken on mobile screen
- issue fixed on Viewing Gallery is broken on mobile screen
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1787
2. Documents:

issue fixed on Viewing Gallery is broken on mobile screen

---

src/pages/CreatePayoutEvent/PayoutEventBlock.tsx

change button text on payout event button
- change button text on payout event button
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1781
2. Documents:

change button text on payout event button

---

src/components/DateInput/index.tsx
src/pages/KYC/common.tsx

- issue fixed Should show exactly error when validate datetime on create payout event
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1796
2. Documents:

issue fixed Should show exactly error when validate datetime on create payout event

---

src/components/LaunchpadOffer/OfferMainInfo/OfferGalleryViewer.tsx

issue fixed on Viewing Gallery is broken on mobile screen 
- issue fixed on Viewing Gallery is broken on mobile screen 
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1787
2. Documents:

issue fixed on Viewing Gallery is broken on mobile screen (#2687)

---

src/components/TmPayoutEvents/index.tsx
src/components/TmPayoutHistory/index.tsx

issue Fixed on token manager dashboard pages flashing when switch between tabs
- issue Fixed on token manager dashboard pages flashing when switch between tabs
2. Documents:

issue Fixed on token manager dashboard pages flashing when switch between tabs

---

src/components/Vault/AddressInput.tsx
src/components/Vault/AmountInputV2.tsx
src/components/Vault/DepositCard.tsx
src/components/Vault/DepositRequestForm.tsx
src/components/Vault/DepositTransaction.tsx
src/components/Vault/ExistingVault.tsx
src/components/Vault/TransactionDetails.tsx
src/components/Vault/enum.ts
src/components/Vault/index.tsx
src/pages/SecTokenDetails/index.tsx
src/state/deposit/reducer.ts
src/state/wallet/index.ts

- Update deposit flow
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1791
2. Documents:

IXSPD1-1791 Update deposit flow

---

src/assets/svg/star.svg
src/components/Header/AdministrationMenu.tsx
src/components/Header/HeaderLinks.tsx
src/components/Header/index.tsx
src/utils/routes.ts

- Re-Organize Menu, Back-office navigation
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1793
2. Documents:

Ixspd1-1793 fe re organize menu back office navigation

---

src/components/Header/AdministrationMenu.tsx
src/utils/routes.ts

- Fix css for button administration
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1793
2. Documents:

IXSPD1-1793 Fix css for button administration

---

src/components/Header/HeaderLinks.tsx
src/components/Launchpad/Offers/Pinned.tsx

Issues fixed highlighting 2 menu and Displaye shortDescription on the Pinned deal 
- Issue fixed highlighting 2 menu items at a time
- Displayed shortDescription on the Pinned deal instead of longDescription
https://investax.atlassian.net/browse/IXSPD1-1834
https://investax.atlassian.net/browse/IXSPD1-1833
2. Documents:

IXSPD1 1833 and IXSPD1 1834  Issues fixed highlighting 2 menu and Displaye shortDescription on the Pinned deal 

---

.env.development
.env.staging
.env.staging-client-demo
src/components/Header/AdministrationMenu.tsx
src/config/index.ts

- Add bridge admin link
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1793
2. Documents:

IXSPD1-1793 Add bridge admin link

---

src/pages/PayoutItem/ActionBlock/Claimed.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx

- replace toFixed function to floorToDecimals for the user payout item page
-
-
1. Jira ticket: [IXSPD1-1661]
2. Documents:
[IXSPD1-1661]: https://investax.atlassian.net/browse/IXSPD1-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1661] retrieve claim amount and truncate on FE

---

src/components/Header/AdministrationMenu.tsx

- Fix font size of bridge menu
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1793
2. Documents:

IXSPD1-1793 Fix font size of bridge menu

---

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

- publish payout event instead of creating draft event when token manager choose pay now option
1. Jira ticket: [IXSPD1-1848]
2. Documents:
[IXSPD1-1848]: https://investax.atlassian.net/browse/IXSPD1-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1848] publish payout event when TM choose pay now option

---

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

- change the workflow of approving token and publishing payout event
- only create draft event to purchase token, publish that event later
1. Jira ticket: [IXSPD1-1848]
2. Documents:
[IXSPD1-1848]: https://investax.atlassian.net/browse/IXSPD1-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1848] control approve and publish payout event

---

src/components/CurrencyLogo/index.tsx

Populate logo for token
2. Documents:

Populate logo for token

---

src/components/UserPayoutEvents/AllPayoutEvents.tsx

Fixed pagination on all payout
- Fixed pagination on all payout
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1788
2. Documents:

Fixed pagination on all payout

---

src/components/TmPayoutEvents/index.tsx
src/components/TmPayoutHistory/index.tsx

issue fixed on As a token manager, if there are no payout events i will see a placeholder
-issue fixed on As a token manager, if there are no payout events i will see a placeholder
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1685
2. Documents:

issue fixed on As a token manager, if there are no payout events i will see a placeholder

---

src/components/UserPayoutEvents/Card.tsx
src/pages/CreatePayoutEvent/index.tsx
src/pages/CreatePayoutEvent/mock.ts
src/pages/PayoutItem/PayoutHeader.tsx
src/pages/PayoutItem/PayoutItemManager.tsx
src/pages/PayoutItem/index.tsx

Ixspd1 1867 Update UI for airdrop mode
- Ixspd1 1867 Update UI for airdrop mode
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1867
2. Documents:

Ixspd1 1867 Update UI for airdrop mode

---

src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/PayoutForm.tsx
src/pages/CreatePayoutEvent/Summary.tsx
src/pages/CreatePayoutEvent/mock.ts
src/pages/CreatePayoutEvent/utils.ts

Update Payout event creation flow to support blocknumber, includeOriginSupply
-  Update Payout event creation flow to support blocknumber, includeOriginSupply
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1866
2. Documents:

Ixspd1 1866 Update Payout event creation flow to support blocknumber, includeOriginSupply

---

src/abis/payout-airdrop.json
src/components/Uploader/index.tsx
src/constants/addresses.ts
src/hooks/useContract.ts
src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/pages/CreateAirdropPayoutEvent/AirdropForm.tsx
src/pages/CreateAirdropPayoutEvent/PublishAirdropModal.tsx
src/pages/CreateAirdropPayoutEvent/index.tsx
src/pages/CreateAirdropPayoutEvent/mock.ts
src/pages/CreateAirdropPayoutEvent/utils.ts

- add airdrop contract instance
- adjust the uploader component to export the csv row data
- approve airdrop contract using erc20 token
- call airdrop contract to distribute token
- remove abandoned code
1. Jira ticket: [IXSPD1-1807]
2. Documents:
[IXSPD1-1807]: https://investax.atlassian.net/browse/IXSPD1-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1807] integrate contract to approve and distribute token

---

src/pages/CreatePayoutEvent/PayoutForm.tsx

edit payout fetch amount if includeOriginSupply checked
- fixed issue on edit payout fetch amount if includeOriginSupply checked
2. Documents:

fixed issue on edit payout fetch amount if includeOriginSupply checked

---

src/components/TmPayoutEvents/index.tsx
src/components/TokenLogo/index.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx

All payout events have the wrong token logo issue  fixed
- All payout events have the wrong token logo issue  fixed
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1785
2. Documents:

payout events have the wrong token logo issue  fixed

---

src/abis/payout.json
src/constants/addresses.ts
src/pages/PayoutItem/ActionBlock/ManagerView.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx
src/state/payout/hooks.ts

- retrieve claim back signature
- remove nonce property
- update payout ABI
1. Jira ticket: [IXSPD1-1882]
2. Documents:
[IXSPD1-1882]: https://investax.atlassian.net/browse/IXSPD1-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1882] update payout claim back flow for token manager

---

src/components/WhiteLabelFooter/CopyrightBlock.tsx
src/components/WhiteLabelFooter/styleds.tsx

- fixed Readi UI broken on Swap, KYC pages
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1871
2. Documents:

fixed Readi UI broken on Swap, KYC pages

---

src/pages/CustodianV2/SecTokensTable.tsx

Fix pagination on token list page
- Fix pagination
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1788
2. Documents:

fixed pagination on token list

---

src/components/LoaderHover/index.tsx
src/components/LoadingIndicator/index.tsx
src/components/TmMyTokens/index.tsx
src/components/TmPayoutEvents/index.tsx
src/components/TmPayoutHistory/index.tsx
src/components/UserPayoutEvents/AllPayoutEvents.tsx
src/components/UserPayoutEvents/MyPayoutEvents.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/index.tsx
src/pages/PayoutItem/ActionBlock/ManagerView.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx
src/pages/PayoutItem/PayoutItemManager.tsx
src/pages/PayoutItem/index.tsx

fixed token manager dashboard pages flashing when switch between tabs
- fixed token manager dashboard pages flashing when switch between tabs
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1789
2. Documents:

fixed token manager dashboard pages flashing when switch between tabs

---

src/components/TmPayoutEvents/index.tsx
src/components/TmPayoutHistory/index.tsx

fixed issue on payout list screen is flashing when using filter with option which have data
- fixed issue on payout list screen is flashing when using filter with option which have data
- fixed issue Could not search by wallet or ID which have data on payout history
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1890
https://investax.atlassian.net/browse/IXSPD1-1822
2. Documents:

fixed issue on payout list screen is flashing when using filter with option which have data

---

src/components/MultipleFilters/index.tsx
src/hooks/useAllTokensList.tsx
src/state/secTokens/hooks.ts

fixed the issue where show SEC of all chain
- fixed the issue where show SEC of all chain
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1870
2. Documents:

fixed the issue where show SEC of all chain

---

src/components/Uploader/index.tsx
src/hooks/useTokensList.tsx
src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/PayoutItem/History/index.tsx

issue fixed Missing Payout token in edit mode and pagination fixes on airdrop
- issue fixed Missing Payout token in edit mode and pagination fixes on airdrop
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1861
2. Documents:

issue fixed Missing Payout token in edit mode and pagination fixes on airdrop

---

src/pages/CreatePayoutEvent/PayoutEventBlock.tsx
src/pages/CreatePayoutEvent/styleds.ts

issue fixed on payout delayed status admin can now edit start date and deadline date
- issue fixed on payout delayed status admin can now edit start date and deadline date
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1827
2. Documents:

issue fixed on payout delayed status admin can now edit start date and deadline date

---

src/components/TmPayoutEvents/index.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/PayoutForm.tsx

-change payout event button's behavior if already paid
1. Jira ticket: [IXSPD1-1815]
2. Documents:
[IXSPD1-1815]: https://investax.atlassian.net/browse/IXSPD1-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-1815] change payout event button's behavior if already paid

---

src/components/TmPayoutEvents/index.tsx
src/components/UserPayoutEvents/AllPayoutEvents.tsx
src/pages/CreatePayoutEvent/utils.ts

- fetch data when change URL pathname
- allow submit id when update payout event
1. Jira ticket: [IXSPD1-1831]
2. Documents:
[IXSPD1-1831]: https://investax.atlassian.net/browse/IXSPD1-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-1831] update payout list automatically after back to list

---

src/components/Vault/DepositPopup.tsx
src/components/Vault/DepositRequestForm.tsx

- Handle validate token balance with deposit amount
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1869
2. Documents:

IXSPD1-1869 Handle validate token balance with deposit amount

---

src/components/Vault/DepositCard.tsx
src/components/Vault/DepositRequestForm.tsx

- Fix base on status show content deposit
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1883
2. Documents:

IXSPD1-1883 Fix base on status show content deposit

---

src/components/Launchpad/InvestmentCard/index.tsx
src/components/Select/index.tsx
src/components/UsersList/UserModal.tsx
src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/pages/CreateAirdropPayoutEvent/AirdropForm.tsx
src/pages/CreatePayoutEvent/PayoutEventBlock.tsx
src/pages/CreatePayoutEvent/PayoutForm.tsx
src/pages/KYC/common.tsx

combined token and network in dropdown
- combined token and network in dropdown
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1728
2. Documents:

combined token and network in dropdown

---

src/components/TmPayoutEvents/index.tsx
src/state/payout/hooks.ts
src/state/token-manager/hooks.tsx

- admin can list all payouts
1. Jira ticket: [IXSPD1-1810]
2. Documents:
[IXSPD1-1810]: https://investax.atlassian.net/browse/IXSPD1-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1810] admin can list all payouts

---

src/components/Vault/DepositCard.tsx
src/components/Vault/DepositError.tsx
src/components/Vault/DepositPopup.tsx
src/components/Vault/DepositRequestForm.tsx
src/components/Vault/DepositTransaction.tsx
src/components/Vault/ExistingVault.tsx
src/pages/CustodianV2/MySecToken.tsx
src/pages/CustodianV2/styleds.ts
src/pages/SecTokenDetails/index.tsx

- Cannot open About wrapping popup
- Deposit status screen is not displayed after user confirms on wallet
- Deposit form is still displayed when user open other pages and back
- https://investax.atlassian.net/browse/IXSPD1-1880
- https://investax.atlassian.net/browse/IXSPD1-1888
- https://investax.atlassian.net/browse/IXSPD1-1884
2. Documents:

IXSPD1-1888, IXSPD1-1880, IXSPD1-1884 Fix cannot open About wrapping popup

---

src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/pages/CreateAirdropPayoutEvent/validation.ts

- update validation schema to mandate the files has one item at least
1. Jira ticket: [IXSPD1-1807]
2. Documents:
[IXSPD1-1807]: https://investax.atlassian.net/browse/IXSPD1-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1807] mandate the files field once airdrop token

---

src/components/Header/AdministrationMenu.tsx

- Administration menu does not close when clicking on Payout
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1853
2. Documents:

Ixspd1-1853 fe dev administration menu does not close when clicking on payout

---

src/components/Header/AdministrationMenu.tsx

- Fix Could not access to 'payout' from menu on dev-readi
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1849
2. Documents:

Fix Could not access to 'payout' from menu on dev-readi

---

src/pages/CreateAirdropPayoutEvent/index.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/index.tsx
src/pages/PayoutItem/PayoutItemManager.tsx

added back button on create payout page and detail and edit payout pages
- added back button on create payout page and detail and edit payout pages
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1821
2. Documents:

added back button on create payout page and detail and edit payout pages

---

src/components/TmPayoutEvents/index.tsx

- added isClearable for clear filter
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1889
2. Documents:

added isClearable for clear filter

---

src/pages/CreateAirdropPayoutEvent/PublishAirdropModal.tsx
src/utils/formatCurrencyAmount.ts

- add safeParseUnits function to parse unit with long decimals
1. Jira ticket: [IXSPD1-1807]
2. Documents:
[IXSPD1-1807]: https://investax.atlassian.net/browse/IXSPD1-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1807] parse unit with long decimals

---

src/chains.ts
src/components/TmPayoutHistory/index.tsx

fix filters on payout history table
- fixed filters on payout history table
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1913
2. Documents:

fixed filters on payout history table

---

src/components/TmPayoutEvents/index.tsx
src/components/UserPayoutEvents/AllPayoutEvents.tsx

paginations issue fixed on multiple components and logo issue fixed on history page
- paginations issue fixed on multiple components and logo issue fixed on history page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1788
2. Documents:

paginations issue fixed on multiple components and logo issue fixed on history page

---

src/components/TmPayoutEvents/index.tsx
src/hooks/useApproveCallback.ts
src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/pages/CreateAirdropPayoutEvent/AirdropForm.tsx
src/pages/CreateAirdropPayoutEvent/PublishAirdropModal.tsx
src/pages/CreateAirdropPayoutEvent/mock.ts
src/pages/CreateAirdropPayoutEvent/utils.ts
src/pages/CreateAirdropPayoutEvent/validation.ts
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/PayoutItem/ActionBlock/ManagerView.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx
src/pages/PayoutItem/PayoutHeader.tsx
src/pages/PayoutItem/index.tsx
src/services/apiUrls.ts
src/state/payout/hooks.ts
src/state/token-manager/types.ts

- make secTokenId optional
- call airdrop endpoint to create airdrop event
- pass the CSV data onto backend
1. Jira ticket: [IXSPD1-1916]
2. Documents:
[IXSPD1-1916]: https://investax.atlassian.net/browse/IXSPD1-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1916] make secTokenId optional

---

src/pages/PayoutItem/index.tsx

- fix retrieve my token amount
-
-
2. Documents:

fix: retrieve my token amount

---

src/pages/PayoutItem/ActionBlock/ManagerView.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx

- wait block to be mined
1. Jira ticket: [IXSPD1-1918]
2. Documents:
[IXSPD1-1918]: https://investax.atlassian.net/browse/IXSPD1-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1918] wait for transaction to be mined

---

src/components/UserPayoutEvents/AllPayoutEvents.tsx
src/components/UserPayoutEvents/Card.tsx
src/components/UserPayoutEvents/styleds.ts

Update Payout Card View
- Update Payout Card View
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1911
2. Documents:
3. Page Demo

Update Payout Card View

---

src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx

- airdrop filter out native tokens as the payout token
-
-
2. Documents:

feat: airdrop filter out native tokens as the payout token

---

src/components/UserPayoutEvents/AllPayoutEvents.tsx

clear filter enable on all payout event page
- clear filter enable on all payout event page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1889
2. Documents:

clear filter enable on all payout event page

---

src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/services/apiUrls.ts

Added a reference link to CSV template for Airdrop
- Added a reference link to CSV template for Airdrop
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1912
2. Documents:

Added a reference link to CSV template for Airdrop

---

src/components/LaunchpadIssuance/IssuanceForm/Information/sections/IssuanceActionButtons.tsx

- Fix show admin button for master tenant
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1902
2. Documents:

IXSPD1-1902 Fix show admin button for master tenant

---

src/components/LaunchpadIssuance/IssuanceDashboard/IssuanceInformationPopup.tsx

- Hide the Deploy button and Issuance fee if user role is Master tenant
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1921
2. Documents:

IXSPD1-1921 Hide the Deploy button and Issuance fee if user role is Master tenant

---

src/components/UserPayoutEvents/Card.tsx
src/components/UserPayoutEvents/MyPayoutEvents.tsx

title added on card and fix logo align
- title added on card and fix logo align
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1911-N
2. Documents:

title added on card and fix logo align

---

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

- payout event wait for confirmation then submit txPaidHash
-
-
2. Documents:

feat: payout event wait for confirmation then submit txPaidHash

---

src/pages/App.tsx

-  Fix default redirect when access home page
-
-
2. Documents:

Fix default redirect when access home page

---

src/utils/formatCurrencyAmount.ts

- round of number by decimals
2. Documents:

fix: round of number by decimals

---

src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx

- reset sec token when user change network
1. Jira ticket: [IXSPD1-1927]
2. Documents:
[IXSPD1-1927]: https://investax.atlassian.net/browse/IXSPD1-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1927] reset sec token when user change network

---

src/pages/App.tsx

- Fix reload redirect to default page
-
-
2. Documents:

Fix reload redirect to default page

---

src/components/Launchpad/InvestmentCard/index.tsx
src/components/UserPayoutEvents/Card.tsx

- Text height reduced
2. Documents:
3. UI Demo

Payout card align

---

src/components/TmPayoutEvents/index.tsx

issue fixed on Could not see payout token icon when stand in different network
- issue fixed on Could not see payout token icon when stand in different network
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1910
2. Documents:

issue fixed on Could not see payout token icon when stand in different network

---

src/components/Modal/RedesignedLightWideModal.tsx

removed blue background of the image preview
- Removed blue background of the image preview
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1925
2. Documents:

removed blue background of the image preview

---

src/components/Launchpad/InvestmentCard/index.tsx

- issue fixed on Capitalised texts in deal card
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1923
2. Documents:

issue fixed on Capitalised texts in deal card

---

src/components/Launchpad/InvestmentCard/index.tsx
src/pages/SecTokenDetails/index.tsx
src/pages/SecTokenDetails/styleds.ts

- Polish Back button on RWAs
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1875
2. Documents:

Ixspd1 1875 Polish Back button on RWAs

---

src/pages/Launchpad/Footer.tsx

Hide roadmap in the footer
- Hide roadmap in the footer
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1926
2. Documents:

Ixspd1 1926 Hide roadmap in the footer

---

src/pages/CreatePayoutEvent/PayoutForm.tsx

Update record date time til 23:59:59 
2. Documents:

Update record date time

---

src/pages/PayoutItem/PayoutItemManager.tsx

- enable admin access the payout event detail
1. Jira ticket: [IXSPD1-1810]
2. Documents:
[IXSPD1-1810]: https://investax.atlassian.net/browse/IXSPD1-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1810] enable admin access the payout event detail

---

src/pages/PayoutItem/PayoutItemManager.tsx

feat: [IXSPD1-1810] refactor validation of user privilege

---

src/components/UserPayoutEvents/Card.tsx

fixed card height on payout
- fixed card height on payout
2. Documents:

fixed card height on payout

---

src/components/TmPayoutHistory/index.tsx

Display all chains tokens on payout history table
- render tokens with useSafeCurrency hook
1. Jira ticket: This issue doesn't have a ticket, but the fix can be related to [IXSPD1-1910](https://investax.atlassian.net/browse/IXSPD1-1910).
2. Documents:
[IXSPD1-1910]: https://investax.atlassian.net/browse/IXSPD1-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Display all chains tokens on payout history table

---

src/pages/PayoutItem/PayoutItemManager.tsx

-
-
-
1. Jira ticket: [[IXSPD1-1810](https://investax.atlassian.net/browse/IXSPD1-1810)]
2. Documents:
[IXSPD1-1810]: https://investax.atlassian.net/browse/IXSPD1-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-1810] payout, user initiated before checking the ownership

---

src/components/Vault/DepositRequestForm.tsx

-  Add error text for deposit form
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1869
2. Documents:

IXSPD1-1869 Add error text for deposit form

---

src/pages/App.tsx

- Redirect to Launchpad when offer manager role refreshes Issuance page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1877
2. Documents:

IXSPD1-1877 Redirect to Launchpad when offer manager role refreshes Issuance page

---

src/pages/PayoutItem/index.tsx

added  back button in payout detail on user view
- added  back button in payout detail on user view
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1933
2. Documents:

added  back button in payout detail on user view

---

src/theme/muiTheme.tsx

UI fixes on date picker
- UI fixes on date picker
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1879
2. Documents:
3. UI Demo

UI fixes on date picker

---

src/pages/PayoutItem/ActionBlock/UserView.tsx

- when user requested accreditation but not passed yet, the UI **does not** show the accreditation banner.
-
-
2. Documents:

fix: request accreditation if user is not passed yet

---

src/components/TmPayoutHistory/index.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/KYC/common.tsx

Fixed the chain logo issue on the payout edit form and removed the placeholder logo in payout history for non-sec tokens.
- Fixed the chain logo issue on the payout edit form 
- Removed the placeholder logo in payout history for non-sec tokens
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1728
2. Documents:
3. Demo UI
a) 
b) 

Fixed the chain logo issue on the payout edit form and removed the placeholder logo in payout history for non-sec tokens.

---

src/pages/PayoutItem/ActionBlock/Claimed.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx

feat: validate user claimed on chain

---

src/components/TmPayoutHistory/index.tsx

- avoid regression bug
- fetching payout history when changing wallet
1. Jira ticket: [IXSPD1-1940]
2. Documents:
[IXSPD1-1940]: https://investax.atlassian.net/browse/IXSPD1-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1940] avoid regression bug when fetching payout history

---

src/pages/App.tsx
src/pages/KYC/common.tsx

Added a white background to the payout view and a border to the payout sec token edit section
- Added a white background to the payout view
- Border to the payout sec token edit section
2. Documents:
3. UI Demo
a) Added a white background to the payout view
b) Border to the payout sec token edit section

Added a white background to the payout view and a border to the payout sec token edit section

---

src/pages/PayoutItem/index.tsx
src/utils/routes.ts

issue fixed  redirect to previous page when click on back button in user view
- create a separate url to all payout events for users
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1939
2. Documents:

issue fixed  redirect to previous page when click on back button in user view

---

src/components/Vault/AmountInputV2.tsx
src/components/Vault/DepositRequestForm.tsx
src/components/Vault/WithdrawRequestForm.tsx

- Add max button for deposit form and withdraw form
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1937
2. Documents:

Ixspd1-1937 fe add max button on deposit and withdrawal flow 

---

src/pages/PayoutItem/ActionBlock/ManagerView.tsx

Hide Claim Back button if the current user is not the event creator, if and event creator didn't pay for the event earlier
-  Hide Claim Back button if the current user is not the event creator, if and event creator didn't pay for the event earlier
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1942
2. Documents:

Ixspd1 1942 Hide Claim Back button

---

src/pages/SecTokenDetails/index.tsx

fixed back button position
- fixed back button position
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1935
2. Documents:

fixed back button position

---

src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/PublishPayoutModal.tsx
src/pages/CreatePayoutEvent/utils.ts

fix: disable pay button if user is not owner

---

src/pages/SecTokenDetails/index.tsx

Issue fixed The Back button is disappear if the disclaimer text is not close
- fixed The Back button is disappear if the disclaimer text is not close
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1938
2. Documents:
3. UI Demo 

Issue fixed The Back button is disappear if the disclaimer text is not closed

---

src/pages/CreatePayoutEvent/PayoutForm.tsx

Allow inclusion of original supply when future record date is selected
- Allow inclusion of original supply when future record date is selected
2. Documents:

Allow inclusion of original supply when future record date is selected

---

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

- validate the ownership when the event is not created yet
-
-
2. Documents:

fix: validate the ownership when the event is not created yet

---

src/pages/PayoutItem/ActionBlock/UserView.tsx

issue fixed Wrong SEC token in user view when includeOriginSupply= false
- issue fixed Wrong SEC token in user view when includeOriginSupply= false
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1948
2. Documents:
3. UI Demo

issue fixed Wrong SEC token in user view when includeOriginSupply= false

---

src/components/Vault/DepositCard.tsx

- Fix Deposit successful screen still displays when user click new Deposit
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1949
2. Documents:

IXSPD1-1949 Deposit successful screen still displays when user click new Deposit

---

src/pages/KYC/schema.ts

fixed invalid error message
- fixed invalid error message
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1943
2. Documents:
3. UI Demo

fixed invalid error message

---

src/components/Vault/DepositCard.tsx
src/components/Vault/DepositRequestForm.tsx
src/components/Vault/DepositTransaction.tsx

- deposit successful screen still displays when user click new deposit
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1949
2. Documents:

Ixspd1-1949 fe dev deposit successful screen still displays when user click new deposit

---

package.json
yarn.lock

Bump default-token-list version and reflect NPT token in the swap box

---

package.json
yarn.lock

Reflect NPT token in the swap box
2. Documents:

Reflect NPT token in the swap box

---

package.json
yarn.lock

Revert default token list version update to keep using fake stablecoin tokens on mainnet

---

src/pages/PayoutItem/ActionBlock/ManagerView.tsx

fixed issue on Claim back button still enable after claim back success
- fixed issue on Claim back button still enable after claim back success
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1826
2. Documents:

fixed issue on Claim back button still enable after claim back success

---

src/components/Launchpad/InvestmentList/Filter.tsx
src/components/Launchpad/Offers/index.tsx

Added a filter by network for launchpad
- Added a filter by network for launchpad
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1756
2. Documents:

Added a filter by network for launchpad

---

src/components/LBP/InvestmentList/Filter.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts
src/state/launchpad/constants.ts
src/state/launchpad/types.ts

added a new category Media & Entertainment in Issuance  dropdown and filter
- added a new category Media & Entertainment in Issuance  dropdown and filter
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1627
2. Documents:

added a new category Media & Entertainment in Issuance  dropdown and filter

---

src/components/TmPayoutHistory/index.tsx
src/components/TmPayoutHistory/styleds.ts

- show payout event name on history page
-
-
1. Jira ticket: [IXSPD1-1954]
2. Documents:
[IXSPD1-1954]: https://investax.atlassian.net/browse/IXSPD1-1954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1954] show payout event name on history page

---

src/pages/CreateAirdropPayoutEvent/PublishAirdropModal.tsx

- validate duplicated addresses in sensitivity issue
-
-
2. Documents:

fix: validate duplicated addresses in sensitivity issue

---

src/pages/KYC/CorporateKycForm.tsx
src/pages/KYC/schema.ts

Reverts IX-Swap/interface#2827

Revert "IXSPD1-1956 Revert kyc corporate form"

---

src/pages/KYC/CorporateKycForm.tsx

- https://investax.atlassian.net/browse/IXSPD1-1956
-
-
2. Documents:

IXSPD1-1956 Fix Corporate KYC form empty

---

src/components/TmPayoutEvents/index.tsx
src/components/TmPayoutEvents/styleds.ts
src/components/TmPayoutHistory/index.tsx
src/components/TmPayoutHistory/styleds.ts

- show event name on payout events page
- show event name on payout history page
-
1. Jira ticket: [IXSPD1-1960]
2. Documents:
[IXSPD1-1960]: https://investax.atlassian.net/browse/IXSPD1-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1960] show event name on payout events page

---

src/pages/KYC/CorporateKycForm.tsx

- Remove some condition
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1956
2. Documents:

IXSPD1-1956 Remove some condition

---

src/components/Vault/ExistingVault.tsx
src/pages/CustodianV2/SecTokenSection.tsx
src/state/wallet/index.ts

- RWA - Optimize the loading time of token's balance
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1964
2. Documents:

Ixspd1-1964 fe rwa optimize the loading time of token s balance

---

src/hooks/useSwapCallback.ts

- Swap - Fix the long error message when the price impact is too high
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1963
2. Documents:

IXSPD1-1963 Swap - Fix the long error message when the price impact is too high

---

src/components/Header/HeaderLinks.tsx
src/components/Mobile-Menu/Menu.tsx
src/components/NotAvailablePage/ConnectWalletCard.tsx
src/pages/Launchpad/Header.tsx

Change farming term to staking
2. Documents:

Change farming term to staking

---

src/components/Header/HeaderLinks.tsx
src/components/Mobile-Menu/Menu.tsx
src/pages/Launchpad/Header.tsx

1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1997
2. Documents:

Change farming term to staking (#2841)

---

src/components/Uploader/index.tsx
src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/pages/CreateAirdropPayoutEvent/CsvUploader.tsx

- support airdrop by csv file without header
-
-
1. Jira ticket: [IXSPD1-2000]
2. Documents:
[IXSPD1-2000]: https://investax.atlassian.net/browse/IXSPD1-2000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2000] support airdrop by csv file without header

---

src/components/Launchpad/InvestmentCard/RaisedFund.tsx
src/components/Launchpad/InvestmentCard/index.tsx
src/pages/Launchpad/Banner.tsx
src/utils/index.ts

- Show total fund raised on Deal card and Total Raised of all deals
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1962
2. Documents:

IXSPD1-1962 Show total fund raised on Deal card and Total Raised of all deals

---

src/components/Uploader/index.tsx
src/pages/CreateAirdropPayoutEvent/AirdropEventBlock.tsx
src/pages/CreateAirdropPayoutEvent/CsvUploader.tsx
src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

Staging hotfixes for payout 
[Payout: fix wrong usage of refreshAllowance in payout pay modal (](https://github.com/IX-Swap/interface/pull/2845/commits/e124f157e4faaa9d85d4749f5627e6f25648a57a)
[feat: [IXSPD1-2000] support airdrop by csv file without header](https://github.com/IX-Swap/interface/pull/2845/commits/ac4c305848bd44d5964c379c56d66f6f73115ef8)
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2000
2. Documents:
[IXSPD1-2000]: https://investax.atlassian.net/browse/IXSPD1-2000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Staging hotfixes

---

src/pages/CreateAirdropPayoutEvent/CsvUploader.tsx

- migrate isAddress function
-
-
2. Documents:

feat: migrate isAddress function

---

src/pages/CreatePayoutEvent/PayoutForm.tsx
src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

- remove file if saved in draft mode
-
-
1. Jira ticket: [IXSPD1-2005]
2. Documents:
[IXSPD1-2005]: https://investax.atlassian.net/browse/IXSPD1-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2005] remove file if saved in draft mode

---

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx

- handle loading when paying later
-
-
1. Jira ticket: [IXSPD1-2006]
2. Documents:
[IXSPD1-2006]: https://investax.atlassian.net/browse/IXSPD1-2006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2006] handle loading when paying later

---

src/components/LaunchpadIssuance/ManageOffer/index.tsx

- Admin should be allowed to withdraw all deals
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1985
2. Documents:

IXSPD1-1985 Admin should be allowed to withdraw all deals

---

src/components/Button/index.tsx
src/components/Header/index.tsx
src/components/Mobile-Menu/Menu.tsx

- Adjust some fields related to user's profile on Mobile screen
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2004
2. Documents:

IXSPD1-2004 Adjust some fields related to user's profile on Mobile screen

---

src/components/SignMessageModal/styled.ts

- Resize the Sign popup on mobile browser's screen
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1998
2. Documents:

IXSPD1-1998 Resize the Sign popup on mobile browser's screen

---

package.json
yarn.lock

Use real token staging: Swap, payout. Launchpad still  use mock token

---

src/components/TmPayoutEvents/index.tsx

- show total amount if payout event is airdrop
-
-
1. Jira ticket: [IXSPD1-2013]
2. Documents:
[IXSPD1-2013]: https://investax.atlassian.net/browse/IXSPD1-2013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2013] show total amount if payout event is airdrop

---

src/components/Header/AdministrationMenu.tsx

- UI bug relates to the administration menu
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1981
2. Documents:

Ixspd1-1981 fe UI bug relates to the administration menu

---

src/state/auth/hooks.ts

- page error displays when user disconnects on LBP detail page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1996
2. Documents:

Ixspd1-1996 fe dev page error displays when user disconnects on lbp detail page

---

package.json
yarn.lock

This reverts commit 640b4faaecff3b982b550d739b152ea13840a4b2.
- Use mock token for staging
2. Documents:

Revert "Reflect NPT token in the swap box"

---

src/components/Table/index.tsx
src/components/TmPayoutEvents/index.tsx
src/components/TmPayoutEvents/styleds.ts
src/pages/PayoutItem/Timeline/PayoutTimeline.tsx
src/pages/PayoutItem/Timeline/TimelineDate.tsx
src/pages/PayoutItem/Timeline/TodayIndicator.tsx
src/pages/TokenManager/index.tsx

- update indicator position
- highlight start date button
- styles of token manager payout list
1. Jira ticket: [IXSPD1-2018]
2. Documents:
[IXSPD1-2018]: https://investax.atlassian.net/browse/IXSPD1-2018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2018] enhance UI on payout detail

---

src/pages/PayoutItem/ActionBlock/ManagerView.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx

- update the notification if the event is delayed
-
-
2. Documents:

feat: update the notification if the event is delayed

---

src/components/SignMessageModal/index.tsx
src/pages/App.tsx
src/state/auth/hooks.ts
src/state/user/hooks.tsx
src/state/wallet/index.ts

- Sign flow - The user cannot Sign if user cancels opening MetaMask app
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1999
2. Documents:

IXSPD1-1999 Sign flow - The user cannot Sign if user cancels opening MetaMask app

---

src/components/Button/index.tsx
src/components/MultipleFilters/index.tsx
src/components/MultipleFilters/styleds.ts
src/components/TmPayoutHistory/index.tsx

- add clear button in payout history page
-
-
1. Jira ticket:[IXSPD1-1967] 
2. Documents:
[IXSPD1-1967]: https://investax.atlassian.net/browse/IXSPD1-1967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-1967] add clear button in payout history page

---

src/components/Button/index.tsx
src/components/MultipleFilters/index.tsx

- update global button size and payout page
-
-
1. Jira ticket: [IXSPD1-2023] 
2. Documents:
[IXSPD1-2023]: https://investax.atlassian.net/browse/IXSPD1-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2023] global button size and payout page

---

src/hooks/personalSign.ts

- Cannot connect to CoinBase after disconnecting it (Scan QR)
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1983
2. Documents:

Ixspd1-1983 fe dev cannot connect to coin base after disconnecting it scan qr

---

src/state/auth/hooks.ts
src/state/auth/reducer.ts

- The Sign popup flashes after disconnecting wallet
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1994
2. Documents:

IXSPD1-1994 The Sign popup flashes after disconnecting wallet

---

src/components/Header/index.tsx
src/components/Web3Status/index.tsx

- Remove the KYC button for users passed KYC as well
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2004
2. Documents:

IXSPD1-2004 Remove the KYC button for users passed KYC as well

---

src/pages/CustodianV2/MySecToken.tsx

- UI is broken when the token name is too long
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2027
2. Documents:

Ixspd1-2027 fe dev UI is broken when the token name is too long

---

src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx

- Don’t display all social icon on Deal page when they are not provided 
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1852
2. Documents:

Ixspd1-1852 fe mobile minor UI bugs

---

src/state/auth/hooks.ts
src/state/auth/reducer.ts

-  stuck when token expire
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1990
2. Documents:

IXSPD1-1990 stuck when token expire

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx

- Limit the length of token ticker to 10 characters
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2029
2. Documents:

Ixspd1-2029 fe limit the length of token ticker to 10 characters

---

src/components/CurrencyInputPanel/index.tsx
src/components/SearchModal/CurrencyList.tsx
src/components/SearchModal/styleds.tsx

- Layout is broken on Swap token list
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2001
2. Documents:

Ixspd1-2001 fe mobile layout is broken on swap token list 

---

src/components/LBP/InvestmentList/LbpCard.tsx
src/components/Launchpad/InvestmentCard/index.tsx
src/components/Launchpad/InvestmentList/index.tsx
src/components/Launchpad/Offers/Pinned.tsx

…tton
- connect wallet popup should be displayed when user clicks invest button
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2020
2. Documents:

Ixspd1-2020 fe dev connect wallet popup should be displayed when user clicks invest button

---

src/pages/PayoutItem/ActionBlock/UserView.tsx

- token symbol and content if event is announced and user was not holding on record date
-
-
1. Jira ticket:[IXSPD1-1966]
2. Documents:
[IXSPD1-1966]: https://investax.atlassian.net/browse/IXSPD1-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-1966] token symbol and content if event is announced

---

src/pages/CreatePayoutEvent/PayoutType.tsx
src/pages/CreatePayoutEvent/mock.ts
src/pages/CreatePayoutEvent/validation.ts

- refactor payout event creation form
-
-
2. Documents:

feat: refactor payout event creation form

---

src/hooks/useEthersProvider.ts
src/hooks/useWeb3React.ts

- Cannot Invest a deal if user connected wallet via scanning QR code
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2021
2. Documents:

Ixspd1-2021 dev cannot invest a deal if user connected wallet via scanning qr code

---

src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/PayoutType.tsx

- payout normalizes event type
-
-
2. Documents:

feat: payout normalizes event type

---

src/components/Button/index.tsx
src/components/MultipleFilters/index.tsx
src/components/MultipleFilters/styleds.ts
src/components/Table/index.tsx
src/components/TmPayoutEvents/index.tsx
src/components/TmPayoutEvents/styleds.ts
src/components/TmPayoutHistory/index.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/CreatePayoutEvent/PayoutType.tsx
src/pages/CreatePayoutEvent/mock.ts
src/pages/CreatePayoutEvent/validation.ts
src/pages/PayoutItem/ActionBlock/ManagerView.tsx
src/pages/PayoutItem/ActionBlock/UserView.tsx
src/pages/PayoutItem/Timeline/PayoutTimeline.tsx
src/pages/PayoutItem/Timeline/TimelineDate.tsx
src/pages/PayoutItem/Timeline/TodayIndicator.tsx
src/pages/TokenManager/index.tsx

- update indicator position
- highlight start date button
- styles of token manager payout list
- update the notification if the event is delayed
- add clear button in payout history page
2. Documents:

feat: enhance UI on payout detail (#2864)

---

package.json
src/state/auth/hooks.ts
yarn.lock

- Cannot connect to CoinBase after disconnecting it (Scan QR)
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1983
2. Documents:

IXSPD1-1983 Cannot connect to CoinBase after disconnecting it (Scan QR)

---

src/hooks/useAddToMetamask.ts

- Launchpad - Add MetaMask button does not work
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2043
2. Documents:

IXSPD1-2043 - Launchpad - Add MetaMask button does not work

---

src/state/auth/hooks.ts

- Don't redirect to KYC page if user disconnect wallet
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2049
2. Documents:

IXSPD1-2049 Don't redirect to KYC page if user disconnect wallet

---

src/components/Web3Provider/constants.ts

- Coinbase wallet - Error: underlying network changed
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2050
2. Documents: 

Ixspd1-2050 fe dev coinbase wallet error underlying network changed

---

src/pages/PayoutItem/ActionBlock/ManagerView.tsx

Merge missing commit to staging

---

src/components/AdminSecurityCatalog/TokenPopup.tsx

- Token Catalog - The address of previous token is still display when admin Add new Token
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2053
2. Documents:

Ixspd1-2053 fe dev token catalog the address of previous token is still display when admin add new token

---

src/state/auth/hooks.ts

- WalletConnect- Zerion - Wallet is disconnected after refreshing the page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2058
2. Documents:

Ixspd1-2058 fe dev wallet connect zerion wallet is disconnected after refreshing the page

---

src/pages/Launchpad/Banner.tsx

-  cannot open learn more link if screen width is smaller than 2560
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2042
2. Documents:

Ixspd1-2042 fe dev cannot open learn more link if screen width is smaller than 2560

---

src/components/AdminSecurityCatalog/TokenForm/GeneralInfo.tsx
src/components/AdminSecurityCatalog/TokenForm/WithdrawalDetails.tsx

- Token Catalog - Country dropdown list should be Searchable
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2052
2. Documents:

Ixspd1-2052 fe dev token catalog country dropdown list should be searchable

---

src/components/AdminSecurityCatalog/TokenPopup.tsx

- Token Catalog - "Required" message just displays when admin clicks Continue button
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2051
2. Documents:

Ixspd1-2051 fe dev token catalog required message just displays when admin clicks continue button

---

src/components/Vault/FeeStatus.tsx
src/utils/formatCurrencyAmount.ts

- RWA - Withdraw fee is not correct
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2046
2. Documents:

Ixspd1-2046 be dev rwa withdraw fee is not correct

---

src/components/AdminSecurityCatalog/TokenForm/index.tsx

- Fix redirect issue
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2026
2. Documents:

Ixspd1-2026 fix redirect issue

---

src/components/SearchModal/CurrencySearch.tsx
src/constants/tokens.ts

- only show the approved tokens on Swap/Liquidity list
-
-
1. Jira ticket: [IXSPD1-2047]
2. Documents:
[IXSPD1-2047]: https://investax.atlassian.net/browse/IXSPD1-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2047] only show the approved tokens on Swap/Liquidity list

---

src/components/AdminSecurityCatalog/TokenForm/Availability.tsx
src/components/AdminSecurityCatalog/TokenForm/GeneralInfo.tsx
src/components/AdminSecurityCatalog/TokenForm/helper.ts
src/components/AdminSecurityCatalog/TokenForm/index.tsx
src/components/AdminSecurityCatalog/mock.ts

-  Secondary listing -  Some fields were accidentally changed after editing the token form
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2062
2. Documents:

Ixspd1-2062 fe dev secondary listing some fields were accidentally changed after editing the token form

---

src/components/AdminSecurityCatalog/TokenForm/WrappedTokenDetails.tsx
src/components/AdminSecurityCatalog/TokenForm/index.tsx

- Secondary listing Add wrapped token address to Wrapped Token details
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2066
2. Documents:

Ixspd1-2066 fe secondary listing add wrapped token address to wrapped token details

---

src/components/AdminSecurityCatalog/TokenForm/helper.ts
src/components/AdminSecurityCatalog/TokenForm/index.tsx
src/components/AdminSecurityCatalog/index.tsx

- Secondary listing - Don't scrolled down to the page bottom after admin creates, edits the Token
- Improve compare change function
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2065
2. Documents:

Ixspd1-2065 fe dev secondary listing don t scrolled down to the page bottom after admin creates edits the token

---

src/components/AdminSecurityCatalog/index.tsx

- Secondary listing - Incorrect navigation when user clicks Back from the Edit Issuer page
-
-
1. Jira ticket: Secondary listing - Incorrect navigation when user clicks Back from the Edit Issuer page
2. Documents:

Ixspd1-2063 fe dev secondary listing incorrect navigation when user clicks back from the edit issuer page

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx

- show max length token ticker
- 
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2029
2. Documents:

IXSPD1-2029 show max length token ticker

---

src/components/AdminSecurityCatalog/TokenForm/index.tsx

- Secondary listing - Fix display of Withdraw fee in Token Catalog
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2068
2. Documents:

Ixspd1-2068 fe dev secondary listing fix display of withdraw fee in token catalog

---

src/components/KycReviewModal/KycReviewModalV2.tsx

- Enable action buttons on KYC review page even though KYC were approved or rejected.
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2019
2. Documents:

Ixspd1-2019 fe enable action buttons on kyc review page even though kyc were approved or rejected

---

src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts

- Limit the length of "Token Ticker" to 10 characters
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2029
2. Documents:

IXSPD1-2029 Update validate message text

---

src/services/apiService.ts

- Rainbowkit - Sign button is loading when the user has just accessed IXS on Mobile
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2070
2. Documents:

Ixspd1-2070 fe dev rainbowkit sign button is loading when the user has just accessed ixs on mobile

---

src/components/Header/AdministrationMenu.tsx

- UI bug relates to the administration menu
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1981
2. Documents:

IXSPD1-1981 UI bug relates to the administration menu

---

src/components/AdminKyc/ReminderModal.tsx
src/components/Header/AdministrationMenu.tsx

- Kyc page crashes when admin searches or filters the Draft KYC
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2083
2. Documents:

Ixspd1-2083 dev kyc page crashes when admin searches or filters the draft kyc

---

src/components/MultipleFilters/constants.ts

-
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1859
2. Documents:

IXSPD1-1859 Update the filters on Users page

---

src/components/Header/AdministrationMenu.tsx

- Fix administrator menu
-
-
2. Documents:

Fix administrator menu

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx
src/components/LaunchpadIssuance/IssuanceForm/shared/fields/ImageField.tsx

- Issuance form - Required message is still displayed after uploading pictures
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1989
2. Documents:

Ixspd1-1989 fe dev issuance form required message is still displayed after uploading pictures

---

src/components/Web3Provider/constants.ts

- Remove Ethereum in the network list
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2090
2. Documents:

IXSPD1-2090 Remove Ethereum in the network list

---

src/components/Web3Provider/wagmi.ts
src/state/auth/hooks.ts

-  Cannot open QR code without deleting WALLET_CONNECT_V2 in indexedD
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2092
2. Documents:

Ixspd1-2092 fe staging cannot open qr code without deleting wallet connect v2 in indexed db

---

src/components/AdminSecurityCatalog/TokenForm/helper.ts

- kycType is not correct after admin edit the Token Catalog
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2095
2. Documents:

Ixspd1-2095 be staging kyc type is not correct after admin edit the token catalog

---

src/components/Header/index.tsx
src/state/auth/hooks.ts

- Mobile - Redundant button should be removed on ConnectWallet screen
- 
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2093
2. Documents:

IXSPD1-2093 fix disconnect and redundant button

---

src/components/Header/IXSBalanceModal.tsx

- Incorrect button name on Token popup
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2091
2. Documents:

Ixspd1-2091 fe staging incorrect button name on token popup

---

src/pages/LBP/PublicDetails.tsx

- CoinBase - Disconnect wallet does not work in LBP detail page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2097
2. Documents:

Ixspd1-2097 dev coin base disconnect wallet does not work in lbp detail page

---

src/pages/App.tsx

- Rainbowkit - Sign button does not work if the MetaMask is displaying switch chain popup
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2105
2. Documents:

Ixspd1-2105 dev stg rainbowkit sign button does not work if the meta mask is displaying switch chain popup

---

src/components/Web3Provider/wagmi.ts

- WalletConnect - Wallet is disconnected when user switches to unsupported network
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2057
2. Documents:

Ixspd1-2057 fe dev wallet connect wallet is disconnected when user switches to unsupported network

---

src/components/AdminSecurityCatalog/TokenPopup.tsx

-  Secondary listing - The error message and value are not cleared
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2100
2. Documents:

Ixspd1-2100 dev stg secondary listing the error message and value are not cleared

---

src/pages/Tenant/TenantForm.tsx
src/pages/Tenant/components/Design.tsx
src/pages/Tenant/components/FooterConfig.tsx
src/pages/Tenant/components/GeneralInfo.tsx
src/pages/Tenant/components/ImageUpload.tsx
src/pages/Tenant/components/KYCLinks.tsx
src/pages/Tenant/components/SupportInformation.tsx

- Saas config - The required messages are not cleared when the values were input
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2075
2. Documents:

Ixspd1-2075 fe dev saas config the required messages are not cleared when the values were input

---

src/state/auth/hooks.ts

- Development => staging
-
-
2. Documents:

Development => staging

---

src/components/Web3Provider/wagmi.ts
src/config/index.ts
src/walletConnectConfig.json

- Rainbowkit - Cannot open WalletConnect's QR code on Readi tenant
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2115
2. Documents:

Ixspd1-2115 dev stg rainbowkit cannot open wallet connect s qr code on readi tenant

---

src/components/Web3Provider/wagmi.ts
src/config/index.ts
src/walletConnectConfig.json

…n readi tenant (#2949)
* Rainbowkit - Cannot open WalletConnect's QR code on Readi tenant
* Update env for production
-
-
-
2. Documents:

dev => staging

---

src/walletConnectConfig.json

- dev to staging
-
-
2. Documents:

dev to staging

---

src/components/Web3Provider/wagmi.ts
src/state/auth/hooks.ts
src/utils/index.ts

- Refactor clear indexDB
-
-
2. Documents:

Refactor clear indexDB

---

src/components/Launchpad/InvestmentCard/RaisedFund.tsx
src/pages/KYC/index.tsx

- button Pass KYC as Individual is not clickable
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2122
2. Documents:

IXSPD1-2122 button Pass KYC as Individual is not clickable

---

src/components/NumericalInput/index.tsx

- Could not input decimal number when swap
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2121
2. Documents:

IXSPD1-2121 ios could not input decimal number when swap

---

src/components/Web3Provider/index.tsx

`##` Description
-  User sometimes cannot Sign to connect Coinbase wallet -Scan QR
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2118
2. Documents:

Ixspd1-2118 fe prod user sometimes cannot sign to connect coinbase wallet scan qr

---

src/components/Web3Provider/wagmi.ts
src/hooks/useWeb3React.ts
src/state/auth/hooks.ts

-  Fix cannot connect coinbase with QR scan
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2117
2. Documents:

IXSPD1-2117 Fix cannot connect coinbase with QR scan

---

src/components/Web3Provider/wagmi.ts
src/hooks/useWeb3React.ts
src/state/auth/hooks.ts

Reverts IX-Swap/interface#2961

Revert "IXSPD1-2117 Fix cannot connect coinbase with QR scan"

---

src/components/Web3Provider/wagmi.ts
src/state/auth/hooks.ts

- FIx wallet connect
-
-
2. Documents:

FIx wallet connect

---

src/hooks/personalSign.ts

- Handle reload when sign error in coinbase
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2117
2. Documents:

IXSPD1-2117 Handle reload when sign error in coinbase

---

src/components/Vault/FeeStatus.tsx
src/components/Vault/WithdrawRequestForm.tsx

- Fix UI off the Withdraw button when user clicks on it
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2127
2. Documents:

IXSPD1-2127 Add loading for withdraw button

---

src/pages/App.tsx
src/pages/Launchpad/index.tsx

- Switch chain popup does not work on launchpad page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2144
2. Documents:

IXSPD1-2144 Switch chain popup does not work on launchpad page

---

src/components/Header/AdministrationMenu.tsx

- Menu - Cannot open DashBoard when using touchpad to click
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2149
2. Documents:

IXSPD1-2149 Menu - Cannot open DashBoard when using touchpad to click

---

src/components/Header/AdministrationMenu.tsx
src/components/Header/NetworkCard.tsx

- menu cannot open dash board when using touchpad to click
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2149
2. Documents:

Ixspd1-2149 fe menu cannot open dash board when using touchpad to click

---

src/components/Vault/WithdrawRequestForm.tsx

- Fix UI off the Withdraw button when user clicks on it
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2127
2. Documents:

Ixspd1-2127 fe fix UI off the withdraw button when user clicks on it

---

src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
src/state/launchpad/hooks.ts

- pass amount param when user request presale proof
-
-
1. Jira ticket: [IXSPD1-2106]
2. Documents:
[IXSPD1-2106]: https://investax.atlassian.net/browse/IXSPD1-2106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2106] improve validation for investment api

---

src/walletConnectConfig.json

Update wallet connect ids for digital x
2. Documents:

Update wallet connect ids for digital x

---

src/walletConnectConfig.json

Update wallet connect ids for digital x (#2977)

---

src/pages/Launchpad/Banner.tsx

- Hide total raised if not isIxswap
-
-
2. Documents:

Hide total raised if not isIxswap

---

src/components/Header/HeaderLinks.tsx
src/components/Header/index.tsx

- DigitalX: Update Main Menu
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2165
2. Documents:

Ixspd1-2165 fe digital x update main menu

---

src/pages/KYC/IndividualKycFormV2.tsx
src/state/kyc/hooks.ts

- kyc is secondary contact verified is false if user select poa after clicking send code button
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2184
2. Documents:

Ixspd1-2184 be kyc is secondary contact verified is false if user select poa after clicking send code button

---

src/state/kyc/hooks.ts

- Add miss url individual
-
-
2. Documents:

IXSPD1-2184 Add miss url individual

---

src/assets/images/icons/alert.svg
src/pages/KYC/CountriesBlockAlert.tsx
src/pages/KYC/IndividualKycFormV2.tsx
src/pages/KYC/styleds.tsx

- Add KYC guidance telling users not using copied document
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2140
2. Documents:

Ixspd1-2146 design add kyc guidance telling users not using copied document

---

src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
src/components/LaunchpadOffer/InvestDialog/utils/InvestSubmitButton.tsx
src/state/launchpad/hooks.ts

- pass amount argument to retrieve the proof of presale 
- show particular investment error message on modal
1. Jira ticket: [IXSPD1-2177]
2. Documents:
[IXSPD1-2177]: https://investax.atlassian.net/browse/IXSPD1-2177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2177] show particular investment error message on modal

---

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx

- launchpad disable claim button when start claiming
-
-
1. Jira ticket: [IXSPD1-2193]
2. Documents:
[IXSPD1-2193]: https://investax.atlassian.net/browse/IXSPD1-2193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2193] launchpad disable claim button when start claiming

---

src/walletConnectConfig.json

- Add project id for 1assetexchange
-
-
2. Documents:

Add project id for 1assetexchange

---

src/walletConnectConfig.json

- Add project id for 1assetexchange
-
-
2. Documents:

Add project  id for 1assetexchange

---

src/components/Launchpad/NetworkNotAvailable/index.tsx
src/components/Launchpad/NetworkNotAvailable/styled.tsx
src/components/NotAvailablePage/styled.ts
src/components/Web3Provider/index.tsx
src/pages/AddLiquidityV2/index.tsx
src/pages/AddLiquidityV2/redirects.tsx
src/pages/Admin/index.tsx
src/pages/AppBody.tsx
src/pages/CreatePayoutEvent/EditPayoutEvent.tsx
src/pages/Farming/StakingTab.tsx
src/pages/Farming/VestingTab.tsx
src/pages/LBP/PublicDetails.tsx
src/pages/LBP/components/Tokenomics.tsx
src/pages/LBP/layout.tsx
src/pages/LaunchpadIssuance/layout.tsx
src/pages/LaunchpadOffer/index.tsx
src/pages/PayoutItem/PayoutHeader.tsx
src/pages/Pool/v2.tsx
src/pages/RemoveLiquidity/index.tsx
src/pages/SecTokenDetails/index.tsx
src/pages/SecurityTokens/index.tsx
src/pages/TokenManager/index.tsx

- Handling unsupported networks on pages requiring RPC calls
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2205
2. Documents:

Ixspd1-2205 fe handling unsupported networks on pages requiring rpc calls

---

src/pages/Launchpad/Banner.tsx

- Launchpad - Open the new tab when clicking on "Learn more" btn
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1709
2. Documents:

Ixspd1-1709 fe launchpad open the new tab when clicking on learn more btn

---

src/components/Header/index.tsx

- MultiChain - Default network is not switched when user connects with active network = Polygon Amoy
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2221
2. Documents:

Ixspd1-2221 fe dev multi chain default network is not switched when user connects with active network polygon amoy

---

src/components/Launchpad/NetworkNotAvailable/index.tsx
src/components/Web3Provider/constants.ts

- Ozean - Popup display Unknown when user switch to Ozean on L pool page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2237
2. Documents:

Ixspd1-2237 fe dev ozean popup display unknown when user switch to ozean on l pool page

---

src/components/Header/NetworkCard.tsx
src/components/Header/index.tsx

…ng network
- Multichain - Network button does not display if WalletConnect has wrong network
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2239
2. Documents:

Ixspd1-2239 fe dev multichain network button does not display if wallet connect has wrong network

---

src/components/Header/NetworkCard.tsx
src/pages/KYC/index.tsx

- Multichain - KYC status is incorrect if user has not Sign on MetaMask
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2246
2. Documents:

Ixspd1-2246 fe dev multichain kyc status is incorrect if user has not sign on meta mask

---

package.json
src/assets/images/chains/kaia.svg
src/components/Web3Provider/constants.ts
src/constants/chains.ts
src/pages/AddLiquidityV2/index.tsx
src/pages/Farming/Staking/StakingOtherNetworkCard.tsx
src/state/stake/contstants.ts
src/types/chains.ts
yarn.lock

- Add Kaia chain
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2248
2. Documents:

IXSPD1-2248 Add Kaia chain

---

src/components/Header/NetworkCard.tsx

- MultiChain - Network button does not display when switching to some network
-
-
2. Documents:

Ixspd1-2249 fe dev multi chain network button does not display when switching to some network

---

src/components/AdminKyc/index.tsx

- KYC v2 Enhancement
-
-
- https://investax.atlassian.net/browse/IXSPD1-2240
- https://investax.atlassian.net/browse/IXSPD1-2241
- https://investax.atlassian.net/browse/IXSPD1-2244
- https://investax.atlassian.net/browse/IXSPD1-2245
3. Documents:

IXSPD1-2139 KYC Dashboard

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts
src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts
src/state/launchpad/types.ts

- Add ozean kaia chain in the network filter launchpad home page
- Add Ozean, Kaia chain in the network option of Issuance form
-
- https://investax.atlassian.net/browse/IXSPD1-2224
- https://investax.atlassian.net/browse/IXSPD1-2226
- https://investax.atlassian.net/browse/IXSPD1-2231
2. Documents:

Ixspd1-2224, IXSPD1-2226, IXSPD1-2231 fe add ozean kaia chain in the network filter launchpad home page

---

src/components/LaunchpadIssuance/ManageOffer/HeaderButtons.tsx
src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx
src/constants/chains.ts
src/utils/getExplorerLink.ts

…ton ( Kaia testnet)
- Multichain - Incorrect scan link opened when clicking on Explorer button ( Kaia testnet)
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2264
2. Documents:

Ixspd1-2264 fe dev multichain incorrect scan link opened when clicking on explorer button kaia testnet

---

src/components/Mobile-Menu/Menu.tsx

…er switches to Ozean and Kaia chains
- Multichain - The items of hamburger menu displays incorrectly when user switches to Ozean and Kaia chains
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2267
2. Documents:

Ixspd1-2267 fe dev multichain the items of hamburger menu displays incorrectly when user switches to ozean and kaia chains

---

src/components/LaunchpadOffer/OfferSummary/index.tsx
src/pages/LaunchpadOffer/index.tsx

- Error displays after refreshing issuance deal
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2215
2. Documents:

Ixspd1-2215 fe prod error displays after refreshing issuance deal

---

src/pages/SecTokenDetails/DetailsInfo.tsx

- Security Token - Clicking on Issuer link text displays the wrong page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1907
2. Documents:

Ixspd1-1907 fe prod security token clicking on issuer link text displays the wrong page

---

src/components/LaunchpadOffer/OfferSidebar/OfferStage.tsx
src/utils/chains.ts

- Launchpad - The value of timelines are not changed when user replaces the offerId
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2219
2. Documents:

Ixspd1-2219 fe launchpad the value of timelines are not changed when user replaces the offer

---

src/pages/Tenant/TenantForm.tsx
src/pages/Tenant/types.ts

…any invalid fields
- Saas config - Nothing happens when admin submits a tenant form with many invalid fields
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2169
2. Documents:

Ixspd1-2169 fe dev saas config nothing happens when admin submits a tenant form with many invalid fields

---

src/components/AdminSecurityCatalog/TokenForm/CustodyDetails.tsx
src/components/AdminSecurityCatalog/TokenForm/GeneralInfo.tsx
src/components/AdminSecurityCatalog/TokenForm/WithdrawalDetails.tsx
src/components/AdminSecurityCatalog/TokenForm/index.tsx
src/components/AdminSecurityCatalog/TokenForm/schema.ts

- Secondary Listing - Missing validation error message at some fields in token information form
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2158
2. Documents:

Ixspd1-2158 fe secondary listing missing validation error message at some fields in token information form

---

src/components/WhiteLabelFooter/CopyrightBlock.tsx
src/state/whitelabel/types.ts

- Saas config - Terms and Privacy have incorrect value
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2168 
2. Documents: 

Ixspd1-2168 fe dev saas config terms and privacy have incorrect value

---

src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx
src/components/LaunchpadOffer/OfferMainInfo/OfferGalleryViewer.tsx

- Improve UI of Gallery view on Launchpad issuance deal-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1803
2. Documents:

Ixspd1-1803 fe improve UI of gallery view on launchpad issuance deal

---

src/components/Header/NetworkCard.tsx
src/components/Web3Status/index.tsx

- Adjust the buttons on top of mobile screen
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2128
2. Documents:

Ixspd1-2128 fe adjust the buttons on top of mobile screen

---

src/components/Vault/WithdrawPopup.tsx

- Withdraw - The screen flashes continuously each time the user types a number
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1091
2. Documents:

Ixspd1-1091 fe prod withdraw the screen flashes continuously each time the user types a number

---

src/components/Launchpad/KYCPrompt/index.tsx
src/pages/LaunchpadOffer/index.tsx

- Clicking on the offer link sometimes directs to Launchpad page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2272
2. Documents:

Ixspd1-2272 fe prod clicking on the offer link sometimes directs to launchpad page

---

src/components/Launchpad/KYCPrompt/index.tsx

- Remove error
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2272
2. Documents:

IXSPD1-2272 Remove error

---

src/components/Pagination/index.tsx
src/constants/subgraph.ts
src/hooks/useSubgraphQuery.ts
src/lib/balancer/hooks/useCurrency.ts
src/lib/balancer/utils/numbers.ts
src/pages/AppRoutes.tsx
src/pages/DexV2/Pool/List/FilterProvider.tsx
src/pages/DexV2/Pool/List/Filters/NetworkCard.tsx
src/pages/DexV2/Pool/List/Filters/index.tsx
src/pages/DexV2/Pool/List/PoolList.tsx
src/pages/DexV2/Pool/List/constants.ts
src/pages/DexV2/Pool/List/hooks.ts
src/pages/DexV2/Pool/List/index.tsx
src/theme/index.tsx
src/theme/styled.d.ts
src/utils/routes.ts
yarn.lock

- add liquidity pool page
-
-
1. Jira ticket: [IXSPD1-2227]
2. Documents:
[IXSPD1-2227]: https://investax.atlassian.net/browse/IXSPD1-2227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2227] add liquidity pool page

---

src/pages/Tenant/helpers.ts

- Redirect to swap when try to create payout airdrop
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2282
2. Documents:

Ixspd1-2282 payout redirect to swap when try to create payout airdrop

---

src/components/LBP/PublicDetails/HistoryTable.tsx
src/components/LBP/PublicDetails/PublicChart.tsx
src/components/LBP/PublicDetails/StatisticData.tsx
src/hooks/useSubgraphQuery.ts
src/pages/DexV2/Pool/List/hooks.ts
src/pages/DexV2/Pool/Steps/ChooseWeights.tsx
src/pages/DexV2/Pool/components/BalAlert.tsx
src/state/dexV2/poolCreation/hooks/usePoolCreation.ts

- liquidity pool page prevent creating duplicated pool
- wrap the useSubgraphQuery via useQuery
-
1. Jira ticket: [IXSPD1-2278]
2. Documents:
[IXSPD1-2278]: https://investax.atlassian.net/browse/IXSPD1-2278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2278] liquidity pool page prevent creating duplicated pool

---

src/assets/images/dex-v2/gift.svg
src/assets/images/dex-v2/percentage.svg
src/assets/images/dex-v2/warning.svg
src/constants/addresses.ts
src/pages/AppRoutes.tsx
src/pages/DexV2/Lock/LockProvider.tsx
src/pages/DexV2/Lock/components/CurrencyInput.tsx
src/pages/DexV2/Lock/components/DurationSlider.tsx
src/pages/DexV2/Lock/components/LockBenefits.tsx
src/pages/DexV2/Lock/components/LockContent.tsx
src/pages/DexV2/Lock/components/LockExplanation.tsx
src/pages/DexV2/Lock/components/VerticleSteps.tsx
src/pages/DexV2/Lock/index.tsx
src/pages/DexV2/Lock/types/index.ts
src/pages/DexV2/Pool/components/BalAlert.tsx
src/pages/DexV2/Pool/components/TokenInput.tsx
src/theme/index.tsx
src/theme/styled.d.ts
src/utils/routes.ts

- lock IXS to receive veIXS
-
-
1. Jira ticket: [IXSPD1-2281]
2. Documents:
[IXSPD1-2281]: https://investax.atlassian.net/browse/IXSPD1-2281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2281] lock IXS to receive veIXS

---

src/constants/countriesList.ts

- Remove blocking IP for US/North Korea at app level
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2290
2. Documents:

Ixspd1-2290 fe remove blocking ip for us north korea at app level

---

src/constants/countriesList.ts

- Remove blocking IP for US/North Korea at app level
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2290
2. Documents:

IXSPD1-2290 Remove blocking IP for US/North Korea at app level

---

src/pages/Tenant/helpers.ts

- Hotfix for Redirect to swap when try to create payout airdrop
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2282
2. Documents:

IXSPD1-2282 Redirect to swap when try to create payout airdrop

---

src/pages/Tenant/TenantForm.tsx

- Saas Config - Customize the pages for Ix Swap Tenant
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2297
2. Documents:

Ixspd1-2297 fe saas config customize the pages for ix swap tenant

---

src/components/Header/HeaderLinks.tsx
src/components/Mobile-Menu/Menu.tsx
src/pages/Tenant/helpers.ts

- Saas mobile menu bug : still show irreleavant items
-
-
2. Documents:

Ixspd1-2298 fe saas mobile menu bug still show irreleavant items

---

src/components/AccountDetails/index.tsx
src/components/NotAvailablePage/ConnectWalletCard.tsx

Hide staking info

---

src/components/LaunchpadIssuance/utils/Dialog.tsx
src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx
src/components/LaunchpadOffer/InvestDialog/utils/InvestSuccessModal.tsx
src/components/LaunchpadOffer/InvestDialog/utils/InvestTextField.tsx

- Mobile - Fix some UI bugs on Invest Dashboard
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2305
2. Documents:

Ixspd1-2305 fe mobile fix some UI bugs on invest dashboard

---

src/pages/KYC/CountriesBlockAlert.tsx
src/pages/KYC/SecondaryContactOption.tsx

- Fix UI for kyc
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2305
2. Documents:

IXSPD1-2305 Fix UI for kyc

---

src/components/Vault/AmountInput.tsx
src/components/Vault/WithdrawRequestForm.tsx
src/state/withdraw/hooks.ts

- Fix error decimals
-
-
- https://investax.atlassian.net/browse/IXSPD1-1091 
- https://investax.atlassian.net/browse/IXSPD1-2306
- https://investax.atlassian.net/browse/IXSPD1-2307
3. Documents:

Ixspd1-1091 fe prod withdraw the screen flashes continuously each time the user types a number 1

---

src/pages/AppRoutes.tsx
src/pages/DexV2/Dashboard/components/Card.tsx
src/pages/DexV2/Dashboard/components/LiquidityRewards.tsx
src/pages/DexV2/Dashboard/components/LockRewards.tsx
src/pages/DexV2/Dashboard/components/VotingRewards.tsx
src/pages/DexV2/Dashboard/index.tsx
src/theme/index.tsx
src/theme/styled.d.ts
src/utils/routes.ts

- add v2 dashboard
-
-
1. Jira ticket: [IXSPD1-2312]
2. Documents:
[IXSPD1-2312]: https://investax.atlassian.net/browse/IXSPD1-2312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2312] add v2 dashboard

---

src/components/LBP/InvestmentList/LbpCard.tsx
src/components/LBP/InvestmentList/LbpList.tsx
src/components/Launchpad/InvestmentCard/index.tsx
src/components/Launchpad/InvestmentList/index.tsx
src/components/LaunchpadOffer/InvestDialog/utils/InvestSubmitButton.tsx

- Mobile - some UI bugs on Invest Dashboard
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2311
2. Documents:

Ixspd1-2311 UI i os mobile some UI bugs on invest dashboard

---

package.json
src/components/Web3Provider/constants.ts
yarn.lock

Hot Fix kaia wrong rpc, update default token list sdk version

---

package.json
src/components/Web3Provider/constants.ts
yarn.lock

Fix kaia wrong rpc, update default token list sdk version

---

src/components/AccountDetails/ReferFriend.tsx
src/pages/App.tsx
src/pages/KYC/index.tsx

Fix referral link

---

src/pages/KYC/IndividualKycFormV2.tsx

- KYC screen is broken if there is a referral code
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2335
2. Documents:

IXSPD1-2335 KYC screen is broken if there is a referral code

---

src/components/Rewards/TaskSuccessModal.tsx
src/constants/lineRewards.ts
src/hooks/useLineReward.ts

…campaign reward
- this PR to validate if user claimed joining campaign point and skip adding point
-
-
2. Documents:

fix: validate if user claimed campaign point and skip submit joining point

---

src/components/Rewards/TaskSuccessModal.tsx

- wording message
-
-
2. Documents:

fix: wording message

---

src/pages/KYC/IndividualKycForm.tsx
src/pages/KYC/IndividualKycFormV2.tsx

Cherrypick fix referral UI issue

---

src/components/Rewards/TaskSuccessModal.tsx

- line reward enables to click on claim button and close popup
-
-
2. Documents:

fix: line reward enables to click on claim button and close popup

---

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx

- Update the message on Claim dashboard - Unsuccessful issuance deal
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1698
2. Documents:

Ixspd1-1698 fe update the message on claim dashboard unsuccessful issuance deal

---

src/pages/Pool/v2.tsx

- UI bug Liquidity Pools
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2342
2. Documents:

IXSPD1-2342 UI bug Liquidity Pools

---

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx
src/components/LaunchpadOffer/InvestDialog/index.tsx
src/components/LaunchpadOffer/InvestDialog/utils/InvestSubmitButton.tsx
src/components/LaunchpadOffer/InvestDialog/utils/InvestSuccessModal.tsx

- UI bugs on Register to Invest dashboard
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2346
2. Documents:

IXSPD1-2346 UI bugs on Register to Invest dashboard

---

src/pages/Launchpad/Footer.tsx

- Fix new logo on the footer
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2347
2. Documents:

IXSPD1-2347 Fix new logo on the footer

---

src/index.css
src/services/apiService.ts

- Refactor API Service to Handle 401 Unauthorized Responses Gracefully
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2348
2. Documents:

Ixspd1-2348 fe refactor api service to handle 401 unauthorized responses gracefully

---

src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
src/components/LaunchpadOffer/InvestDialog/index.tsx

- Fix invest dashboard
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2346
2. Documents:

Ixspd1-2346 fe UI bugs on register to invest dashboard

---

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx
src/components/Vault/BalanceRow.tsx
src/components/Vault/ExistingVault.tsx
src/pages/AppRoutes.tsx
src/pages/Maintenance/index.tsx

- Disable claim offer
-
-
2. Documents:

Hotfix: Give notice of refund for specific deals

---

src/components/Launchpad/Offers/Pinned.tsx

- The button is always displayed "Invest" on the Pinned deal
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1776
2. Documents:

Ixspd1-1776 fe staging the button is always displayed invest on the pinned deal

---

src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx
src/pages/App.tsx

- display invest success modal for line liff
-
-
1. Jira ticket: [IXSPD1-2353]
2. Documents:
[IXSPD1-2353]: https://investax.atlassian.net/browse/IXSPD1-2353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2353] display invest success modal for line liff

---

src/components/Vault/AmountInput.tsx
src/components/Vault/DepositRequestForm.tsx
src/state/deposit/hooks.ts
src/state/swap/helpers.ts

- FIx parse amount deposit form
-
-
2. Documents:

FIx parse amount deposit form

---

src/pages/Launchpad/index.tsx

- UI - The font was changed after merging Staging-client-demo branch
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-978
2. Documents:

Ixspd1-978 fe prod UI the font was changed after merging staging client demo branch

---

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx

- Add transaction hash for offer 40e1ce66-1532-4794-86c4-af465bf22a57
-
-
2. Documents:

Add transaction hash for offer 40e1ce66-1532-4794-86c4-af465bf22a57

---

package.json
yarn.lock

- Hot fix Delist wMSTO token
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2368
2. Documents:

IXSPD1-2368 Hot fix Delist wMSTO token

---

src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx
src/components/LaunchpadOffer/OfferSidebar/OfferSaleAllocation.tsx

- update launchpad offer detail
-
-
1. Jira ticket: [IXSPD1-2382]
2. Documents:
[IXSPD1-2382]: https://investax.atlassian.net/browse/IXSPD1-2382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2382] update launchpad offer detail

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts
src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts
src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts
src/state/launchpad/hooks.ts
src/state/launchpad/types.ts

- update issuance information form
-
-
1. Jira ticket: [IXSPD1-2380]
2. Documents:
[IXSPD1-2380]: https://investax.atlassian.net/browse/IXSPD1-2380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2380] update issuance information form

---

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx

- enable invest issuance with 2 digit number
-
-
1. Jira ticket: [IXSPD1-2409]
2. Documents:
[IXSPD1-2409]: https://investax.atlassian.net/browse/IXSPD1-2409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2409] enable invest issuance with 2 digit number

---

src/components/TokenLogo/index.tsx

- construct the token url by api url and uuid
-
-
1. Jira ticket: [IXSPD1-2414]
2. Documents:
[IXSPD1-2414]: https://investax.atlassian.net/browse/IXSPD1-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2414] construct the token url by api url and uuid

---

src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts

- require company number should have at least 4 chars
-
-
1. Jira ticket: [IXSPD1-2400]
2. Documents:
[IXSPD1-2400]: https://investax.atlassian.net/browse/IXSPD1-2400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2400] require company number should have at least 4 chars

---

src/components/CurrencyLogo/index.tsx

- logo on swap page
-
-
2. Documents:

fix: logo on swap page

---

src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts
src/state/launchpad/types.ts

- add RWA ERC20 Token standard into the standard dropdown of issuance form
1. Jira ticket: [IXSPD1-2453]
2. Documents:
[IXSPD1-2453]: https://investax.atlassian.net/browse/IXSPD1-2453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2453] add RWA ERC20 Token standard into the standard dropdown of issuance form

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx

- update mint amount preview for standard erc20
-
-
1. Jira ticket: [IXSPD1-2456]
2. Documents:
[IXSPD1-2456]: https://investax.atlassian.net/browse/IXSPD1-2456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IXSPD1-2459]: https://investax.atlassian.net/browse/IXSPD1-2459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2456] update mint amount preview for standard erc20

---

src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts

- alert message of validation between presaleAllocated and hard cap
-
-
2. Documents:

fix: alert message of validation between presaleAllocated and hard cap

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts
src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts

- total supply must greater or equal sale supply
-
-
1. Jira ticket: [IXSPD1-2459]
2. Documents:
[IXSPD1-2459]: https://investax.atlassian.net/browse/IXSPD1-2459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2459] total supply must greater or equal sale supply

---

src/hooks/login.ts
src/services/apiService.ts

- rotate refresh token and access token
-
-
1. Jira ticket: [IXSPD1-2464]
2. Documents:
[IXSPD1-2464]: https://investax.atlassian.net/browse/IXSPD1-2464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2464] rotate refresh token and access token

---

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx

- get token price by deal stage
-
-
2. Documents:

fix: get token price by deal stage

---

src/components/LaunchpadIssuance/ManageOffer/investments/InvestmentsList.tsx

- format amount out of investor
-
-
1. Jira ticket: [IXSPD1-2490]
2. Documents:
[IXSPD1-2490]: https://investax.atlassian.net/browse/IXSPD1-2490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2490] format amount out of investor

---

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx
src/components/LaunchpadOffer/InvestDialog/index.tsx

- parse invested amount with long decimals
-
-
1. Jira ticket: [IXSPD1-2509]
2. Documents:
[IXSPD1-2509]: https://investax.atlassian.net/browse/IXSPD1-2509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2509] parse invested amount with long decimals

---

src/components/LaunchpadIssuance/ManageOffer/investments/InvestmentsList.tsx
src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx
src/state/launchpad/hooks.ts

- format amount on invest dialog with 4 decimals
-
2. Documents:

fix: format amount on invest dialog with 4 decimals

---

src/services/apiService.ts

- Fix forever loop
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2520
2. Documents:

Ixspd1-2520 fe jwt logout handling and cookie selection based on user address

---

src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts

-
-
-
1. Jira ticket: [IXSPD1-2521]
2. Documents:
[IXSPD1-2521]: https://investax.atlassian.net/browse/IXSPD1-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2521] crash page once inputting 0. for token price

---

src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts

- validate presale price must less than public price
1. Jira ticket: [IXSPD1-2457]
2. Documents:
[IXSPD1-2457]: https://investax.atlassian.net/browse/IXSPD1-2457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2457] validate presale price must less than public price

---

src/hooks/postLogoutApi.ts
src/state/auth/hooks.ts

- Revert call logout api when disconnect wallet
-
-
2. Documents:

Revert call logout api when disconnect wallet

---

src/services/apiService.ts

- Fix not recall first api when refresh
-
-
2. Documents:

Fix not recall first api when refresh

---

src/services/apiService.ts

- Config to right instance
-
-
2. Documents:

Config to right instance

---

src/components/LaunchpadIssuance/IssuanceForm/Information/sections/UploadDocuments.tsx
src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FileField.tsx
src/pages/AddLiquidityV2/index.tsx
src/state/launchpad/hooks.ts

- missing upload file name when create offer
-
-
1. Jira ticket: [IXSPD1-2513]
2. Documents:
[IXSPD1-2513]: https://investax.atlassian.net/browse/IXSPD1-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2513] missing upload file name when create offer

---

src/components/CurrencyLogo/index.tsx
src/constants/tokens.ts

- add logo for RedBelly native token on swap
-
-
2. Documents:

fix: logo for RedBelly native token on swap

---

src/components/LaunchpadIssuance/IssuanceForm/types.ts
src/state/launchpad/hooks.ts

- passing correct file id if there is no file change
-
-
1. Jira ticket: [IXSPD1-2513]
2. Documents:
[IXSPD1-2513]: https://investax.atlassian.net/browse/IXSPD1-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2513] passing correct file id if there is no file change

---

src/components/Web3Provider/constants.ts
src/constants/chains.ts

- do not show redbelly on mainnet
2. Documents:

fix: do not show redbelly on mainnet

---

README.md
src/components/Mobile-Menu/Menu.tsx
src/components/PositionCard/PoolInformation.tsx
src/components/WhiteLabelFooter/CopyrightBlock.tsx
src/pages/Farming/Staking/StakeModal.tsx
src/pages/Farming/Staking/StakingTiers.tsx
src/pages/Launchpad/Footer.tsx

Update link in footer

---

src/walletConnectConfig.json

- Change domain names in wallet connect config
2. Documents:

Change domain in walletConnect config

---

src/hooks/dex-v2/queries/useLocksQuery.ts
src/pages/DexV2/Dashboard/components/LockRewards.tsx
src/pages/DexV2/Dashboard/graphql/dashboard.ts
src/services/balancer/contracts/ve-sugar.ts
src/services/lock/lock.service.ts

- integrate data from contract for Lock reward
-
-
1. Jira ticket: [IXSPD1-2561]
2. Documents:
[IXSPD1-2561]: https://investax.atlassian.net/browse/IXSPD1-2561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2561] integrate data from contract for Lock reward

---

src/pages/DexV2/Dashboard/components/LiquidityRow.tsx

- unstaked amount on the rewards page
-
-
2. Documents:

fix: unstaked amount on the rewards page

---

src/pages/DexV2/Dashboard/components/LockRewards.tsx
src/utils/routes.ts

-
-
-
1. Jira ticket: [IXSPD1-2561]
2. Documents:
[IXSPD1-2561]: https://investax.atlassian.net/browse/IXSPD1-2561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2561] update lock rewards section

---

src/assets/images/sync.svg
src/hooks/dex-v2/queries/useLockQuery.ts
src/pages/AppRoutes.tsx
src/pages/DexV2/Lock/Detail/LockDetailProvider.tsx
src/pages/DexV2/Lock/Detail/components/LockDetailContent.tsx
src/pages/DexV2/Lock/Detail/components/LockExtendAutoMaxLockMode.tsx
src/pages/DexV2/Lock/Detail/components/LockExtendDurationSlider.tsx
src/pages/DexV2/Lock/Detail/components/LockExtendExplanation.tsx
src/pages/DexV2/Lock/Detail/components/LockInfo.tsx
src/pages/DexV2/Lock/Detail/index.tsx
src/services/balancer/contracts/ve-sugar.ts
src/services/lock/lock.service.ts

-
-
-
1. Jira ticket: [IXSPD1-2562]
2. Documents:
[IXSPD1-2562]: https://investax.atlassian.net/browse/IXSPD1-2562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2562] implement the Lock extend feature

---

src/components/NumericalInput/index.tsx
src/pages/DexV2/Lock/Detail/components/LockDetailContent.tsx
src/pages/DexV2/Lock/Detail/components/LockIncreaseCurrencyInput.tsx
src/pages/DexV2/Lock/Detail/components/LockIncreaseExplanation.tsx

- implement the Lock increase feature
-
-
1. Jira ticket: [IXSPD1-2563]
2. Documents:
[IXSPD1-2563]: https://investax.atlassian.net/browse/IXSPD1-2563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2563] implement the Lock increase feature

---

src/pages/DexV2/Dashboard/components/LockRewards.tsx

- Update Lock sections: remove Lock Date column, Add Unlock At column, render Withdraw when the lock is expired.
-
-
1. Jira ticket: [IXSPD1-2573]
2. Documents:
[IXSPD1-2573]: https://investax.atlassian.net/browse/IXSPD1-2573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2573] Update Lock sections

---

src/components/AccountDetails/index.tsx
src/components/Header/HeaderLinks.tsx
src/components/LaunchpadIssuance/IssuanceForm/index.tsx
src/components/Mobile-Menu/Menu.tsx
src/pages/KYC/index.tsx
src/pages/LBP/NotFound.tsx

- Change c@ixswap.io to c@ixs.finance on UI
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2577
2. Documents:

IXSPD1-2577 Change c@ixswap.io to c@ixs.finance on UI

---

src/index.css

- Fix number zero
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2577
2. Documents:

Ixspd1-2577 fe change c ixswap.io to c ixs.finance on UI

---

src/components/AccountDetails/index.tsx
src/components/Header/HeaderLinks.tsx
src/components/LaunchpadIssuance/IssuanceForm/index.tsx
src/components/Mobile-Menu/Menu.tsx
src/index.css
src/pages/KYC/index.tsx
src/pages/LBP/NotFound.tsx

**Release Date:** April 11, 2025
- **UI Update:**  
- Changed the email address from **c@ixswap.io** to **c@ixs.finance** on the UI.  
- *Commit by: @leonthuongto*
- **Font Fix:**  
- Corrected the display issue with the numeral **0** where it showed incorrectly as a slashed zero.  
- *Commit by: @leonthuongto*
This hotfix addresses two critical issues:
1. **Email Correction:**  
The UI now reflects the updated email **c@ixs.finance** ensuring that users see the correct contact information.
2. **Font Correction:**  
The numeral **0** font has been fixed to display correctly without the unwanted slash, improving readability.

Feature change to new email + fix wrong font number zero

---

src/components/KycDocPreviewModal/index.tsx
src/components/KycReviewModal/IndividualForm.tsx
src/components/KycReviewModal/molecules/Documents.tsx
src/components/TokenLogo/utils.ts

- attach auth header when fetching protected files
-
-
1. Jira ticket: [IXSPD1-2578]
2. Documents:
[IXSPD1-2578]: https://investax.atlassian.net/browse/IXSPD1-2578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2578] attach auth header when fetching protected files

---

src/services/balancer/contracts/ve-sugar.ts

fix: add vote list to the veSugar

---

src/hooks/dex-v2/queries/useLocksQuery.ts
src/pages/DexV2/Dashboard/components/LockRewards.tsx

- update withdraw function for lock
-
-
1. Jira ticket: [IXSPD1-2571]
2. Documents:
[IXSPD1-2571]: https://investax.atlassian.net/browse/IXSPD1-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2571] update withdraw function for lock

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx

fix: show buttons and update text show more

---

src/constants/subgraph.ts

fix: subgraphql url for pool page

---

src/pages/DexV2/Pool/List/PoolList.tsx

- filter out small pool by TVL less than 0.001
-
-
2. Documents:

feat: filter out small pool by TVL less than 0.001

---

src/hooks/dex-v2/approvals/useTokenApprovalActions.ts
src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/components/AddLiquidityPreview/components/ActionSteps.tsx
src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/components/AddLiquidityPreview/index.tsx
src/pages/DexV2/Pool/AddLiquidity/index.tsx
src/pages/DexV2/Pool/List/PoolList.tsx
src/pages/DexV2/Pool/List/hooks.ts
src/pages/DexV2/Pool/components/ActionSteps.tsx
src/pages/DexV2/Pool/components/CreateActions.tsx
src/state/dexV2/pool/useJoinPool.ts
src/state/dexV2/tokenLists/index.ts
src/state/dexV2/tokens/hooks/useTokens.ts

fix: create and join liquidity pool

---

src/hooks/dex-v2/queries/useFlattenedLocks.ts
src/hooks/dex-v2/queries/useVotingQuery.ts
src/lib/abi/RewardSugarABI.json
src/pages/DexV2/Dashboard/components/VotingRewards.tsx
src/services/balancer/contracts/ve-sugar.ts
src/services/reward-sugar/reward-sugar.contract.ts
src/services/reward-sugar/reward-sugar.service.ts

- Smart contract integration for Voting Rewards
-
-
1. Jira ticket: [IXSPD1-2592]
2. Documents:
[IXSPD1-2592]: https://investax.atlassian.net/browse/IXSPD1-2592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2592] Smart contract integration for Voting Rewards

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx
src/pages/DexV2/Dashboard/components/VotingRewards.tsx

- dashboard removes pool title
-
-
2. Documents:

fix: dashboard removes pool title

---

src/constants/dexV2/queryKeys.ts
src/hooks/dex-v2/queries/useVoteHistoriesQuery.ts
src/pages/DexV2/Pool/Withdraw/components/WithdrawPreviewModal.tsx
src/pages/DexV2/Vote/components/VoteHistoryRecords.tsx
src/pages/DexV2/Vote/index.tsx

- Handle voteHistoryRecords
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2607
2. Documents:

IXSPD1-2607 Handle voteHistoryRecords

---

src/abis/gaugeABI.json
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx
src/pages/DexV2/Dashboard/components/LockRewards.tsx
src/pages/DexV2/Dashboard/graphql/dashboard.ts
src/pages/DexV2/Dashboard/hooks/useLiquidityPool.ts
src/services/balancer/contracts/voter.ts

- dashboard populates earned trading fee and emission fee
-
-
1. Jira ticket: [IXSPD1-2608]
2. Documents:
[IXSPD1-2608]: https://investax.atlassian.net/browse/IXSPD1-2608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2608] dashboard populates earned trading fee and emission fee

---

amplify.yml

Fix amplify pipeline

---

src/state/dexV2/tokenLists/index.ts

- tokens are duplicated in the token list
-
-
1. Jira ticket: [IXSPD1-2605]
2. Documents:
[IXSPD1-2605]: https://investax.atlassian.net/browse/IXSPD1-2605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2605] tokens are duplicated in the token list

---

src/hooks/dex-v2/queries/useVoteInfoQuery.ts
src/pages/DexV2/Pool/Detail/components/PoolPageHeader.tsx
src/state/dexV2/pool/usePool.ts
src/state/dexV2/pool/usePoolQuery.ts

-  LP balance is not loaded properly in pool detail page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2616
2. Documents:

LP balance is not loaded properly in pool detail page

---

src/constants/addresses.ts
src/hooks/dex-v2/approvals/useTokenApprovalActions.ts
src/hooks/dex-v2/pools/usePropMaxJoin.ts
src/hooks/dex-v2/queries/useTokenPricesQuery.ts
src/hooks/useContract.ts
src/pages/DexV2/Dashboard/hooks/useLockReward.ts
src/pages/DexV2/Lock/Detail/LockDetailProvider.tsx
src/pages/DexV2/Lock/LockProvider.tsx
src/pages/DexV2/Pool/Staking/hooks/useStakePreview.ts
src/pages/DexV2/Swap/components/SwapPreviewModal.tsx

- spending cap display incorrect value when approving swap token
-
-
1. Jira ticket: [IXSPD1-2617]
2. Documents:
[IXSPD1-2617]: https://investax.atlassian.net/browse/IXSPD1-2617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2617] spending cap display incorrect value when approving swap token

---

src/pages/DexV2/Swap/components/SwapCard.tsx
src/pages/DexV2/common/BalAlert.tsx
src/state/dexV2/swap/useSwapping.ts

- Display message if there is no pool for selected pair
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2462
2. Documents:

IXSPD1-2462 Display message if there is no pool for selected pair

---

src/state/dexV2/swap/useSwapping.ts

- Handle mistake for handleAmountChange when change tokenOutAddressInput
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2462
2. Documents:

IXSPD1-2462 Handle mistake for handleAmountChange when change tokenOutAddressInput

---

src/pages/DexV2/Lock/Detail/components/LockExtendDurationSlider.tsx

- avoid extend with time less than current locked time
-
-
1. Jira ticket: [IXSPD1-2611]
2. Documents:
[IXSPD1-2611]: https://investax.atlassian.net/browse/IXSPD1-2611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2611] avoid extend with time less than current locked time

---

src/pages/DexV2/Vote/components/VotingRoundStats.tsx

- Vote display the countdown timer if remaining time is less than 1 day
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2622
2. Documents:

Ixspd1-2622 fe vote display the countdown timer if remaining time is less than 1 day

---

src/pages/DexV2/Lock/Detail/LockDetailProvider.tsx

- disable button increase/extend after complete increase/extend
-
-
1. Jira ticket: [IXSPD1-2613]
2. Documents:
[IXSPD1-2613]: https://investax.atlassian.net/browse/IXSPD1-2613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2613] disable button increase/extend after complete increase/extend

---

src/pages/DexV2/Lock/Detail/LockDetailProvider.tsx
src/pages/DexV2/Lock/Detail/components/LockDetailContent.tsx
src/pages/DexV2/Lock/Detail/components/LockExtendDurationSlider.tsx

- lock extend feature grays out the disabled range
-
-
2. Documents:

fix: lock extend feature grays out the disabled range

---

src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/components/TokenInput.tsx
src/pages/DexV2/Pool/Create/components/TokenInput.tsx
src/pages/DexV2/Pool/Withdraw/components/TokenInput.tsx

- exceeds balance error when clicking Max total button
-
-
1. Jira ticket: [IXSPD1-2471]
2. Documents:
[IXSPD1-2471]: https://investax.atlassian.net/browse/IXSPD1-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2471] exceeds balance error when clicking Max total button

---

src/pages/DexV2/Pool/Create/components/Steps/ChooseWeights.tsx

- Pool - Fix alerts when choosing tokens and weights
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2510
2. Documents:

IXSPD1-2510 Pool - Fix alerts when choosing tokens and weights

---

src/pages/DexV2/Pool/Staking/HorizSteps.tsx

- leverage tooltip for stake preview
-
-
1. Jira ticket: [IXSPD1-2603]
2. Documents:
[IXSPD1-2603]: https://investax.atlassian.net/browse/IXSPD1-2603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2603] leverage tooltip for stake preview

---

src/pages/DexV2/Lock/components/LockContent.tsx

- add Back button to Lock page
-
-
1. Jira ticket: [IXSPD1-2631]
2. Documents:
[IXSPD1-2631]: https://investax.atlassian.net/browse/IXSPD1-2631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2631] add Back button to Lock page

---

src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/components/TokenInput.tsx
src/pages/DexV2/Pool/Create/components/TokenInput.tsx
src/pages/DexV2/Pool/Create/components/TokenPriceInput.tsx
src/pages/DexV2/Pool/Withdraw/components/SingleTokenInput/index.tsx
src/pages/DexV2/Pool/Withdraw/components/TokenInput.tsx
src/pages/DexV2/Swap/components/TokenInput.tsx

…tton
- Pool - Exceed balance error displays when after clicking Max total button
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2471
2. Documents:

IXSPD1-2471 Pool - Exceed balance error displays when after clicking Max total button

---

src/hooks/dex-v2/pools/usePropMaxJoin.ts
src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/components/AddLiquidityTotals.tsx
src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/components/TokenInput.tsx
src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/index.tsx

- Remove some redundant fields in Add liquidity screen
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2626
2. Documents:

IXSPD1-2626 Remove some redundant fields in Add liquidity screen

---

src/hooks/dex-v2/pools/usePropMaxJoin.ts

- Handle check zero pool token
-
-
2. Documents:

Handle check zero pool token

---

src/pages/DexV2/Dashboard/components/VotingRewards.tsx

- voting rewards disable claim button
-
-
1. Jira ticket: [IXSPD1-2623]
2. Documents:
[IXSPD1-2623]: https://investax.atlassian.net/browse/IXSPD1-2623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2623] hide claim reward button if there is nothing to claim

---

src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/index.tsx
src/pages/DexV2/Pool/Create/components/Steps/InitialLiquidity.tsx
src/state/dexV2/poolCreation/hooks/usePoolCreation.ts
src/state/dexV2/poolCreation/index.ts

- Pool - Fix issues when removing number in token amount fields
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2637
2. Documents:

Ixspd1-2637 fe pool fix issues when removing number in token amount fields

---

src/abis/voterABI.json
src/pages/DexV2/Dashboard/components/ClaimVotingRewardButton.tsx
src/pages/DexV2/Dashboard/components/VotingRewards.tsx
src/pages/DexV2/Pool/List/PoolList.tsx
src/pages/DexV2/Pool/List/hooks.ts
src/services/balancer/contracts/voter.ts

- claim voting rewards
-
-
1. Jira ticket: [IXSPD1-2638]
2. Documents:
[IXSPD1-2638]: https://investax.atlassian.net/browse/IXSPD1-2638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2638] claim voting rewards

---

src/components/Countdown/index.tsx
src/pages/DexV2/Vote/components/SelectLockToVote/LockSelect.tsx
src/pages/DexV2/Vote/components/VoteHistoryRecords.tsx
src/pages/DexV2/Vote/components/VotingRoundStats.tsx
src/pages/DexV2/Vote/index.tsx

- vote countdown timer is not running
-
-
1. Jira ticket: [IXSPD1-2634]
2. Documents:
[IXSPD1-2634]: https://investax.atlassian.net/browse/IXSPD1-2634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2634] vote countdown timer is not running

---

src/hooks/dex-v2/queries/useVoteInfoQuery.ts
src/pages/DexV2/Vote/components/SelectLockToVote/LockSelect.tsx
src/pages/DexV2/Vote/components/SelectLockToVote/index.tsx
src/pages/DexV2/Vote/components/VotingRoundStats.tsx
src/pages/DexV2/Vote/index.tsx

- Should be able to vote after new epoch starts
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2639
2. Documents:

IXSPD1-2639 Should be able to vote after new epoch starts

---

src/pages/DexV2/Dashboard/components/Card.tsx
src/pages/DexV2/Dashboard/components/VotingRewards.tsx

- width of set of logos
-
-
2. Documents:

fix: width of set of logos

---

src/pages/DexV2/Pool/List/PoolList.tsx

- pool list page adds skeleton
-
-
2. Documents:

fix: pool list page adds skeleton

---

src/pages/DexV2/Vote/components/SelectLockToVote/index.tsx
src/pages/DexV2/Vote/components/VoteHistoryRecords.tsx
src/pages/DexV2/Vote/index.tsx

- Add function refetch vote histories when vote success
-
-
2. Documents:

Add function refetch vote histories when vote success

---

src/pages/DexV2/Lock/Detail/components/LockDetailContent.tsx

- add go to dashboard button to extend and Increase pages
-
-
1. Jira ticket: [IXSPD1-2640]
2. Documents:
[IXSPD1-2640]: https://investax.atlassian.net/browse/IXSPD1-2640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2640] add go to dashboard button to extend and Increase pages

---

src/pages/DexV2/Lock/Detail/components/LockDetailContent.tsx

- disable button increase and extend after done
-
-
1. Jira ticket: [IXSPD1-2613]
2. Documents:
[IXSPD1-2613]: https://investax.atlassian.net/browse/IXSPD1-2613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2613] disable button increase and extend after done

---

src/lib/utils/balancer/wrapper.ts
src/pages/DexV2/Swap/components/SwapCard.tsx
src/pages/DexV2/Swap/components/SwapPair.tsx
src/pages/DexV2/Swap/components/TokenInput.tsx
src/pages/DexV2/common/TokenSelectInput.tsx
src/state/dexV2/swap/useSor.ts

- display eth in token list for wrapping token
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2643
2. Documents:

Ixspd1-2643 fe display eth in token list for wrapping token

---

src/pages/DexV2/Vote/components/VotingRoundStats.tsx
src/pages/DexV2/Vote/index.tsx

- render skeleton on fetching stats
-
-
1. Jira ticket: [IXSPD1-2634]
2. Documents:
[IXSPD1-2634]: https://investax.atlassian.net/browse/IXSPD1-2634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2634] render skeleton on fetching stats

---

src/pages/DexV2/Pool/Staking/ActionSteps.tsx
src/state/dexV2/poolStaking/index.ts
src/state/dexV2/poolStaking/usePoolStaking.ts

- Stake - Staked Token Amount Not Updated After Successful Staking
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2604
2. Documents:

Ixspd1-2604 fe stake staked token amount not updated after successful staking

---

src/pages/DexV2/common/modals/SelectTokenModal/index.tsx
src/state/dexV2/tokens/hooks/useTokens.ts

- do not show or search LP tokens in swapping page
-
-
1. Jira ticket: [IXSPD1-2451]
2. Documents:
[IXSPD1-2451]: https://investax.atlassian.net/browse/IXSPD1-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2451] do not show or search LP tokens in swapping page

---

src/pages/DexV2/Pool/Create/index.tsx

- reset create pool form when component is unmounted
-
-
1. Jira ticket: [IXSPD1-2499]
2. Documents:
[IXSPD1-2499]: https://investax.atlassian.net/browse/IXSPD1-2499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2499] reset create pool form when component is unmounted

---

src/hooks/useWrapCallback.ts

- populate correspond ticker on swapping native token
-
-
1. Jira ticket: [IXSPD1-2647]
2. Documents:
[IXSPD1-2647]: https://investax.atlassian.net/browse/IXSPD1-2647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2647] populate correspond ticker on swapping native token

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx
src/pages/DexV2/Pool/Staking/StakingCard.tsx
src/pages/DexV2/Pool/Staking/hooks/useStakePreview.ts

- inject token and gauge to validate allowance of staking
-
-
1. Jira ticket: [IXSPD1-2649]
2. Documents:
[IXSPD1-2649]: https://investax.atlassian.net/browse/IXSPD1-2649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2649] inject token and gauge to validate allowance of staking

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx

- fix ui when there are more than 2 tokens in pool
-
-
1. Jira ticket: [IXSPD1-2650]
2. Documents:
[IXSPD1-2650]: https://investax.atlassian.net/browse/IXSPD1-2650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2650] fix ui when there are more than 2 tokens in pool

---

src/pages/DexV2/Pool/components/CreateActions.tsx

- transfer amount exceeds when user funds pool
-
-
1. Jira ticket: [IXSPD1-2660]
2. Documents:
[IXSPD1-2660]: https://investax.atlassian.net/browse/IXSPD1-2660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2660] transfer amount exceeds when user funds pool

---

src/pages/DexV2/Pool/Detail/components/MyPoolBalancesCard.tsx

- display user pool balance per each token
-
-
1. Jira ticket: [IXSPD1-2553]
2. Documents:
[IXSPD1-2553]: https://investax.atlassian.net/browse/IXSPD1-2553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2553] display user pool balance per each token

---

src/components/AdminKyc/index.tsx
src/state/admin/actions.ts

- Add risk rating column for KYC dashboard
-
-
1. Jira ticket: [IXSPD1-2661]
2. Documents:
[IXSPD1-2661]: https://investax.atlassian.net/browse/IXSPD1-2661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2661] Add risk rating column for KYC dashboard

---

src/pages/DexV2/Pool/components/CreateActions.tsx

- temporary allowance max
-
-
2. Documents:

fix: temporary allowance max

---

src/hooks/dex-v2/useTransactions.tsx
src/pages/DexV2/Pool/Create/index.tsx
src/pages/DexV2/Pool/Staking/hooks/useStakePreview.ts
src/pages/DexV2/Pool/Withdraw/components/WithdrawActions.tsx
src/pages/DexV2/Pool/Withdraw/components/WithdrawForm.tsx
src/pages/DexV2/Pool/Withdraw/components/WithdrawPreviewModal.tsx
src/pages/DexV2/Pool/Withdraw/components/WithdrawSummary.tsx
src/pages/DexV2/Vote/components/SelectLockToVote/VoteModal.tsx
src/pages/DexV2/common/ConfirmationIndicator.tsx
src/pages/DexV2/common/Tooltip.tsx
src/state/dexV2/pool/useExitPool.ts

- Adjust the message on toasts
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2493
2. Documents:

IXSPD1-2493 Adjust the message on toasts

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx

- filter out pools have no user involved
-
-
1. Jira ticket: [IXSPD1-2653]
2. Documents:
[IXSPD1-2653]: https://investax.atlassian.net/browse/IXSPD1-2653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2653] filter out pools have no user involved

---

.env.staging
.env.staging-client-demo

Change wrong domain in env files

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx

- hotfix earnedTradingFee.some is not function if it's undefined
-
-
2. Documents:

hotfix: earnedTradingFee.some is not function if it's undefined

---

src/pages/DexV2/common/ConfirmationIndicator.tsx

- Open explore link in new tab
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2494
2. Documents:

IXSPD1-2494 Open explore link in new tab

---

src/pages/DexV2/Pool/List/PoolList.tsx

- add pagination for pool list
-
-
2. Documents:

fix: add pagination for pool list

---

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx
src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts
src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts
src/components/LaunchpadIssuance/IssuanceForm/shared/fields/MultipleDropdownField.tsx

- Add Restricted Jurisdictions section to Issuance Information form
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2583
2. Documents:

IXSPD1-2583 Add Restricted Jurisdictions section to Issuance Information form

---

src/assets/launchpad/svg/earth.svg
src/components/Launchpad/UnsupportedCountryPopup/index.tsx
src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx
src/state/issuance/types.ts
src/state/kyc/actions.ts
src/state/launchpad/hooks.ts
src/state/launchpad/types.ts

- show unsupported country popup on invest button click
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2584
2. Documents:

Ixspd1-2584 fe show unsupported country popup on invest button click

---

src/components/KycReviewModal/IndividualFormV2.tsx
src/components/KycReviewModal/InternalNotes.tsx
src/state/admin/actions.ts

- Add Notes section for all users in KYC section
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2585
2. Documents:

Ixspd1-2585 fe add notes section for all users in kyc section

---

src/components/AdminKyc/index.tsx
src/components/AdminKycExportCSVModal/index.tsx
src/components/AdminKycExportCSVModal/styled.ts
src/components/AdminKycFilters/index.tsx
src/components/Search/index.tsx
src/services/apiUrls.ts
src/state/admin/hooks.ts
src/state/issuance/hooks.ts
src/state/kyc/actions.ts
src/state/kyc/hooks.ts
src/state/kyc/reducer.ts
src/utils/saveCsvFile.ts

- implement UI for CSV Export on the KYC Dashboard
-
-
1. Jira ticket: [IXSPD1-2587]
2. Documents:
[IXSPD1-2587]: https://investax.atlassian.net/browse/IXSPD1-2587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2587] implement UI for CSV Export on the KYC Dashboard

---

src/pages/DexV2/Lock/components/LockContent.tsx

- disable Lock button once locked
-
-
1. Jira ticket: [IXSPD1-2668]
2. Documents:
[IXSPD1-2668]: https://investax.atlassian.net/browse/IXSPD1-2668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2668] disable Lock button once locked

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx

- format token weight digits to avoid title is overflow
-
-
1. Jira ticket: [IXSPD1-2665]
2. Documents:
[IXSPD1-2665]: https://investax.atlassian.net/browse/IXSPD1-2665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2665] format token weight digits to avoid title is overflow

---

src/components/KycReviewModal/IndividualFormV2.tsx

- UI bugs on kyc review modal
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2676
2. Documents:

Ixspd1-2676 fe UI bugs on kyc review modal

---

src/components/KycLightDocPreviewModal/index.tsx

- Cannot view Additional Document files on Launchpad deal
-
-
1. Jira ticket: [IXSPD1-2671]
2. Documents:
[IXSPD1-2671]: https://investax.atlassian.net/browse/IXSPD1-2671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2671] Cannot view Additional Document files

---

src/pages/DexV2/Swap/components/ActionSteps.tsx
src/pages/DexV2/Swap/components/SwapCard.tsx
src/pages/DexV2/Swap/components/SwapPreviewModal.tsx
src/state/dexV2/swap/useSor.ts
src/state/dexV2/swap/useSwapping.ts

[Draft] - Improve approval swap

---

package.json
src/components/DocumentViewer/index.tsx
src/components/KycLightDocPreviewModal/index.tsx
src/components/LBP/PublicDetails/DocumentSec.tsx
yarn.lock

- improve document viewer
- migrate @cyntler/react-doc-viewer to **react-pdf**
- I chosen the react-pdf because it's more popular (>M downloads/week) and the minimized size is less than @cyntler/react-doc-viewer
1. Jira ticket: [IXSPD1-2436]
2. Documents:
[IXSPD1-2436]: https://investax.atlassian.net/browse/IXSPD1-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2436] improve document viewer

---

.env.staging

- update API url for staging
-
-
2. Documents:

fix: update API url for staging

---

src/components/AdminKycExportCSVModal/index.tsx
src/state/kyc/hooks.ts

- Add Click Feedback Effect for “Export CSV” Button
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2686
2. Documents:

IXSPD1-2686 Add Click Feedback Effect for “Export CSV” Button

---

src/pages/DexV2/common/forms/AppSlippageForm.tsx

- Dex - Cannot input decimal number into Slippage
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2495
2. Documents:

IXSPD1-2495 Dex - Cannot input decimal number into Slippage

---

src/assets/images/list.svg
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/EmptyList.tsx
src/pages/DexV2/Dashboard/components/LockRewards.tsx
src/pages/DexV2/Dashboard/components/VotingRewards.tsx

- update empty section for dashboard
-
-
1. Jira ticket: [IXSPD1-2664]
2. Documents:
[IXSPD1-2664]: https://investax.atlassian.net/browse/IXSPD1-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2664] update empty section for dashboard

---

src/pages/DexV2/Swap/components/SwapCard.tsx

Add loading fetch allowance

---

amplify.yml

Updated amplify.yaml

---

src/pages/DexV2/Vote/components/SelectLockToVote/PoolWeightInput.tsx
src/pages/DexV2/Vote/components/SelectLockToVote/SelectPoolModal/index.tsx
src/pages/DexV2/Vote/components/SelectLockToVote/VoteModal.tsx
src/state/dexV2/vote/index.ts
src/state/dexV2/vote/useVote.ts

-  vote UI bugs on vote modal
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2642
2. Documents:

Ixspd1-2642 fe vote UI bugs on vote modal

---

amplify.yml

Update amplify config

---

src/pages/DexV2/Pool/Create/index.tsx
src/pages/DexV2/Pool/components/TokenPrices.tsx
src/pages/DexV2/Pool/components/VerticleSteps.tsx
src/pages/DexV2/Swap/components/SwapDetails.tsx

-  Dex - Max slippage and max fee are missing value
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2463, https://investax.atlassian.net/browse/IXSPD1-2696
2. Documents:

Ixspd1-2463 fe dex max slippage and max fee are missing value

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityCard.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx
src/pages/DexV2/Dashboard/graphql/dashboard.ts
src/pages/DexV2/Dashboard/hooks/useLiquidityPool.ts
src/pages/DexV2/Pool/Staking/ActionSteps.tsx
src/pages/DexV2/Pool/Staking/StakePreview.tsx
src/pages/DexV2/Pool/Staking/StakePreviewModal.tsx
src/pages/DexV2/Pool/Staking/hooks/useStakePreview.ts
src/services/balancer/contracts/voter.ts
src/state/dexV2/poolStaking/usePoolStaking.ts

- using pools data with balancer implementation because it's include some necessary fields, such as: lastestUSDPrice.
- break the DepositedStakedLiquidityCard into smaller components
- change type of gauge variable to string (instead of Address)
2. Documents:

fix: refactor pool list by balancer implementation

---

src/pages/DexV2/Vote/components/VoteHistoryRecords.tsx

- Vote - Fix Vote history record weight
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2692
2. Documents:

IXSPD1-2692 Vote - Fix Vote history record weight

---

src/pages/DexV2/Lock/components/LockContent.tsx

- user must go through two steps allow and lock
-
-
1. Jira ticket: [IXSPD1-2681]
2. Documents:
[IXSPD1-2681]: https://investax.atlassian.net/browse/IXSPD1-2681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2681] user must go through two steps allow and lock

---

src/pages/DexV2/Pool/Create/components/TokenInput.tsx

- Pool - Add max buttons to the token fields at Set initial Liquidity screen
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2629
2. Documents:

Ixspd1-2629 fe pool add max buttons to the token fields at set initial liquidity screen

---

src/pages/DexV2/Pool/components/HorizSteps.tsx

- Update tooltips in Liquidity Pools creating screen
-
-
1. Jira ticket: [IXSPD1-2651]
2. Documents:
[IXSPD1-2651]: https://investax.atlassian.net/browse/IXSPD1-2651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2651] Update tooltips in Liquidity Pools creating screen

---

src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/components/AddLiquidityPreview/components/AddLiquidityActions.tsx
src/pages/DexV2/Pool/Create/components/Steps/PreviewPool.tsx
src/pages/DexV2/Pool/Withdraw/components/WithdrawActions.tsx
src/pages/DexV2/Pool/components/ActionSteps.tsx
src/pages/DexV2/Pool/components/CreateActions.tsx
src/pages/DexV2/common/ConfirmationIndicator.tsx

- Add button return to pool page after adding liquidity and creating pool
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2702
2. Documents:

IXSPD1-2702 Add button return to pool page after adding liquidity and creating pool

---

package.json
yarn.lock

- build issue with viem
-
-
2. Documents:

hotfix: build issue with viem

---

src/pages/DexV2/Vote/components/SelectLockToVote/SelectPoolModal/index.tsx
src/pages/DexV2/common/modals/SelectTokenModal/index.tsx

- Lock background scroll when Dialog is open
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2654
2. Documents:

Ixspd1-2654 fe lock background scroll when dialog is open

---

src/lib/utils/validations.ts
src/pages/DexV2/Pool/Create/components/TokenPriceInput.tsx
src/pages/DexV2/Pool/Create/components/UnknownTokenPriceModal.tsx

- Pool - Add input validation for Token Price popup
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2699
2. Documents:

Ixspd1-2699 fe pool add input validation for token price popup

---

src/abis/rewardsDistributorABI.json
src/hooks/dex-v2/useEmissionApr.ts
src/lib/utils/index.ts
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityCard.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx

- implement APR on IXS emission
-
-
1. Jira ticket: [IXSPD1-2690]
2. Documents:
[IXSPD1-2690]: https://investax.atlassian.net/browse/IXSPD1-2690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2690] implement APR on IXS emission

---

src/hooks/dex-v2/pools/useGauges.ts
src/hooks/dex-v2/queries/useGaugesQuery.ts
src/pages/DexV2/Pool/List/PoolList.tsx
src/services/balancer/gauges/entities/gauges/gauges.entity.ts
src/services/balancer/gauges/entities/gauges/query.ts
src/services/balancer/gauges/gauges-subgraph.client.ts
src/services/balancer/gauges/gauges-subgraph.service.ts
src/services/balancer/gauges/types.ts

- add useGauges function and obtain data from subgraph
-
-
2. Documents:

feat: add useGauges function and obtain data from subgraph

---

src/constants/dexV2/queryKeys.ts
src/hooks/dex-v2/queries/usePoolDayDatasQuery.ts
src/services/balancer/poolDayDatas/entities/gauges/poolDayDatas.entity.ts
src/services/balancer/poolDayDatas/entities/gauges/query.ts
src/services/balancer/poolDayDatas/poolDayDatas.client.ts
src/services/balancer/poolDayDatas/poolDayDatas.service.ts
src/services/balancer/poolDayDatas/types.ts

- add usePoolDayDatas function
-
-
2. Documents:

feat: add usePoolDayDatas function

---

src/pages/DexV2/Pool/Create/components/TokenPriceInput.tsx
src/pages/DexV2/Vote/components/SelectLockToVote/LockSelect.tsx
src/pages/DexV2/common/modals/SelectTokenModal/index.tsx

- Vote - Add User Guidance to Create Lock from Voting Page
- Selecting from Recently Used Tokens Causes Duplicate Token Selection
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2697, https://investax.atlassian.net/browse/IXSPD1-2716
2. Documents:

Fix bug Ixspd1-2697, IXSPD1-2716

---

src/hooks/dex-v2/useEmissionApr.ts
src/hooks/dex-v2/useTradingFeeApr.ts
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx
src/pages/DexV2/Pool/List/PoolList.tsx

- Display APR on the pool table
-
-
1. Jira ticket: [IXSPD1-2504]
2. Documents:
[IXSPD1-2504]: https://investax.atlassian.net/browse/IXSPD1-2504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2504] Display APR on the pool table

---

src/hooks/dex-v2/queries/usePoolSnapshotsQuery.ts
src/pages/DexV2/Pool/Detail/components/PoolCharts.tsx
src/pages/DexV2/Pool/Detail/index.tsx

- integrate data for pool chart
-
-
1. Jira ticket: [IXSPD1-2713]
2. Documents:
[IXSPD1-2713]: https://investax.atlassian.net/browse/IXSPD1-2713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2713] integrate data for pool chart

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityCard.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx
src/pages/DexV2/Dashboard/components/VotingRewards.tsx
src/pages/DexV2/Dashboard/hooks/useLiquidityPool.ts

- get gauge address from useGauges func
- fix the user LP balance and LP supply
- fix the Claim Voting reward function
1. Jira ticket: [IXSPD1-2675]
2. Documents:
[IXSPD1-2675]: https://investax.atlassian.net/browse/IXSPD1-2675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2675] get gauge address from useGauges func

---

src/lib/config/base-sepolia/index.ts
src/lib/utils/index.ts
src/services/balancer/subgraph/entities/pools/index.ts
src/services/balancer/subgraph/subgraph-fallback.service.ts

- Handle fallback subgraph
-
-
2. Documents:

Handle fallback subgraph

---

src/pages/DexV2/Pool/Detail/components/TokenBreakdown.tsx

- Pool - Value displays NaN after creating new pool
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2720
2. Documents:

Ixspd1-2720 fe pool value displays na n after creating new pool

---

src/pages/DexV2/Lock/Detail/components/LockDetailContent.tsx

- increase lock separates steps
-
-
1. Jira ticket: [IXSPD1-2712]
2. Documents:
[IXSPD1-2712]: https://investax.atlassian.net/browse/IXSPD1-2712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2712] increase lock separates steps

---

src/pages/DexV2/Dashboard/hooks/useLiquidityPool.ts
src/pages/DexV2/Pool/Staking/hooks/useStakePreview.ts
src/state/dexV2/poolStaking/usePoolStaking.ts

- update dashboard after staking
-
-
1. Jira ticket: [IXSPD1-2519]
2. Documents:
[IXSPD1-2519]: https://investax.atlassian.net/browse/IXSPD1-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2519] update dashboard after staking

---

src/pages/DexV2/Vote/components/VoteHistoryRecords.tsx

- Vote History Records - only show 3 records
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2710
2. Documents:

IXSPD1-2710 Vote History Records - only show 3 records

---

src/lib/config/base-sepolia/index.ts

- subgraph url endpoint
-
-
2. Documents:

fix: subgraph url endpoint

---

src/pages/DexV2/Pool/List/PoolList.tsx
src/types/TokenList.ts

- display real pool type data in pool list
-
-
1. Jira ticket: [IXSPD1-2715]
2. Documents:
[IXSPD1-2715]: https://investax.atlassian.net/browse/IXSPD1-2715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2715] display real pool type data in pool list

---

src/pages/DexV2/Lock/components/LockContent.tsx

- handle the button label when confirming on wallet
1. Jira ticket: [IXSPD1-2681]
2. Documents:
[IXSPD1-2681]: https://investax.atlassian.net/browse/IXSPD1-2681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2681] handle the button label when confirming on wallet

---

src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/index.tsx

- Add Liquidity - Input are disappeared when user type more than 2 numbers
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2728
2. Documents:

Ixspd1-2728 fe add liquidity input are disappeared when user type more than 2 numbers

---

src/pages/DexV2/common/Asset.tsx

- Token Logo Appears Blurry or Low-Resolution
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2714
2. Documents:

Ixspd1-2714 fe swap token logo appears blurry or low resolution

---

src/pages/DexV2/Dashboard/components/ClaimVotingRewardButton.tsx
src/pages/DexV2/Dashboard/components/VotingRewards.tsx
src/pages/DexV2/Dashboard/components/types.ts

- disable claim voting reward button when emission = 0
-
-
1. Jira ticket: [IXSPD1-2707]
2. Documents:
[IXSPD1-2707]: https://investax.atlassian.net/browse/IXSPD1-2707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2707] disable claim voting reward button when emission = 0

---

src/hooks/dex-v2/queries/useVoteHistoriesQuery.ts
src/pages/DexV2/Vote/components/SelectLockToVote/index.tsx
src/pages/DexV2/Vote/index.tsx

- Vote history does not update automatically after user votes
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2738
2. Documents:

Ixspd1-2738 fe vote vote history does not update automatically after user votes

---

src/hooks/dex-v2/useTradingFeeApr.ts
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityCard.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityRow.tsx
src/pages/DexV2/Pool/List/PoolList.tsx

- update APR on dashboard page and pool page
-
-
1. Jira ticket: [IXSPD1-2737]
2. Documents:
[IXSPD1-2737]: https://investax.atlassian.net/browse/IXSPD1-2737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2737] update APR on dashboard page and pool page

---

src/pages/App.tsx
src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/index.tsx
src/pages/DexV2/Swap/components/SwapCard.tsx
src/pages/DexV2/common/Layout.tsx

- Dex - Implement the screens when user has not connected wallet
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2533
2. Documents:

Ixspd1-2533 fe dex implement the screens when user has not connected wallet

---

src/walletConnectConfig.json

Rm amplify v2

---

src/lib/utils/poolApr.ts
src/pages/DexV2/Pool/Detail/components/PoolStatCards.tsx
src/pages/DexV2/Pool/Detail/index.tsx
src/pages/DexV2/Pool/List/PoolList.tsx
src/pages/DexV2/Pool/Staking/StakingCard.tsx

- show apr in pool detail
-
-
1. Jira ticket: [IXSPD1-2730]
2. Documents:
[IXSPD1-2730]: https://investax.atlassian.net/browse/IXSPD1-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2730] show apr in pool detail

---

src/hooks/dex-v2/queries/useTokenPricesQuery.ts
src/services/apiUrls.ts
src/state/dexV2/tokens/hooks/useTokens.ts
src/state/dexV2/tokens/index.ts
src/types/TokenList.ts

- fetch token price from API
-
-
1. Jira ticket: [IXSPD1-2689]
2. Documents:
[IXSPD1-2689]: https://investax.atlassian.net/browse/IXSPD1-2689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2689] fetch token price from API

---

src/hooks/dex-v2/pools/usePools.ts
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/LockRewards.tsx
src/pages/DexV2/Dashboard/components/VotingRewards.tsx
src/pages/DexV2/Dashboard/hooks/useLiquidityPool.ts

- handle loading on dashboard
-
-
2. Documents:

fix: handle loading on dashboard

---

src/pages/DexV2/Pool/Detail/components/PoolCompositionCard.tsx
src/pages/DexV2/Pool/Detail/components/TokenBreakdown.tsx
src/pages/DexV2/common/modals/SelectTokenModal/index.tsx

- Pool - Pool composition displays in correct value
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2719
2. Documents:

Ixspd1-2719 fe pool pool composition displays in correct value

---

src/pages/DexV2/Pool/List/PoolList.tsx
src/pages/DexV2/Pool/List/index.tsx

- hide pool type filter bar
-
-
1. Jira ticket: [IXSPD1-2606]
2. Documents:
[IXSPD1-2606]: https://investax.atlassian.net/browse/IXSPD1-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2606] hide pool type filter bar

---

src/components/Header/HeaderLinks.tsx
src/components/Mobile-Menu/Menu.tsx

- fix route swap
-
-
2. Documents:

Fix route swap

---

src/pages/DexV2/Lock/LockProvider.tsx
src/pages/DexV2/Lock/components/LockContent.tsx

- handle lock processing by txListener
-
-
1. Jira ticket: [IXSPD1-2681](https://investax.atlassian.net/browse/IXSPD1-2681)
2. Documents:
[IXSPD1-2681]: https://investax.atlassian.net/browse/IXSPD1-2681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2681] handle lock processing by txListener

---

src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/components/AddLiquidityPreview/components/BalDataList.tsx
src/pages/DexV2/common/modals/index.tsx

… 2 tokens
- Withdraw pool - Cannot scroll to view summary when pool has more than 2 tokens
-
-
2. Documents:

Ixspd1-2746 fe withdraw pool cannot scroll to view summary when pool has more than 2 tokens

---

src/pages/DexV2/Pool/Withdraw/components/WithdrawPreviewModal.tsx
src/pages/DexV2/Pool/Withdraw/components/WithdrawTabs.tsx
src/pages/DexV2/Pool/Withdraw/index.tsx
src/state/dexV2/pool/useExitPool.ts

- Update UI withdraw modal
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2748
2. Documents:

Ixspd1-2748 fe update UI withdraw modal

---

src/walletConnectConfig.json

Added wallet connect for pre-prod

---

src/pages/DexV2/Pool/AddLiquidity/AddLiquidityForm/index.tsx

- Add Liquidity – Token amount not auto-optimized when user clicks Max on any field
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2745
2. Documents:

Ixspd1-2745 fe add liquidity token amount not auto optimized when user clicks max on any field

---

src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts
src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DropdownField.tsx
src/state/launchpad/types.ts

- integrate with redbelly network
-
-
1. Jira ticket: [IXSPD1-2460]
2. Documents:
[IXSPD1-2460]: https://investax.atlassian.net/browse/IXSPD1-2460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2460] integrate with redbelly network

---

src/pages/Earn/ProductDetail.tsx
src/pages/Earn/components/tabs/Claim/ClaimPreview.tsx
src/pages/Earn/components/tabs/Claim/index.tsx
src/pages/Earn/components/tabs/Deposit/DepositPreview.tsx
src/pages/Earn/components/tabs/Deposit/index.tsx
src/pages/Earn/components/tabs/SharedStyles.ts
src/pages/Earn/components/tabs/WithdrawRequest/WithdrawPreview.tsx
src/pages/Earn/components/tabs/WithdrawRequest/index.tsx
yarn.lock

-  Earn - Update UI for Preview screens
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2764
2. Documents:

Earn - Update UI for Preview screens

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityCard.tsx
src/pages/DexV2/Pool/Staking/hooks/useStakePreview.ts
src/state/dexV2/tokens/hooks/useTokens.ts
src/state/dexV2/tokens/index.ts

- handle fetch allowance with set of spenders
-
-
1. Jira ticket: [IXSPD1-2649]
2. Documents:
[IXSPD1-2649]: https://investax.atlassian.net/browse/IXSPD1-2649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2649] handle fetch allowance with set of spenders

---

src/pages/DexV2/Dashboard/components/LockRewards.tsx

- add voting power to Lock list
-
-
1. Jira ticket: [IXSPD1-2724]
2. Documents:
[IXSPD1-2724]: https://investax.atlassian.net/browse/IXSPD1-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IXSPD1-2724] add voting power to Lock list

---

src/pages/Earn/ProductDetail.tsx
src/pages/Earn/components/tabs/Claim/ClaimPreview.tsx
src/pages/Earn/components/tabs/Claim/SuccessPopup.tsx
src/pages/Earn/components/tabs/Claim/index.tsx
src/pages/Earn/components/tabs/Deposit/DepositPreview.tsx
src/pages/Earn/components/tabs/Deposit/index.tsx
src/pages/Earn/components/tabs/WithdrawRequest/WithdrawPreview.tsx
src/pages/Earn/components/tabs/WithdrawRequest/index.tsx

- Fix some bugs earn
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2755
2. Documents:

IXSPD1-2755 Fix some bugs earn

---

src/components/Header/index.tsx
src/pages/Earn/components/tabs/Claim/index.tsx
src/pages/Earn/components/tabs/Deposit/DepositPreview.tsx
src/pages/Earn/components/tabs/Deposit/index.tsx
src/pages/Earn/components/tabs/WithdrawRequest/WithdrawPreview.tsx

- Fix show success for whitelist success
- Add button connect wallet in header mobile
- Custom Ui claim
2. Documents:

Fix show success for whitelist success

---

src/pages/App.tsx

- Turn on maintain mode
-
-
2. Documents:

Turn on maintain mode

---

src/components/Header/index.tsx
src/pages/Earn/components/tabs/Deposit/DepositPreview.tsx
src/pages/Earn/components/tabs/Deposit/index.tsx
src/pages/Earn/components/tabs/WithdrawRequest/index.tsx

- Fix some bugs UI
-
-
2. Documents:

Fix some bugs UI

---

src/pages/App.tsx

Reverts IXS-Finance/interface#3380

Revert "Turn on maintain mode"

---

src/pages/Earn/ProductDetail.tsx
src/pages/Earn/components/tabs/Deposit/index.tsx
src/pages/Earn/products.ts

- Update config for earn products
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2767
2. Documents:

IXSPD1-2767 Update config for earn products

---

src/pages/Earn/products.ts

Adjust config to support stablecoin on multi chains

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityCard.tsx
src/pages/DexV2/Pool/Staking/StakePreview.tsx
src/pages/DexV2/Pool/Staking/StakePreviewModal.tsx
src/pages/DexV2/Pool/Staking/StakingCard.tsx

- show emission apr on staking preview
-
-
2. Documents:

feat: show emission apr on staking preview

---

src/pages/Earn/products.ts

Fix earn contract address on avalanche

---

src/pages/Earn/ProductDetail.tsx
src/pages/Earn/components/EarnProductCard.tsx

- Fix some small errors
-
-
2. Documents:

Fix some small errors

---

src/pages/Earn/ProductDetail.tsx
src/pages/Earn/components/tabs/Deposit/index.tsx
src/pages/Earn/components/tabs/WithdrawRequest/index.tsx
src/pages/Earn/products.ts

- Update min max for earn
-
-
2. Documents:

Update min max for earn

---

src/pages/Earn/products.ts

Udpate addresses of earn products

---

package.json
yarn.lock

Upgrade balancer sdk

---

src/pages/Earn/ProductDetail.tsx
src/pages/Earn/abis/OpenTrade.json
src/pages/Earn/hooks/useMulticall.tsx

- Get interest rate from smart contract
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2775
2. Documents:

Ixspd1-2776 fe get interest rate from smart contract

---

src/pages/Earn/ProductDetail.tsx
src/pages/Earn/hooks/useMulticall.tsx
src/pages/Earn/products.ts

- Add links to Learn more for both Treasury and High Yield products
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2778
2. Documents:

Ixspd1-2778 fe add links to learn more for both treasury and high yield products

---

src/pages/KYC/CountriesBlockAlert.tsx

- Remove flags of blocked countries
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2772
2. Documents:

Remove flags of blocked countries

---

src/pages/Earn/ProductDetail.tsx
src/pages/Earn/components/tabs/Claim/SuccessPopup.tsx
src/pages/Earn/components/tabs/Claim/index.tsx
src/pages/Earn/components/tabs/WithdrawRequest/SuccessPopup.tsx
src/pages/Earn/components/tabs/WithdrawRequest/index.tsx
src/utils/getExplorerLink.ts

- Scan link on Claim successful popup is not correct
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2783
2. Documents:

Ixspd1-2783 fe scan link on claim successful popup is not correct

---

src/constants/subgraph.ts
src/pages/Earn/ProductDetail.tsx

Update subgraph url for avax fuji

---

src/pages/Earn/products.ts

- Change minimum Deposit and Withdraw on HYCB to 1 USDC
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2784
2. Documents:

Ixspd1-2784 fe change minimum deposit and withdraw on hycb to 1 usdc

---

src/pages/Earn/components/tabs/Claim/SuccessPopup.tsx
src/pages/Earn/components/tabs/Deposit/SuccessPopup.tsx
src/pages/Earn/components/tabs/Deposit/index.tsx
src/pages/Earn/components/tabs/WithdrawRequest/SuccessPopup.tsx
src/pages/Earn/components/tabs/WithdrawRequest/index.tsx

- Handle open explore link
-
-
2. Documents:

Handle open explore link

---

src/hooks/useWrapCallback.ts
src/pages/Swap/SwapButtons.tsx

- disable wrap button on processing
-
-
2. Documents:

fix: disable wrap button on processing

---

src/pages/KYC/CountriesBlockAlert.tsx

- Update the verbiage on Individual KYC page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2772
2. Documents:

IXSPD1-2772 Update the verbiage on Individual KYC page

---

src/pages/Earn/products.ts

- Earn - Change APR on the HYCB card to 6.45%
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2789
2. Documents:

IXSPD1-2789 Update apy from 7 to 6.45

---

src/components/Launchpad/KYCPrompt/index.tsx

- Change title of kyc promt
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2792
2. Documents:

IXSPD1-2792 Change title of kyc promt

---

src/components/Header/HeaderLinks.tsx
src/components/Header/index.tsx
src/pages/Launchpad/Header.tsx

- Fix UI bug on Logo
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2793
2. Documents:

Ixspd1-2793 fe fix UI bug on logo

---

src/pages/KYC/CountriesBlockAlert.tsx

Update content alert block countries

---

src/pages/DexV2/Dashboard/components/DepositedStakedLiquidity.tsx
src/pages/DexV2/Dashboard/components/DepositedStakedLiquidityCard.tsx
src/pages/DexV2/Dashboard/components/constants.ts

- filter out pools with negligible activity
-
-
1. Jira ticket: [IXSPD1-2707]
2. Documents:
[IXSPD1-2707]: https://investax.atlassian.net/browse/IXSPD1-2707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IXSPD1-2707] filter out pools with negligible activity

---

src/constants/chains.ts

- RedBelly - Clicking the Explorer button always opens Etherscan lịnk
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2803
2. Documents:

Ixspd1-2803 fe red belly clicking the explorer button always opens etherscan lịnk

---

src/pages/KYC/SecondaryContactOption.tsx

- KYC v2 : Timer still runs even IXS shows error 'Email already existed'
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1549
2. Documents:

IXSPD1-1549 KYC v2 : Timer still runs even IXS shows error Email already existed

---

src/pages/App.tsx
src/pages/KYC/IndividualKycFormV2.tsx
src/state/kyc/hooks.ts

- Refetch KYC status every 30 seconds.
- When the user changes the account, refetch the data and the KYC status
-
1. Jira ticket:  https://investax.atlassian.net/browse/IXSPD1-2343
2. Documents:

Ixspd1-2343 kyc status is not updated until user refreshes the page

---

src/pages/KYC/index.tsx

- Hide loading in kyc page 
-
-
2. Documents:

Hide loading in kyc page 

---

src/components/PhoneInput/index.tsx
src/components/Select/index.tsx
src/pages/KYC/CorporateKycForm.tsx
src/pages/KYC/IndividualKycFormV2.tsx
src/pages/KYC/schema.ts
src/state/kyc/hooks.ts

- Corporate KYC UI bugs
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2512
2. Documents:

Ixspd1-2512 fe corporate kyc UI bugs

---

src/pages/KYC/CorporateKycForm.tsx
src/pages/KYC/schema.ts
src/pages/KYC/utils.ts

- Corporate KYC UI bugs
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2512
2. Documents:

Ixspd1-2512 fe corporate kyc UI bugs 

---

src/pages/LaunchpadOffer/index.tsx
src/pages/PoolFinder/index.tsx

-  Header is duplicated when opening Import Pool
-
-
2. Documents:

Ixspd1-2820 fe prod header is duplicated when opening import pool

---

src/pages/KYC/EmailVerifyModal.tsx
src/pages/KYC/ResendEmailModal.tsx

- KYC Corporate - The page is reloaded when user submit the verification code
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1065
2. Documents:

Ixspd1-1065 fe kyc corporate the page is reloaded when user submit the verification code

---

src/pages/Earn/ProductDetail/components/AnnualPercentageRate.tsx
src/pages/Earn/ProductDetail/index.tsx

- Earn - APR shows 0% if user clear local storage
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2825
2. Documents:

Ixspd1-2825 fe earn apr shows 0 if user clear local storage

---

src/assets/images/icons/external-link.svg
src/pages/Earn/ProductDetail/index.tsx

- Earn - Update the Transactions table on mobile screen
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2828
2. Documents:

Ixspd1-2828 fe earn update the transactions table on mobile screen

---

src/pages/AddLiquidityV2/redirects.tsx

…ith unsupported chain
- Add Liquidity - Display Feature not supported page if users connect with unsupported chain
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2388
2. Documents:

Ixspd1-2388 fe add liquidity display feature not supported page if users connect with unsupported chain

---

src/components/KycReviewModal/InternalNotes.tsx

- Admin - Opening and closing KYC view triggers API call to save internal note, marking KYC as recently updated
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2834
2. Documents:

Ixspd1-2834 fe admin opening and closing kyc view triggers api call to save internal note marking kyc as recently updated

---

src/components/KycReviewModal/InternalNotes.tsx
src/pages/KYC/index.tsx

- Handle save admin kyc note when detect change
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2834
2. Documents:

IXSPD1-2834 Handle save admin kyc note when detect change

---

src/components/Web3Provider/constants.ts
src/hooks/useWeb3React.ts

- Remove chain.Mainnet
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2801
2. Documents:

Remove chain.Mainnet

---

package.json
yarn.lock

- Update new version of rainbowkit
-
-
2. Documents:

Update new version of rainbowkit

---

src/components/Web3Provider/index.tsx
src/components/Web3Provider/wagmi.ts

- WalletConnect,MetaMask - Refreshing the page causes wallet to disconnect
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2856
2. Documents:

IXSPD1-2856 WalletConnect,MetaMask - Refreshing the page causes wallet to disconnect

---

src/state/wallet/hooks.ts

- Swap - Loading the token balance takes a long time when connecting by MetaMask
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2862
2. Documents:

Ixspd1-2862 prod swap loading the token balance takes a long time when connecting by meta mask

---

src/state/kyc/hooks.ts
src/state/stake/contstants.ts
src/utils/verifySwap.ts

-  Error occurs when swapping tokens WIXS-USDC
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2861
2. Documents:

Ixspd1-2861 prod error occurs when swapping tokens wixs usdc

---

src/services/apiService.ts

- Sign-in popup appears even after session is cleared upon browser close
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2865
2. Documents:

Ixspd1-2865 fe sign in popup appears even after session is cleared upon browser close

---

src/state/multicall/hooks.ts

- Fix loading forever find swap trade
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2864
2. Documents:

IXSPD1-2864 Fix loading forever find swap trade

---

src/pages/KYC/KYCProgressBar.tsx

- Individual KYC - Remove Reason of changes requested field in the form V2
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-2868
2. Documents:

Ixspd1-2868 fe individual kyc remove reason of changes requested field in the form v2
