IXS-Finance/interface

src/components/Mobile-Menu/Menu.tsx
- Added NFT-items to navigation menu
=> Added NFT-items to navigation menu

src/components/Header/HeaderLinks.tsx
- Fixed issue with My Collections link being highlighted
when creating new collection
=> Fixed issue with My Collections link being highlighted when creating new collection

src/pages/NFTCollection/NFTPreview.tsx
- Made NFT cards of equal size
- Centered loader within a card
=> Made NFT cards of equal size; Centered loader within a card

src/pages/NFTCollection/index.tsx
- Fixed issue with NFTs aligning into a single row
=> Fixed issue with NFTs aligning into a single row

src/pages/NFTCollection/NFTPreview.tsx
=> Changed NFT card layout

src/components/Loader/LoaderThin.tsx, src/pages/NFTCollections/index.tsx
- Fixed My Collections page twitching cause by LoaderThin
- Added width limit for the LoaderThin
=> Fixed My Collections page twitching cause by LoaderThin; Added width limit for the LoaderThin

src/components/CollectionForm/index.tsx, src/components/Upload/index.tsx
- Added images upload from backend
=> Added images upload from backend

src/pages/NFTAsset/index.tsx
=> Fixed errors on NFT page

src/components/LoaderHover/index.tsx, src/pages/CreateCollection/index.tsx, src/pages/UpdateCollection/index.tsx, src/state/nft/hooks.ts
- Fixed collection update error
=> Fixed collection update error

src/components/CollectionForm/index.tsx, src/constants/misc.ts
- Added Update/Create collection validation
=> Added Update/Create collection validation

src/pages/CreateNFT/mocks.ts, src/pages/NFTCollections/index.tsx, src/pages/NFTCollections/styleds.tsx, src/state/nft/types.ts
=> Added collection images

src/pages/NFTCollections/index.tsx
- Change title of My Collections page to "My Collections"
=> Change title of My Collections page to "My Collections"

src/pages/NFTCollection/index.tsx
- Added back button to collection page
=> Added back button to collection page

src/pages/NFTCollection/index.tsx
- Centered collection's NFT list and title
=> Centered collection's NFT list and title

src/pages/NFTCollections/styleds.tsx
- Added hover effect on collection card
=> Added hover effect on collection card

src/pages/CreateNFT/CreateForm.tsx
- Added notification to NFT-create page
=> Added notification to NFT-create page

src/pages/CreateNFT/CreateForm.tsx, src/pages/NFTCollections/styleds.tsx
- https://app.clickup.com/t/4733323/IXS-1355
=> Create/Update Collection & NFT-items

src/pages/CreateNFT/CreateForm.tsx
- Added Update/Create NFT validation
=> Added Update/Create NFT validation

src/pages/CreateNFT/CreateForm.tsx
- https://app.clickup.com/t/4733323/IXS-1359
=> Create/Update Collection & NFT-items 

src/pages/NFTAsset/index.tsx, src/pages/NFTCollection/index.tsx, src/utils/routes.ts
- Added back button to NFT item page
=> Added back button to NFT item page

src/pages/NFTAsset/index.tsx, src/pages/NFTCollection/NFTPreview.tsx, src/state/nft/hooks.ts, src/state/nft/types.ts
=> Added preview to GLB-files

src/pages/NftImport/index.tsx
- Added network(Kovan) validation
=> Added network(Kovan) validation

src/pages/NFTAsset/index.tsx, src/pages/NFTCollection/index.tsx
- Fixed Collection/NFT-item back-btn layout
=> Fixed Collection/NFT-item back-btn layout

src/pages/NFTCollection/index.tsx
Fixed Collection/NFT-item back-btn layout
=> [IXSwap.Interface] 

src/pages/NFTCollection/NFTPreview.tsx
=> Updated NFT-cards

src/state/nft/hooks.ts, src/state/nft/types.ts
- Added chainId params to NFT-collection
=> Added chainId params to NFT-collection

src/pages/Farming/Staking/StakingTierCard.tsx
- Updated logic of staking pools
=> Updated logic of staking pools

src/pages/NFTCollections/index.tsx
- Fixed collections page after logIn
=> Fixed collections page after logIn

src/components/CollectionForm/index.tsx
- Added description validation
=> Added description validation

src/pages/NFTCollections/index.tsx
- Fixed collection banner image scaling
=> Fixed collection banner image scaling

src/components/CollectionForm/index.tsx
- Added upload only images files to create collection
=> Added upload only images files to create collection

src/pages/NFTAsset/index.tsx, src/services/apiUrls.ts, src/state/nft/hooks.ts
- Added placeholder for nft which without preview
=> Added placeholder for nft which without preview

src/pages/NFTAsset/index.tsx, src/pages/NFTCollection/index.tsx
- Fixed NFT/Collection back btn layout
=> Fixed NFT/Collection back btn layout

src/pages/CreateNFT/CreateForm.tsx
- Fixed previous creation NFT state
=> Fixed previous creation NFT state

src/components/Header/HeaderLinks.tsx, src/components/Mobile-Menu/Menu.tsx, src/pages/AppBody.tsx, src/pages/CreateCollection/index.tsx, src/pages/CreateNFT/index.tsx, src/pages/NFTAsset/index.tsx, src/pages/NFTCollection/index.tsx, src/pages/NFTCollections/index.tsx
- Added blur for NFT sections if chain is not Kovan
=> Added blur for NFT sections if chain is not Kovan

src/pages/Farming/Staking/StakingTierCard.tsx
=> Fixed staking bug

src/pages/NFTCollections/index.tsx
=> Fixed collections layout

src/components/Header/HeaderLinks.tsx, src/components/Mobile-Menu/Menu.tsx, src/constants/chains.ts
=> Updated menu header

src/pages/CreateNFT/FreezeRadio.tsx
=> Added icon to nft-freeze

src/pages/NFTCollection/index.tsx, src/pages/UpdateCollection/index.tsx, src/state/nft/hooks.ts
=> Updated NFT

src/components/CollectionForm/index.tsx
- Updated description field of NFTcollection
=> Updated description field of NFTcollection

src/components/CollectionForm/index.tsx, src/components/Slider/index.tsx, src/pages/CreateCollection/index.tsx, src/state/nft/collectionForm.actions.ts, src/state/nft/collectionForm.reducer.ts, src/state/nft/hooks.ts, src/state/nft/types.ts
- Added MaxSupply to create NFTCollection
=> Added MaxSupply to create NFTCollection

src/components/NavigationTabs/index.tsx
- Added Token listing form and Guide
=> Added Token listing form and Guide

src/components/CollectionForm/index.tsx, src/pages/CreateNFT/CreateForm.tsx
- Updated MaxSupply field in collection
- Added authrization to collection form
=> Updated MaxSupply field in collection

src/components/Header/HeaderLinks.tsx, src/components/Mobile-Menu/Menu.tsx
=> Updated farming menu

src/components/CollectionForm/index.tsx, src/pages/CreateNFT/CreateForm.tsx
- Updated NFT/Collection layouts
=> Updated NFT/Collection layouts

src/utils/verifySwap.ts
- Updated error messages in VerifySwap-script
=>  Updated error messages in VerifySwap-script

src/utils/verifySwap.ts
=> [IXSwap.Interface] - Updated mitigation-script

src/components/Vault/ChooseBrokerDealerPopup.tsx
- Updated design pass-kyc form
=> [IXSwap.Interface] - Updated design pass-kyc form

src/components/Vault/ChooseBrokerDealerPopup.tsx
- Removed unset option for KYC
=> [IXSwap.Interface] - Removed unset option for KYC

src/pages/Swap/SwapButtons.tsx, src/utils/verifySwap.ts
=> [IXSwap.Interface] - Updated ML-script

src/pages/KYC/index.tsx
- Added check up of account in KYC
=> [IXSwap.Interface] - Added check up of account in KYC

src/components/Vault/ChooseBrokerDealerPopup.tsx, src/components/Vault/enum.ts
- Added KYC status in Accreditation-Form
=> [IXSwap.Interface] - Added KYC status in Accreditation-Form

src/components/Vault/ChooseBrokerDealerPopup.tsx, src/services/apiUrls.ts, src/state/user/hooks.tsx
- Added KYC status in Accreditation-Form
- Implemented KYC accreditation API
=> [IXSwap.Interface] - Added KYC status in Accreditation-Form - Implemented KYC accreditation API

src/pages/KYC/CorporateKycForm.tsx, src/state/kyc/hooks.ts
=> [IXSwap.Interface] - Fixed KYC-corporate bugs

src/components/AdminAccreditationTable/FirstStepStatus.tsx, src/components/AdminAccreditationTable/index.tsx, src/components/AdminKyc/index.tsx, src/components/AdminSecurityCatalog/index.tsx, src/components/AdminTransactionsTable/index.tsx, src/pages/Admin/index.tsx, src/pages/App.tsx, src/state/admin/actions.ts
- Added Open button for accreditation
- Changed admin tabs to use router
=> [IXSwap.Interface] - Added Open button for accreditation - Changed admin tabs to use router

src/components/AdminAccreditationTable/FirstStepStatus.tsx, src/components/AdminAccreditationTable/index.tsx, src/components/AdminKyc/index.tsx, src/pages/Admin/index.tsx
- Added KYC modal for Accreditation page
=> [IXSwap.Interface] - Added KYC modal for Accreditation page

src/components/FilePreview/index.tsx, src/pages/KYC/common.tsx
- change default icon for added document
- change allowed format for documents
=> kyc documents fixes

src/pages/KYC/index.tsx
- remove console.log
- add year for kyc status date
- change info text for approved kyc
=> kyc status changes

src/pages/SecTokenDetails/index.tsx
Updated UI of non-tradable tokens
=> UI of non-tradable tokens

src/constants/addresses.ts, src/utils/verifySwap.ts
- Updated addresses of factory
=> [IXSwap.Interface] - Updated addresses of factory

src/constants/misc.ts, src/services/apiService.ts, src/state/kyc/hooks.ts
- Fixed flow with create of KYC (Individual/Corporate)
=> [IXSwap.Interface] - Fixed flow with create of KYC (Individual/Corporate)

src/components/AdminAccreditationTable/Search.tsx, src/components/AdminAccreditationTable/index.tsx, src/components/AdminKyc/index.tsx, src/components/AdminSecurityCatalog/TokenPopup.tsx, src/components/AdminSecurityCatalog/index.tsx, src/components/AdminTransactionsTable/index.tsx, src/pages/KYC/index.tsx, src/state/admin/actions.ts, src/state/admin/constants.ts, src/state/admin/reducer.ts
здесь еще https://app.clickup.com/t/4733323/IXS-1785
=> Add text kyc page ixs 1835

src/components/SearchModal/CurrencyList.tsx, src/components/SearchModal/CurrencySearch.tsx, src/constants/lists.ts, src/pages/Swap/AuthorizationButtons.tsx, src/pages/Swap/index.tsx, yarn.lock
=> Revert "Development"

src/components/Vault/TransactionDetails.tsx, src/components/Vault/TransactionHistoryRow.tsx, src/components/Vault/enum.ts, src/state/deposit/hooks.ts
- change logic for status color
- add redirect to trans info modal after success deposit request
=> change logic for status color and add redirect to trans info modal after success deposit request

src/components/Vault/HistoryTable.tsx, src/components/Vault/TransactionDetails.tsx, src/components/Vault/enum.ts, src/components/Vault/styleds.tsx
- add progress bar
- change icons for statuses
=> progress bar

src/components/Vault/WithdrawRequestForm.tsx, src/state/withdraw/hooks.ts
- Removed feeAddress from draft withdraw-request
=> [IXSwap.Interface] - Removed feeAddress from draft withdraw-request

src/state/swapHelper/hooks.ts
- Updated authorization via Broker-Dealer
=> [IXSwap.Interface]- Updated authorization via Broker-Dealer

src/state/swapHelper/hooks.ts, src/state/withdraw/reducer.ts
=> fix broker dealer flow

src/services/apiUrls.ts, src/state/withdraw/hooks.ts
- Updated flow of fee transaction;
=> [IXSwap.Interface] - Updated flow of fee transaction;

src/components/AdminAccreditationTable/index.tsx, src/components/AdminKyc/index.tsx, src/components/AdminTransactionsTable/index.tsx, src/components/CopyAddress/index.tsx, src/components/MultipleFilters/FilterDropdown.tsx, src/components/MultipleFilters/constants.ts, src/components/MultipleFilters/index.tsx, src/components/MultipleFilters/styleds.ts, src/components/Select/index.tsx, src/components/UsersList/RemoveTokensWarning.tsx, src/components/UsersList/RoleChangeWarning.tsx, src/components/UsersList/TokensBlock.tsx, src/components/UsersList/UpdateSummary.tsx, src/components/UsersList/UserModal.tsx, src/components/UsersList/index.tsx, src/components/UsersList/styleds.ts, src/components/UsersList/validationSchema.ts, src/components/Vault/TransactionDetails.tsx, src/pages/Admin/index.tsx, src/pages/SecTokenDetails/AddToMetamask.tsx, src/services/apiService.ts, src/services/apiUrls.ts, src/state/admin/actions.ts, src/state/admin/hooks.ts, src/state/admin/reducer.ts, src/state/user/hooks.tsx, src/theme/components.tsx, src/types/secToken.ts
- add warning popups and summary popup
- move hook for copy to copy address component
=> Admin - users list

src/components/UsersList/TokenManagerTokens.tsx, src/components/UsersList/index.tsx, src/state/admin/actions.ts
- Added payout event list to token managers on users tab
=> [IXSwap.Interface] - Added payout event list to token managers on users tab

src/components/SearchModal/CurrencyList.tsx, src/state/whitelabel/reducer.ts, src/state/whitelabel/types.ts
- Added limit to available tokens
=> [IXSwap.Interface] - Added limit to available tokens

src/pages/App.tsx, src/state/whitelabel/types.ts
- Added limit to available pages
=> [IXSwap.Interface] - Added limit to available pages

.github/workflows/integration-tests.yaml, e2e_tests/helpers/timeouts.ts, e2e_tests/page-object/connectWalletScreen.ts
Ability to run tests in parallel with handling of Metamask conflicts
=> Ability to run tests in parallel with handling of Metamask conflicts

src/components/PayoutItem/PreviewModal/Attachements.tsx, src/components/PayoutItem/PreviewModal/index.ts, src/pages/PayoutItem/InfoBlock.tsx, src/state/token-manager/types.ts
- Added preview for attachments;
=> [IXSwap.Interface] - Added preview for attachments;

src/pages/CreatePayoutEvent/index.tsx, src/state/payout/reducer.ts
- Fixed eternal spinner in create page;
=> [IXSwap.Interface] - Fixed eternal spinner in create page;

src/components/TmPayoutEvents/index.tsx, src/pages/AppRoutes.tsx, src/pages/CreatePayoutEvent/EditPayoutEvent.tsx, src/pages/CreatePayoutEvent/PayoutEventBlock.tsx, src/pages/CreatePayoutEvent/PayoutForm.tsx, src/pages/CreatePayoutEvent/mock.ts, src/pages/CreatePayoutEvent/utils.ts, src/pages/PayoutItem/PayoutHeader.tsx, src/state/payout/hooks.ts, src/utils/routes.ts
- Added edit page for Payout Events;
=> [IXSwap.Interface] - Added edit page for Payout Events;

src/pages/AddLiquidityV2/index.tsx, src/state/pool/hooks.ts
- Updated service of LiquidityPool;
=> [IXSwap.Interface] - Updated service of LiquidityPool;

src/state/swapHelper/hooks.ts
- Fixed flow of the swap-authorization;
=> [IXSwap.Interface] - Fixed flow of the swap-authorization;

src/pages/Swap/SwapButtons.tsx, src/utils/verifySwap.ts
- Fixed mitigation script;
- Enabled mitigation script;
=> [IXSwap.Interface] - Fixed mitigation script; - Enabled mitigation script;

src/pages/PayoutItem/ActionBlock/ManagerView.tsx, src/services/apiUrls.ts, src/state/payout/actions.ts, src/state/payout/hooks.ts, src/state/payout/reducer.ts
- Fixed info of the claimed events;
=> [IXSwap.Interface] - Fixed info of the claimed events;

src/pages/PayoutItem/ActionBlock/ManagerView.tsx, src/pages/PayoutItem/ActionBlock/UserView.tsx, src/pages/PayoutItem/ActionBlock/dto.ts, src/pages/PayoutItem/ActionBlock/index.tsx, src/pages/PayoutItem/PayoutItemManager.tsx, src/pages/PayoutItem/index.tsx, src/services/apiUrls.ts, src/state/payout/hooks.ts, src/state/token-manager/types.ts
- Added payout event claim back for token manager
=> [IXSwap.Interface] - Added payout event claim back for token manager

src/pages/PayoutItem/PayoutItemManager.tsx
=> [IXSwap.Interface] - Fixed details

src/pages/PayoutItem/ActionBlock/ManagerView.tsx
- Fixed issue with changing wallet on payout details page
=> [IXSwap.Interface] - Fixed issue with changing wallet on payout details page

src/hooks/useTokensList.tsx
- Fixed issue with empty filter of the sec-tokens list;
=> [IXSwap.Interface] - Fixed issue with empty filter of the sec-tokens list;

src/components/UserPayoutEvents/EmptyState.tsx
- Updated empty state of the payouts page;
=> [IXSwap.Interface] - Updated empty state of the payouts page;

src/pages/CreatePayoutEvent/PayoutEventBlock.tsx, src/pages/CreatePayoutEvent/validation.ts
- Fixed creation of the Payout-Event;
=> [IXSwap.Interface] - Fixed creation of the Payout-Event;

src/pages/CreatePayoutEvent/validation.ts
- Fixed pay-flow of the Payout-Event;
=> [IXSwap.Interface] - Fixed pay-flow of the Payout-Event;

src/pages/PayoutItem/Timeline/PayoutTimeline.tsx
- Fixed layouts of the Payout-Event;
=> [IXSwap.Interface] - Fixed layouts of the Payout-Event;

src/pages/PayoutItem/ActionBlock/UserView.tsx, src/pages/PayoutItem/ActionBlock/index.tsx, src/pages/PayoutItem/PayoutItemManager.tsx, src/pages/PayoutItem/index.tsx
- Fixed issue with wallet switch on payout details page
=> [IXSwap.Interface] - Fixed issue with wallet switch on payout details page

src/components/TmPayoutEvents/index.tsx, src/components/Tooltip/index.tsx
=> [IXSwap.Interface] - Fixed claimed info;

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx
- Fixed publish of the Payout-Events;
=> [IXSwap.Interface] - Fixed publish of the Payout-Events;

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx, src/services/apiUrls.ts, src/state/payout/hooks.ts
- Updated paid and publish of the Payout-Events;
=> [IXSwap.Interface] - Updated paid and publish of the Payout-Events;

src/pages/PayoutItem/ActionBlock/UserView.tsx, src/pages/PayoutItem/ActionBlock/index.tsx, src/pages/PayoutItem/index.tsx
- Fixed infinite swap when switching wallets on payout details page
=> [IXSwap.Interface] - Fixed infinite swap when switching wallets on payout details page

src/pages/PayoutItem/ActionBlock/ManagerView.tsx, src/pages/PayoutItem/ActionBlock/UserView.tsx, src/state/payout/hooks.ts
- Updated claim of the Payout-Events;
=> [IXSwap.Interface] - Updated claim of the Payout-Events;

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx, src/services/apiUrls.ts, src/state/payout/actions.ts, src/state/payout/hooks.ts, src/state/payout/reducer.ts
- Updated publish flow of the PayoutEvents;
=> [IXSwap.Interface] - Updated publish flow of the PayoutEvents;

src/assets/svg/trash-icon.svg, src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/KYCProgressBar.tsx, src/pages/KYC/common.tsx, src/pages/KYC/mock.ts, src/pages/KYC/schema.ts
=> [IXSwap.Interface] - Changed Individual KYC form

src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/KYCProgressBar.tsx, src/pages/KYC/schema.ts, src/pages/KYC/utils.ts, src/state/kyc/hooks.ts
=> [IXSwap.Interface] - Updated Individual KYC form

src/components/KycReviewModal/Blocks/InvestorDeclaration.tsx, src/components/KycReviewModal/Blocks/TaxDeclarations.tsx
- Updated Individual KYC review form
=> [IXSwap.Interface] - Updated Individual KYC review form

src/pages/KYC/IndividualKycForm.tsx
- Updated Individual KYC form;
=> [IXSwap.Interface] - Updated Individual KYC form;

src/components/KycReviewModal/Blocks/InvestorDeclaration.tsx, src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/KYCValidationErrors.tsx, src/pages/KYC/mock.ts, src/pages/KYC/schema.ts, src/pages/KYC/utils.ts
- Updated Individual KYC form (Investor Declaration);
- Updated Admin Panel (Ind.KYC);
=> [IXSwap.Interface] - Updated Individual KYC form (Investor Declaration); - Updated Admin Panel (Ind.KYC);

src/components/DateInput/index.tsx, src/components/SearchModal/CommonBases.tsx, src/components/SearchModal/CurrencyList.tsx
- Updated Mobile-DatePicker in KYC;
- Fixed BD and Custodian statuses for the SWAP;
=> [IXSwap.Interface] - Updated Mobile-DatePicker in KYC; - Fixed BD and Custodian statuses for the SWAP;

src/pages/KYC/IndividualKycForm.tsx
- Updated Individual KYC from (Address section)
=> [IXSwap.Interface]  - Updated Individual KYC from (Address section)

src/pages/KYC/IndividualKycForm.tsx
- Added immediate validation for form fields;
- Fixed wrong dates;
- Fixed tax declaration validation;
=> [IXSwap.Interface] - Added immediate validation for form fields; - Fixed wrong dates; - Fixed tax declaration validation;

src/components/KycReviewModal/Blocks/InvestorDeclaration.tsx, src/pages/KYC/utils.ts
- Fixed tax declaration validation;
=> [IXSwap.Interface] - Fixed tax declaration validation;

src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/schema.ts
=> [IXSwap.Interface] - Fixed KYC progress

src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/schema.ts, src/pages/KYC/utils.ts
=> [IXSwap.Interface]   - Fixed KYC progress

src/components/KycReviewModal/utils/constants.tsx
=> [IXSwap.Interface] - Fixed Individual KYC dates;

src/pages/Launchpad/Header.tsx, src/utils/routes.ts
=> [IXSwap.Interface] - Added Launchpad page

README.md
=> [IXSwap.Interface] - Updated Readme-file

src/components/SearchModal/CurrencyList.tsx, src/pages/Swap/SwapButtons.tsx
- Fixed accreditation status in the Swap UI;
=> [IXSwap.Interface] - Fixed accreditation status in the Swap UI;

src/components/KycReviewModal/Blocks/SourceOfFunds.tsx
=> [IXSwap.Interface] - Fixed Draft-Individual KYC;

src/components/KycReviewModal/Blocks/SourceOfFunds.tsx, src/components/SearchModal/CurrencyList.tsx, src/pages/Swap/SwapButtons.tsx
- Fixed accreditation status in the Swap UI;
- Fixed Draft-Individual KYC;
=> [IXSwap.Interface]

src/components/Launchpad/InvestmentCard/InvestmentSaleStatusInfo.tsx, src/components/Launchpad/InvestmentCard/index.tsx, src/components/Launchpad/InvestmentList/Filter.tsx, src/components/Launchpad/InvestmentList/FilterDropdown.tsx, src/components/Launchpad/InvestmentList/index.tsx, src/components/Launchpad/Offers/Pinned.tsx, src/components/Launchpad/Offers/index.tsx, src/pages/Launchpad/Banner.tsx, src/pages/Launchpad/index.tsx, src/state/launchpad/constants.ts, src/state/launchpad/hooks.ts, src/state/launchpad/types.ts
- Added fetching offers from backend
=> [IXSwap.Interface] - Added fetching offers from backend

src/components/Launchpad/InvestmentCard/index.tsx, src/state/launchpad/constants.ts
- Added fetching offers from backend;
=> [IXSwap.Interface] - Added fetching offers from backend;

src/components/Launchpad/KYCPrompt/index.tsx, src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/pages/App.tsx, src/pages/Launchpad/Footer.tsx, src/state/user/hooks.tsx
- Fixed closed authorization;
- Fixed UI-modals;
- Updated links;
=> [IXSwap.Interface] - Fixed closed authorization; - Fixed UI-modals; - Updated links;

src/components/Launchpad/KYCPrompt/ContactForm.tsx, src/components/Launchpad/KYCPrompt/index.tsx
- Fixed KYC status;
- Fixed support request;
=> [IXSwap.Interface] - Fixed KYC status; - Fixed support request;

src/components/Launchpad/KYCPrompt/index.tsx, src/components/Launchpad/Wallet/ConnectPrompt.tsx, src/components/Launchpad/Wallet/ConnectionDialog.tsx
- Added close button to Connect Wallet window
=> [IXSwap.Interface] - Added close button to Connect Wallet window

src/components/Launchpad/Offers/Pinned.tsx
- Fixed pinned offer (banner);
=> [IXSwap.Interface] - Fixed pinned offer (banner);

src/components/Launchpad/InvestmentCard/index.tsx, src/components/Launchpad/InvestmentList/PaginationTrigger.tsx, src/state/launchpad/types.ts
- Fixed status of the offers;
- Updated pagintation of the offers;
=> [IXSwap.Interface] - Fixed status of the offers; - Updated pagintation of the offers;

src/components/Launchpad/InvestmentCard/InvestmentSaleStatusInfo.tsx, src/components/Launchpad/InvestmentCard/index.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/state/launchpad/types.ts
=> [IXSwap.Interface] - Updated offer-card;

src/assets/launchpad/svg/help-icon.svg, src/components/Launchpad/InvestmentList/FilterDropdown.tsx, src/components/Launchpad/InvestmentList/PaginationTrigger.tsx, src/components/Launchpad/InvestmentList/index.tsx, src/components/Launchpad/NetworkNotAvailable/index.tsx, src/components/Launchpad/NetworkNotAvailable/styled.tsx, src/components/Launchpad/Offers/Pinned.tsx, src/components/Launchpad/Offers/index.tsx, src/components/Launchpad/Wallet/WalletInformation.tsx, src/components/LaunchpadOffer/InvestDialog/Sidebar.tsx, src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx, src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx, src/components/LaunchpadOffer/InvestDialog/content/styled.ts, src/components/LaunchpadOffer/InvestDialog/index.tsx, src/components/LaunchpadOffer/InvestDialog/utils/Checkbox.tsx, src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/components/LaunchpadOffer/InvestDialog/utils/InvestSubmitButton.tsx, src/components/LaunchpadOffer/InvestDialog/utils/InvestTextField.tsx, src/components/LaunchpadOffer/InvestDialog/utils/TokenClaimMessage.tsx, src/components/LaunchpadOffer/OfferMainInfo/OfferGalleryViewer.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/styled.ts, src/components/LaunchpadOffer/util/InfoList.tsx, src/components/LaunchpadOffer/util/Loader.tsx, src/pages/Launchpad/index.tsx, src/pages/LaunchpadOffer/index.tsx, src/theme/index.tsx, src/theme/styled.d.ts
- Added banner for unavailable networks;
- Added forms for invest button on offer page;
=> [IXSwap.Interface] - Added banner for unavailable networks; - Added forms for invest button on offer page;

src/components/Launchpad/NetworkNotAvailable/index.tsx, src/components/Launchpad/Offers/Pinned.tsx, src/pages/Launchpad/index.tsx
- Added forms for invest button on offer page
=> [IXSwap.Interface] - Added forms for invest button on offer page

src/components/Launchpad/InvestmentCard/index.tsx
- Fixed invest button on offer page;
=> [IXSwap.Interface] - Fixed invest button on offer page;

README.md
=> [IXSwap.Interface] - Updated Readme-file;

src/components/Launchpad/InvestmentCard/index.tsx
- Fixed claim-status on offer page;
=> [IXSwap.Interface] - Fixed claim-status on offer page;

src/components/Launchpad/InvestmentCard/InvestmentSaleStatusInfo.tsx, src/components/Launchpad/InvestmentCard/index.tsx, src/state/launchpad/types.ts
- Updated investment status info in the offer-card;
=> [IXSwap.Interface] - Updated investment status info in the offer-card;

src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx, src/components/LaunchpadOffer/InvestDialog/index.tsx, src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferContact.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferSaleAllocation.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferStage.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferTerms.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferVesting.tsx, src/components/LaunchpadOffer/OfferSidebar/index.tsx, src/pages/Launchpad/Header.tsx, src/pages/LaunchpadOffer/index.tsx, src/state/launchpad/hooks.ts, src/state/launchpad/types.ts
=> [IXSwap.Interface] - Fixed errors on Offer page

src/components/KycLightDocPreviewModal/index.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferAdditionalDocs.tsx, src/components/LaunchpadOffer/util/Attachment.tsx, src/components/LaunchpadOffer/util/InfoList.tsx, src/components/Modal/RedesignedLightWideModal.tsx, src/components/Modal/styleds.tsx, src/state/launchpad/types.ts, src/theme/components.tsx
=> [IXSwap.Interface] - Added docs-preview modal;

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/components/LaunchpadOffer/InvestDialog/utils/InvestTextField.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferFundRaiseIndicatpor.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferSaleAllocation.tsx, src/constants/constants.ts, src/state/launchpad/hooks.ts
- Updated values format;
- Updated sale form;
=> [IXSwap.Interface] - Updated values format; - Updated sale form;

src/components/LaunchpadOffer/OfferMainInfo/OfferGalleryViewer.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx
- Added component for playing YouTube videos on offer page
=> [IXSwap.Interface] - Added component for playing YouTube videos on offer page

src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx, src/components/LaunchpadOffer/InvestDialog/index.tsx, src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/components/LaunchpadOffer/InvestDialog/utils/InvestSubmitButton.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferFundRaiseIndicatpor.tsx, src/state/payout/hooks.ts
=> [IXSwap.Interface] - Updated Offer page;

src/components/LaunchpadOffer/OfferSidebar/index.tsx
=> [IXSwap.Interface] - Removed Vesting Part (PI);

package.json
=> [IXSwap.Interface] - Updated package.json;

src/components/DateInput/index.tsx, src/components/Launchpad/InvestmentCard/InvestmentStatusBadge.tsx, src/components/Launchpad/Wallet/ConnectionOptions.tsx, src/components/Launchpad/Wallet/WalletInformation.tsx, src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/common.tsx
IXSwap.Interface]
- Updated package.json;
=> IXSwap.Interface] - Updated package.json;

src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
- Removed email field from Register To Invest stage;
=> [IXSwap.Interface] - Removed email field from Register To Invest stage;

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx, src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx, src/state/launchpad/hooks.ts
=> [IXSwap.Interface] - Updated stage requests

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferInvestmentIndicator.tsx, src/state/launchpad/hooks.ts
- Added validation of balance;
=> [IXSwap.Interface] - Added validation of balance;

src/components/Launchpad/InvestmentCard/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/FAQ.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/TeamMembers.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts, src/components/LaunchpadIssuance/IssuanceForm/shared/FormGrid.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DIrectorFIeld.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DropdownField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FileField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FormField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/TextareaField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/styled.ts, src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx, src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferStage.tsx, src/pages/LaunchpadOffer/index.tsx, src/state/launchpad/types.ts
- Updated Issuance Information form
=> [IXSwap.Interface] - Updated Issuance Information form

src/components/LaunchpadOffer/OfferSidebar/OfferStage.tsx, src/pages/Launchpad/Banner.tsx
=> [IXSwap.Interface] - Updated some texts;

src/components/LaunchpadIssuance/IssuanceCreateButton/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/types.ts, src/components/LaunchpadIssuance/IssuanceForm/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DirectorField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FileField.tsx, src/components/LaunchpadIssuance/types.ts, src/components/LaunchpadMisc/buttons.ts, src/state/launchpad/hooks.ts, src/state/launchpad/types.ts
=> [IXSwap.Interface] - Added vetting creation

src/components/LaunchpadIssuance/IssuanceForm/Information/AdditionalInformation.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/Gallery.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts, src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/schema.ts, src/components/LaunchpadIssuance/IssuanceForm/Vetting/types.ts, src/components/LaunchpadIssuance/IssuanceForm/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/Calendar.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DropdownField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FileField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FormField.tsx, src/components/LaunchpadIssuance/utils/TextField.tsx, src/components/LaunchpadMisc/styled.ts, src/components/UsersList/mock.ts, src/constants/roles.ts, src/pages/Launchpad/Header.tsx, src/state/launchpad/hooks.ts
=> [IXSwap.Interface] - Updated vetting form

src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx, src/state/launchpad/hooks.ts
=> [IXSwap.Interface] - Updated vetting form;

src/components/LaunchpadIssuance/IssuanceDashboard/IssuancesFull.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/SearchFilter.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/index.tsx, src/components/LaunchpadMisc/tables.ts, src/state/launchpad/hooks.ts
=> [IXSwap.Interface] - Updated Issuance Dashboard;

src/components/LaunchpadIssuance/IssuanceForm/index.tsx, src/state/launchpad/hooks.ts, src/state/launchpad/types.ts
- Updated create issuance page
=> [IXSwap.Interface] - Updated create issuance page

src/services/interceptors.ts
=> [IXSwap.Interface] - Updated Vetting creation;

src/assets/launchpad/svg/vector-down.svg, src/assets/launchpad/svg/vector-up.svg, src/assets/launchpad/svg/vector_down.svgZone.Identifier, src/assets/launchpad/svg/vector_up.svgZone.Identifier, src/components/LaunchpadIssuance/IssuanceDashboard/IssuancesFull.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/SearchFilter.tsx, src/components/LaunchpadIssuance/utils/SortIcon.tsx, src/state/launchpad/hooks.ts
=> [IXSwap.Interface] - Updated Issaunce Dashboard;

src/components/LaunchpadIssuance/IssuanceCreateButton/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Review/Sidebar.tsx, src/components/LaunchpadIssuance/IssuanceForm/Review/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/schema.ts, src/components/LaunchpadIssuance/IssuanceForm/Vetting/types.ts, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DropdownField.tsx, src/components/LaunchpadIssuance/utils/SortIcon.tsx, src/components/LaunchpadIssuance/utils/TextField.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferSaleAllocation.tsx, src/pages/AppRoutes.tsx, src/pages/LaunchpadIssuance/InformationEditForm.tsx, src/pages/LaunchpadIssuance/InformationReview.tsx, src/pages/LaunchpadOffer/index.tsx, src/state/launchpad/hooks.ts
- Update Issuance Dashboard;
- Updated Issuance From (Create/Update);
=> [IXSwap.Interface] - Update Issuance Dashboard; - Updated Issuance From (Create/Update);

src/components/LaunchpadIssuance/IssuanceDashboard/IssuancesFull.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/PaginationTrigger.tsx, src/components/LaunchpadIssuance/utils/TextField.tsx
- Updated Vetting Form;
- Updated Issuance Dashboard;
=> [IXSwap.Interface] - Updated Vetting Form; - Updated Issuance Dashboard;

src/state/launchpad/hooks.ts
- Updated Issuance Dashboard;
- Updated Vetting Form;
=> [IXSwap.Interface] - Updated Issuance Dashboard; - Updated Vetting Form;

src/assets/launchpad/svg/cancel-vector.svg, src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FileField.tsx, src/state/launchpad/hooks.ts
- Updated Vetting Form;
- Added removing of documents;
=> [IXSwap.Interface] - Updated Vetting Form; - Added removing of documents;

src/components/LaunchpadIssuance/IssuanceDashboard/IssuanceStatusBadge.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/IssuancesFull.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/util.ts, src/components/LaunchpadIssuance/IssuanceForm/shared/RejectInfo.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FileField.tsx
- Updated Issuance Dashboard;
- Fixed New Form button (Vetting);
=> [IXSwap.Interface] - Updated Issuance Dashboard; - Fixed New Form button (Vetting);

src/components/LaunchpadIssuance/IssuanceDashboard/IssuancesFull.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/OffersFull.tsx, src/components/LaunchpadMisc/tables.ts
- Updated Issuance Dashboard (font-family);
=> [IXSwap.Interface] - Updated Issuance Dashboard (font-family);

src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/FAQ.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts, src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts, src/components/LaunchpadIssuance/IssuanceForm/Review/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DirectorField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FormField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/ImageField.tsx, src/components/LaunchpadIssuance/utils/Dialog.tsx, src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferAdditionalDocs.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferContact.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferSaleAllocation.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferStage.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferTerms.tsx, src/components/LaunchpadOffer/OfferSidebar/index.tsx, src/pages/LaunchpadIssuance/InformationReview.tsx, src/state/launchpad/hooks.ts, src/state/launchpad/types.ts
=> [IXSwap.Interface] - Added offer form review

src/components/Launchpad/InvestmentCard/InvestmentSaleStatusInfo.tsx, src/components/Launchpad/InvestmentCard/InvestmentStatusBadge.tsx, src/components/Launchpad/InvestmentCard/InvestmentTypeInfo.tsx, src/components/Launchpad/InvestmentCard/index.tsx, src/components/Launchpad/InvestmentList/Filter.tsx, src/components/Launchpad/InvestmentList/FilterDropdown.tsx, src/components/Launchpad/InvestmentList/PaginationTrigger.tsx, src/components/Launchpad/InvestmentList/index.tsx, src/components/Launchpad/Offers/Pinned.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/IssuanceStatusBadge.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/IssuancesFull.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/OffersFull.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/index.tsx, src/components/LaunchpadIssuance/utils/TextField.tsx, src/components/LaunchpadMisc/buttons.ts, src/components/LaunchpadMisc/tables.ts
- Updated Issuance Dashboard (font-family);
- Updated New Issuance form;
- Fixed Issuances status;
=> [IXSwap.Interface] - Updated Issuance Dashboard (font-family); - Updated New Issuance form; - Fixed Issuances status;

src/components/Launchpad/ConfirmForm/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx
- Added confirmation form to Vetting;
=> [IXSwap.Interface] - Added confirmation form to Vetting;

src/components/LaunchpadIssuance/IssuanceDashboard/IssuancePagination.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/IssuancesFull.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/AdditionalInformation.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/FAQ.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/Gallery.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/TeamMembers.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/UploadDocuments.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts, src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts, src/components/LaunchpadIssuance/IssuanceForm/Review/Sidebar.tsx, src/components/LaunchpadIssuance/IssuanceForm/Review/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DropdownField.tsx, src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferStage.tsx, src/state/launchpad/hooks.ts, src/state/launchpad/types.ts
=> [IXSwap.Interface] - Added offer draft edit

src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/AdditionalInformation.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/Gallery.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/TeamMembers.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/UploadDocuments.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/util.ts, src/components/LaunchpadIssuance/IssuanceForm/Review/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DropdownField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FileField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FormField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/ImageField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/TextareaField.tsx, src/components/LaunchpadIssuance/utils/TextField.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferTerms.tsx, src/components/LaunchpadOffer/util/InfoList.tsx, src/state/launchpad/hooks.ts, src/state/launchpad/types.ts
=> [IXSwap.Interface] - Updated offer form

src/components/LaunchpadIssuance/ManageOffer/HeaderButtons.tsx, src/components/LaunchpadIssuance/ManageOffer/index.tsx, src/components/LaunchpadIssuance/ManageOffer/investments/index.tsx, src/components/LaunchpadIssuance/ManageOffer/presale/WhitelistApprove.tsx, src/components/LaunchpadIssuance/ManageOffer/shared/ConfirmModal.tsx, src/state/launchpad/hooks.ts
- added backend integration to claim buttons
- fixed bug when showing "whitelist" and "presale" stages to non presale offers.
- added 2 generic hooks - for fetching with pagination and for post methods
blockchain integration will be in a separate PR
=> Manage offer: claim

src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx, src/components/LaunchpadIssuance/ManageOffer/Stages.tsx, src/components/LaunchpadIssuance/ManageOffer/edit/index.tsx, src/components/LaunchpadIssuance/ManageOffer/index.tsx, src/components/LaunchpadIssuance/utils/ContactFormModal.tsx, src/components/LaunchpadMisc/styled.ts, src/state/launchpad/hooks.ts, src/state/launchpad/types.ts, src/utils/time.ts
- edit timeframe
- fix success message shown on error
- handle claim for unsuccessful deals
=> Edit timeframe & other

src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Review/index.tsx, src/components/LaunchpadIssuance/ManageOffer/Stages.tsx, src/components/LaunchpadIssuance/ManageOffer/presale/WhitelistInfo.tsx, src/components/LaunchpadIssuance/utils/constants.tsx, src/components/LaunchpadMisc/styled.ts, src/components/LaunchpadOffer/InvestDialog/Sidebar.tsx, src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx, src/components/LaunchpadOffer/InvestDialog/index.tsx, src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferSaleAllocation.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferStage.tsx, src/components/LaunchpadOffer/OfferSidebar/index.tsx, src/state/launchpad/types.ts
=> launchpad offer bugs

src/components/LaunchpadIssuance/IssuanceForm/Information/index.tsx, src/components/LaunchpadIssuance/ManageOffer/presale/WhitelistList.tsx, src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx
=> fix issuance page bugs

src/components/LaunchpadIssuance/IssuanceForm/Information/sections/TeamMembers.tsx, src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DirectorField.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FormField.tsx, src/components/LaunchpadIssuance/utils/TextField.tsx, src/state/launchpad/hooks.ts
- Offer members duplicates - https://app.clickup.com/t/4733323/IXS-2741
- Vetting duplicates - https://app.clickup.com/t/4733323/IXS-2784
- Vetting remove bucket when viewing files - https://app.clickup.com/t/4733323/IXS-2743
=> Form fixes

src/components/LaunchpadIssuance/IssuanceDashboard/EmptyTable.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/IssuancesFull.tsx, src/components/LaunchpadIssuance/IssuanceDashboard/OffersFull.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/FileField.tsx, src/components/LaunchpadIssuance/utils/form.ts
- Update no issuances message
- Fix file too large error
- Fix errors parsing on isDraftDisabled method
=> bug fixing

src/components/LaunchpadOffer/InvestDialog/index.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/hooks/Tokens.ts
=> IXS-2911: Insufficient balance

src/components/LaunchpadIssuance/ManageOffer/ConfirmClaimModal.tsx, src/components/LaunchpadIssuance/ManageOffer/HeaderButtons.tsx, src/components/LaunchpadIssuance/ManageOffer/index.tsx, src/components/LaunchpadIssuance/utils/ConfirmPopup.tsx, src/components/LaunchpadOffer/OfferMainInfo/OfferTeamMembers.tsx, src/state/launchpad/types.ts
Add distributor controller address to manage page IXS-3002; fix member photo IXS-3003
=> Fixes IXS-3002 and IXS-3003

src/components/KycReviewModal/Blocks/Cynopsis.tsx, src/components/KycReviewModal/index.tsx, src/pages/LaunchpadOffer/index.tsx, src/state/launchpad/types.ts
…ated for only accredited investors
=> IXSPD1-262, IXSPD1-282: Fix bugs KYC and Live deal

package.json, yarn.lock
- Adding TIXS token to mumbai list
=> Update default token list package

src/components/LaunchpadIssuance/IssuanceForm/Information/sections/IssuanceActionButtons.tsx, src/components/LaunchpadIssuance/ManageOffer/presale/WhitelistInfo.tsx
Description:
- Fix bug [FE] Dev | Issuance Dashboard - Admin is directed to KYC page after approving issuance form
Bullet points of the changes:
- Disable page reload
- Change text
Link to jira ticket:
https://investax.atlassian.net/browse/IXSPD1-968
https://investax.atlassian.net/browse/IXSPD1-899
=> IXSPD1-968, IXSPD1-899: fe dev issuance dashboard admin is directed to kyc page after approving issuance form

src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/components/LaunchpadOffer/InvestDialog/utils/InvestTextField.tsx, src/pages/KYC/CorporateKycForm.tsx, src/pages/KYC/schema.ts
In the MetaMask connection modal, decimal numbers in the launchpad, individual, and corporate KYC validations were experiencing some bugs and required upgrades. These issues have been fixed, and the changes are ready for merging into the development branch.
- Users cannot submit Individual KYC when selecting TIN is not available fixed
- KYC as Corporate - Validation error messages display incorrect position fixed
- Enforce rounded numbers when investing in launchpad done
- The blank popup still displays after connect wallet on Launchpad page fixed
- Connect Wallet - The UI of screen is not correct after opening MetaMask extension fixed
https://investax.atlassian.net/browse/IXSPD1-361
https://investax.atlassian.net/browse/IXSPD1-90
https://investax.atlassian.net/browse/IXSPD1-955 …
=> IXSPD1-361 & 90 & 955 & 759 and 989 fixed and pushed on dev

src/components/Header/index.tsx, src/components/KycReviewModal/Blocks/Information.tsx, src/components/KycReviewModal/index.tsx
UI bug fixes include resolving issues with the navbar, specifically addressing problems with the 'Connect Wallet' button, removing the 'KYC' button, and rectifying the missing title in Corporate KYC.
- Add "Connect Wallet" button on the top nav bar fixed
- Remove KYC button and profile button fixed
- Missing Title of Corporate KYC ( Admin review KYC)  fixed
No Jira tickets were created for these fixes; they were picked directly from the comment made by QA
=> disconnect wallet kyc button and Corporate KYC title issue fixed

src/pages/KYC/EmailVerifyModal.tsx
Description: Fix email validation
changes:
- Allow -, + , _
- Remove validation for mail's domain + name
=> Fix email validation

src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/components/Launchpad/Wallet/ConnectionOptions.tsx
In this pull request, three fixes have been implemented all were related to Metamask
- The warning text for MetaMask has been revised to include the directive "use this wallet" and padding has been added.
- The issue where clicking on WalletConnect displayed the screen "Connecting to MetaMask" for approximately 2 seconds before displaying the QR code has been resolved.
- The error message displaying "Please install MetaMask to use this application" when the user hasn't clicked on MetaMask yet has been fixed.
https://investax.atlassian.net/browse/IXSPD1-1008
https://investax.atlassian.net/browse/IXSPD1-1011
https://investax.atlassian.net/browse/IXSPD1-1012
=> IXSPD1-1008 and 1012 and 1011 pushing on dev

src/components/Launchpad/Wallet/ConnectionOptions.tsx, src/components/WalletModal/index.tsx
Description: 
Disable deeplink as it causes unexpected issues for metamask browser
Changes:
- Disable connect options with deeplink
=> Disable deeplink as it causes unexpected issues for metamask browser

src/components/Vault/WithdrawRequestForm.tsx, src/services/apiUrls.ts, src/state/withdraw/hooks.ts
Description:
Change the get withdrawal fee endpoint 
Changes:
- Update withdrawal fee endpoint from `/token/price/${id}` to `/custody/withdraw/fee?tokenId=${id}&amount=${amount}`
=> update withdrawal fee endpoint

src/components/Launchpad/Wallet/ConnectionOptions.tsx
Temporarily disable install metamask as the injected metamask is displayed as install metamask in metamask browser
=> Try comment install metamask option

.eslintrc.json
Fix is related to this breaking changes:
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
-
-
-
2. Documents:
=> updated eslint config

.github/workflows/release.yaml
=> try disable eslint

.github/workflows/release.yaml
=> fix run command

src/pages/KYC/common.tsx
=> #2 : Ugly error message when submitting the empty KYC form

src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx
Increase the space between USDT and investment
- just added &nbsp for the spacing
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1027
2. Documents:
=> IXSPD1-1027  Increase the space between USDT and investment is done

src/pages/KYC/schema.ts
=> IXSPD1-1021: Make Financial section optional for certain countries

src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/schema.ts
=> IXSPD1-1021: Fix UI

src/pages/KYC/schema.ts
Fix the issue related to Financial section on Production
- Update the logic of validation
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1050
2. Documents:
=> IXSPD1-1050: The "Employee" field must not be required if Russia, Turkey or Nigeria are not selected

src/pages/KYC/enum.ts
Fix idtype passport -> international passport
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1057
2. Documents:
=> Fix idtype passport -> international passport

src/pages/KYC/enum.ts
Update key from passport to international passport
2. Documents:
=> Update key from passport to international passport

src/pages/KYC/enum.ts
This is a prerelease for v0.5.2
change PASSPORT -> INTERNATIONAL_PASSPORT
2. Documents:
=> Prerelease v0.5.2

src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx
Open the new tab when clicking on the links on Launchpad detail page is done
- just added CSS
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1061
2. Documents: NA
=> Dataroom open in new tab

package.json, src/assets/images/group1.svg, src/assets/images/group2.svg, src/assets/images/group3.svg, src/components/Line/index.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Graph.tsx, src/pages/LBP/components/Tokenomics.tsx, yarn.lock
LBP form component
-
-
-
2. Documents:
=> LBP form component

package.json, src/constants/addresses.ts, src/utils/constructSameAddressMap.ts, yarn.lock
Bump version of v2-sdk to support amoy
-
-
-
2. Documents:
=> Bump version of v2-sdk to support amoy

src/components/LBP/Dashboard/LbpsFull.tsx, src/components/LBP/LbpCreateButton/index.tsx, src/components/LBP/types.ts, src/pages/AppRoutes.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/ProjectInfo.tsx, src/state/launchpad/hooks.ts, src/state/lbp/constants.ts, src/state/lbp/hooks.ts, src/utils/routes.ts
API Integration - Save Draft LBP/Submit LBP
- Implement flow: create, edit, load, save draft, submit LBP 
- Update APIs on Backend: https://github.com/IX-Swap/backend/commit/8f13952aecf6e0ce76842426232d8460251ed665
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1076
2. Documents:
=> IXSPD1-1076: API Integration - Save Draft LBP/Submit LBP

src/components/LBP/InvestmentList/LbpCard.tsx, src/utils/routes.ts
Redirect the user from the launchpad to the LBP details page.
- I just added a dynamic route for redirecting to LBP details.
-
-
2. Documents:
=> Redirect the user from the launchpad to the LBP details page.

src/components/LBP/Dashboard/LbpDashboard.tsx, src/components/LBP/Dashboard/LbpsFull.tsx
Fix UI bugs of LBP admin
- Fix css
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1041
2. Documents:
=> IXSPD1-1041: Fix UI of LBP admin page

src/components/LBP/types.ts, src/constants/addresses.ts, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Tokenomics.tsx
Lbp code refactoring
- Load token options based on chain Id
- add `assetTokenAddress`, `assetTokenSymbol` to LBP post payload
2. Documents:
=> Lbp code refactoring

src/components/LBP/PublicDetails/Background.tsx, src/components/LBP/PublicDetails/Links.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/QuantitiesAndWeight.tsx, src/components/LBP/PublicDetails/VolumeData.tsx, src/components/LBP/types.ts, src/pages/LBP/PublicDetails.tsx
API integration - Display LBP public detail data have been done
- these are the data that added to the details page
- Logo, Background, Name, Description, Wesite ,white paper, Share token, Asset token
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1100
2. Documents:
=> Display LBP public detail data API integration have been done

src/components/LBP/Forms/SubmitSummary.tsx, src/pages/LBP/LbpForm.tsx
Implement summary component when submitting LBP
- Implement UI
- Load data from LBPForm
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1039
2. Documents:
=> IXSPD1-1039: Implement summary component when submitting LBP

src/assets/images/noTokensAvaliable.svg, src/components/LBP/PublicDetails/NoTokensSideBar.tsx, src/components/LBP/PublicDetails/SideBar.tsx
Add new view for Buy/Sell section when there are no available Project tokens in the Pool is done. create a new component for this. this component is Hiding for now will render conditionals on the pool value.
- just a UI added
- https://investax.atlassian.net/browse/IXSPD1-1107
-
2. Documents:
=> Ixspd1 1107 Add new view for Buy/Sell section when there are no available Project tokens in the Pool is done

src/components/LBP/PublicDetails/ComingSoon.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx
Add 2 types of countdown for Coming Soon User details page is done
- Days and Time both countdowns have been handled 
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1105
2. Documents:
=> Ixspd1 1105 Add 2 types of countdown for Coming Soon User details page

src/components/LBP/PublicDetails/BuySellFields.tsx
errors for Buy/Sell form added for all types
- error handlings for BUY and SELL side bar 
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1106
2. Documents:
=> errors for Buy/Sell form added

src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/RedeemedSideBar.tsx
Add Redeemed view for Buy/Sell section is done.
- UI have been updated
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1104
2. Documents:
=> Ixspd1 1104 Add Redeemed view for Buy/Sell section is done.

src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/Modals/BuySellModal.tsx
Modal have been created for the Buy and Sell confirmation 
- Just added a new UI
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1108
2. Documents:
=> Add confirmation pop up for Buy/Sell transactions is done

src/abis/LiquiidtyBoostrapPool.json, src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/SideBar.tsx, src/hooks/useContract.ts, src/hooks/web3.ts
- Fix buy/sell bugs
- Code refactoring
- Handle conversion
-
-
-
2. Documents:
=> Ixspd1 1110 refactored

src/hooks/useApproveCallback.ts, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Approvals.tsx, src/pages/LBP/components/Tokenomics.tsx
Implement token approval for share and assets in LBP form have been done
- handled with the help of useApproveCallback hook to approve both tokens
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1117
2. Documents:
=> Implement token approval for share and assets in LBP form have been done

src/pages/LBP/components/ProjectInfo.tsx, src/pages/LBP/components/Tokenomics.tsx, src/state/lbp/hooks.ts
=> IXSPD1-1115: Cannot save Start Date, End Date, Upload Documents

src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Approvals.tsx, src/pages/LBP/components/Branding.tsx, src/pages/LBP/components/ProjectInfo.tsx, src/pages/LBP/components/Tokenomics.tsx, src/theme/index.tsx
some form bugs have been fixed
- there were few bugs on LBP form. validations bugs and token related bugs have been addressed.
-
-
2. Documents:
=> some form bugs have been fixed

src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/PublicDetails/HistoryTable.tsx, src/constants/subgraph.ts, src/hooks/useSubgraphQuery.ts, src/pages/LBP/components/Approvals.tsx
This PR implement the foundation for subgraph integration 
- Define the subgraph constant URLs
- Show trade history from subgraph data
- Fix LBP deployment
- Show correct token logos
- Handle pagination
2. Documents:
=> Lbp trade history integration with Subgraph + Fix LBP deployment

src/components/LBP/PublicDetails/HistoryTable.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx
Ixspd1 1079 API Integration - show trade history is done
- Fix the logos of the asset/share done
- Fix the pagination done
- Pass the contractAddress to the TradeHistory props done
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1079
2. Documents:
=> Ixspd1 1079 API Integration - show trade history is done

src/components/LBP/Dashboard/LbpDashboard.tsx, src/components/LBP/Dashboard/LbpsFull.tsx, src/components/LBP/LbpCreateButton/index.tsx
LBP Dashboard - Fix UI bugs related to LBP Dashboard
- "New LBP" not "New Lbp" button
- Draft tab -> Drafts
- Remove the frame of Edit button
- Highlight the Edit button when hover on it 
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1116
2. Documents:
=> IXSPD1-1116: LBP Dashboard - Fix UI bugs related to LBP Dashboard

src/components/LBP/PublicDetails/HistoryTable.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/PublicChart.tsx
Implement public price chart for the LBP detail page
- Retrieve historical data from subgraph + calculate future price using existing formula
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1083
2. Documents:
=> Implement price chart for detail page

src/components/AdminTransactionsTable/index.tsx, src/components/LBP/PublicDetails/Background.tsx, src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/HistoryTable.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/QuantitiesAndWeight.tsx, src/components/LBP/PublicDetails/SideBar.tsx, src/components/LBP/PublicDetails/StatisticData.tsx, src/components/LBP/PublicDetails/VolumeData.tsx, src/components/LBP/types.ts, src/pages/LBP/PublicDetails.tsx, src/state/lbp/hooks.ts
- start quantities, start weight, end weight integration 
- Display the correct token logo, token symbol
- Fix the token logo on the buy/sell box
- Hide the price change badge
- displayed a loader overlay on detail page
-  fixed current quantities
-  calculated correct remaining days in the buy/sell box
- made the live button unclickable
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1119
2. Documents:
=> Ixspd1 1119 Statistic API integration for the LBP detail page have been done and some bug fixes handled.

src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/PublicChart.tsx
Show sidebar by status + Fix LBP deployment
- Show sidebar by status
- Fix LBP deployment's weights
- Minor fix on the LBP public chart
2. Documents:
=> Show sidebar by status + Fix LBP deployment

src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/HistoryTable.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/PublicChart.tsx, src/components/LBP/PublicDetails/StatisticData.tsx, src/components/LBP/types.ts, src/components/LBP/utils/calculation.ts, src/hooks/useApproveCallback.ts, src/pages/LBP/AdminLbpDetail.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Approvals.tsx, src/pages/LBP/components/Tokenomics.tsx, src/state/lbp/hooks.ts, src/utils/getExplorerLink.ts
Lbp bug fixes + improvements
[Getting swap fee through LBP factory, increase useLBPtrades interval …](https://github.com/IX-Swap/interface/commit/b819c810c17df4f0cc73e983bf75cbf69289e012) 
[Show error message: amountInTooLarge](https://github.com/IX-Swap/interface/commit/9aedaac14d1050cce3e80c7e3e862ab84f1434ad)
[Implement useMemo for priceImpact](https://github.com/IX-Swap/interface/commit/20c0e45a78a5a53807f5391ce1bb2e76b415db3e)
[Reset opposite field while converting](https://github.com/IX-Swap/interface/commit/54c3e843af0e3efbf7fd4fbebd44fb46e64d9e78)
[Disable button if there are errors](https://github.com/IX-Swap/interface/commit/538aff8e928a0625367ff75d7e543bec00024adb)
[Minor fix on token released](https://github.com/IX-Swap/interface/commit/5246b1edfb52fa2fe8f328625751be924b93ebea) …
=> Lbp improvements

package.json
Bump default token list to remove WETH
2. Documents:
=> Bump default token list to remove WETH

src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/ProjectInfo.tsx
implemented social media dropdown for LBP form.
- previously there was an input so FE and BE can’t able to recognise the correct social media name that issue have been fixed. now we are using the select.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1125
2. Documents:
=> social media dropdown have been added

src/components/LBP/Dashboard/InvestorInformation.tsx, src/pages/LBP/AdminLbpDetail.tsx, src/state/lbp/hooks.ts
Api Added on Get investor information sorting and pagination also added
- API added
- pagination and sorting handled from FE side.
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1080
2. Documents:
=> Api Added on Get investor information sorting and pagination also added

src/abis/LiquidityBoostrapPoolFactory.json, src/components/LBP/Forms/SubmitSummary.tsx, src/constants/addresses.ts
Update LBP factory address
2. Documents:
=> Update LBP factory address

src/components/LBP/Forms/SubmitSummary.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Tokenomics.tsx
submit button is disabled until filled all required fields. added validations and remove validations from these fields
Additional links
Documents.
Max price
Project Token Max Supply
- added form validations
- made some validations optional 
https://investax.atlassian.net/browse/IXSPD1-1130
2. Documents:
=> Lbp form validations added.

src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/PublicChart.tsx, src/components/LBP/PublicDetails/SideBar.tsx
- [Fix purplelinep percentage in LBP chart](https://github.com/IX-Swap/interface/commit/c0e017f24748fde33f9109e6bb73ee9aef336d4d)
- [Handle LBP slippage smart contract logic](https://github.com/IX-Swap/interface/commit/6a54f16810d560602fce79e8784d01625e8e09e0)
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1132
2. Documents:
=> Ixspd1 1132 fe slippage logic smart contract integration for buy sell

src/assets/images/websiteIcon.svg, src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/ComingSoon.tsx, src/components/LBP/PublicDetails/Links.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LaunchpadIssuance/IssuanceCreateButton/index.tsx, src/pages/KYC/common.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Approvals.tsx, src/pages/LBP/components/Branding.tsx, src/pages/LBP/components/ProgressBar.tsx, src/pages/LBP/components/Tokenomics.tsx
There were several bugs on the LBP form and details page in this PR; I fixed that."
- The USDC token is now chosen by default.
-  The correct social media icons are displayed on the detail page.
- The coming soon page now shows the correct date.
- The logo and banner no longer swap after saving the draft and refreshing.
- A loader has been added to the logo.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1156
2. Documents:
=> lbp bug fixes on from and details page

src/components/LBP/PublicDetails/BuySellFields.tsx
Fix bug user cannot sell project token on LBP
- Set fixed gas to 300,000 for buy/sell transactions
- Better error handling
1. Jira ticket:  https://investax.atlassian.net/browse/IXSPD1-1176
2. Documents:
=> IXSPD1-1176 - [BE] Dev | LBP - User cannot sell the Project token

src/components/LaunchpadIssuance/ManageOffer/presale/index.tsx
IXSPD1-899 simple UI hotfix on the issuance live deal
- just changed the UI display: flex; to display: block;
1. Jira ticket:https://investax.atlassian.net/browse/IXSPD1-899
2. Documents:
=> IXSPD1-899 simple UI hotfix on the issuance live deal

src/components/LBP/Forms/SubmitSummary.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Tokenomics.tsx
- "Enable 'Submit Form' button" remains inactive despite completion of all mandatory fields.
- Fix bug LBP - Start Date, End Date are saved with incorrect timezone -> don't set default timezone Singapore
- Fix [BE][FE] Dev | LBP - Nothing displays after deploying LBP successfully -> show successful toast
- Disable deploy button if LBP is being deployed or is already deployed
- Do not allow users to select past hours in the current day
- date validations error message was not displayed properly now added for both End date and start Date
-
-
https://investax.atlassian.net/browse/IXSPD1-1184
https://investax.atlassian.net/browse/IXSPD1-1131
https://investax.atlassian.net/browse/IXSPD1-1163
https://investax.atlassian.net/browse/IXSPD1-1171
2. Documents:
- Ensure new code …
=> IXSPD1-1184, IXSPD1-1131, IXSPD1-1163, IXSPD1-1171 Fix high priority bugs for LBP

src/components/LBP/Dashboard/InvestorInformation.tsx, src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/InvestmentList/LbpCard.tsx, src/components/LBP/PublicDetails/Ended.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/Launchpad/InvestmentCard/index.tsx, src/pages/AppRoutes.tsx, src/pages/LBP/AdminLbpDetail.tsx, src/pages/LBP/components/Tokenomics.tsx
Successfully completed various tasks aimed at enhancing the functionality and user experience of the LBP module. These include implementing KYC restrictions, ensuring accurate information display, standardizing base token naming conventions, resolving UI bugs, and refining terminology for improved clarity in the admin interface.
- Implemented KYC restrictions to prevent access for non-KYC users.
- Ensured accurate information display in the submit summary component.
- Standardized the base token name to always be USDC in weight configuration.
- Resolved disappearance of the top nav bar in the admin side manager of LBP
- Fixed UI bugs on the Ended panel of concluded LBP.
- Renamed the table header to "Number of Tokens" in the admin details page. …
=> Resolved IXSPD1-1180, 1185, 1186, 1187, and 1189 LBP bugs related to the LBP form, detail view, ended panel, and navigation bar.

src/components/LBP/Forms/SubmitSummary.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Graph.tsx, src/pages/LBP/components/Tokenomics.tsx, src/state/lbp/hooks.ts
- Fix discovery preview
- Fix submit summary
- Fix not closing LBP after saving progress
- Show correct information for discovery previw
- Fix not closing LBP after saving progress
- Automatically calculate min price, make this field disabled
- Show start price, start marketcap in submit summary
- https://investax.atlassian.net/browse/IXSPD1-1165
- https://investax.atlassian.net/browse/IXSPD1-1188
- https://investax.atlassian.net/browse/IXSPD1-1197
2. Documents:
=> IXSPD1-1165 Show correct information for discovery preview 

src/components/LBP/Dashboard/LbpDashboard.tsx, src/components/LBP/Dashboard/LbpsFull.tsx, src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/PublicDetails/SideBar.tsx
Fixes for LBP deployment and other UI bug fixes 
- Redirect to “Pending” tab after successful LBP deployment
- Set default slippage to 0.5
- Show paused LBPs in live tab, show closed LBPs in ended tab
https://investax.atlassian.net/browse/IXSPD1-1163
https://investax.atlassian.net/browse/IXSPD1-1198
2. Documents:
=> Fixes for LBP deployment and other UI bug fixes

src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/types.ts, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Tokenomics.tsx, src/state/lbp/hooks.ts
Fix remain lbp form bugs
- maxPrice is submitted as string
- uploadDocs is undefined
- remove minPrice
2. Documents:
=> Lbp form bug fixes

src/components/LBP/PublicDetails/MiddleSection.tsx
Fix bug crash no upload document
2. Documents:
=> Fix bug LBP detail with no upload document crashed

src/components/LBP/Forms/SubmitSummary.tsx, src/pages/LBP/components/Graph.tsx
Ixspd1 1165 update lbp marketcap range formula
2. Documents:
=> Fix marketcap range calculation

src/pages/LBP/components/Tokenomics.tsx
Minor lbp date bug fix
- Fix a bug that error is not updated for end date when start date changes
2. Documents:
=> Fix bug end date error is not updated if start date changes

src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/SideBar.tsx, src/state/lbp/hooks.ts
Fix sell execution errors
-  Set default slippage to 1%
-  Fix issue not enough balance due to round up
2. Documents:
=> Ixspd1 1196 fix issues sell execution error

src/components/LBP/PublicDetails/BuySellFields.tsx
Fix for issue https://investax.atlassian.net/browse/IXSPD1-1218
- Add value for check insufficient balance in Buy form
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1218
2. Documents:
=> Ixspd1-1218 fe there is no insufficient balance error when user does not have enough token to sell

src/components/LBP/PublicDetails/BuySellFields.tsx
- Add debounce for inputs in BuySellFields component
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1219
2. Documents:
=> IXSPD1-1219 FE Apply debounce for LBP buy sell inputs

src/components/LBP/Admin/AdminHeader.tsx, src/pages/LBP/AdminLbpDetail.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Approvals.tsx, src/pages/LBP/components/Tokenomics.tsx
some bugs have been addressed regarding to tickets  IXSPD1-1192 1193 and pool address
- pool address url have been updated. now if user clicks on the pool address then it goes to explorers 
- remaining fields are now disabled in LBP form if user is admin and status is not draft
- auto changing number while scrolling issue have been fixed
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1192
https://investax.atlassian.net/browse/IXSPD1-1193
2. Documents:
=> some bugs have been addressed regarding to tickets  IXSPD1-1192 1193 and pool address

src/components/LBP/PublicDetails/BuySellFields.tsx
- Handle add project token to metamask
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1222
2. Documents:
=> Ixspd1-1222 fe dev lbp the button add base token to wallet does not work

src/components/LBP/InvestmentList/LbpCard.tsx, src/components/LBP/PublicDetails/ComingSoon.tsx, src/state/user/hooks.tsx
Handled the non-KYC user popup in LBP listing, and also resolved the 'coming soon' date and time issue.
- if KYC is undefined then show the popup in lbp listing
- updated the show coming soon date and time logic
-
2. Documents:
=> Handled the non-KYC user popup in LBP listing, and also resolved the 'coming soon' date and time issue.

src/assets/images/checked-green.svg, src/components/LBP/PublicDetails/RedeemedSideBar.tsx, src/hooks/useSubgraphQuery.ts
- Fix The Redeem button does not change status after user completes the "Redeem"
2. Documents:
=> Ixspd1-1199 fe dev lbp the redeem button does not change status after user completes the redeem

src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/Ended.tsx
- Fix Name of some fields in LBP detail page need to be corrected
-
-
2. Documents:
=> Ixspd1-1230 fe dev lbp name of some fields in lbp detail page need to be corrected

src/pages/AppRoutes.tsx
Fix LBP detail access control issue
-
-
-
2. Documents:
=> Fix LBP detail access control issue

src/pages/App.tsx, src/pages/AppRoutes.tsx
=> Revert access control for LBP detail routes as they are not working

src/pages/AppRoutes.tsx, src/pages/LBP/PublicDetails.tsx
Redirect to KYC while reloading the detail page issue has been fixed.
- removed the conditions from the routes
- checking if Metamask is connected or not if not connected then redirect user to KYC page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1226
2. Documents:
=> Redirect to KYC while reloading the detail page issue has been fixed.

src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/SideBar.tsx, src/components/LBP/types.ts
- Support `allowSlippage` flag , only enable slippage if the flag is `true`, otherwise use default slippage
- Code refactoring
- Handle conversion before trade execution
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1196
2. Documents:
=> Ixspd1-1196  dev lbp sometimes the execution error occurs when the user buys or sells

src/pages/AppRoutes.tsx
update the route and made public detail componenet lazy load to fix reload issue
-
-
-
2. Documents:
=> update the route and made public detail componenet lazy load to fix reload issue

src/pages/AppRoutes.tsx, src/pages/LBP/PublicDetails.tsx
removed the logic of if user not connected to metamask user should redirect to kyc page(just for testing relaod issue)
-
-
-
2. Documents:
=> removed the logic of if user not connected to metamask user should redirect to kyc page

src/pages/KYC/index.tsx
- Fix Only keep Polygon as the supported chain for IXS
2. Documents:
=> Ixspd1-1137 only keep polygon as the supported chain for ixs

src/pages/KYC/index.tsx
Revert Leon's "Fix Only keep Polygon as the supported chain for IXS" task as it's not stable
2. Documents:
=> Revert "Fix Only keep Polygon as the supported chain for IXS"

src/components/LBP/InvestmentList/LbpCard.tsx, src/components/LBP/InvestmentList/LbpSaleStatusInfo.tsx
- Clone function calculateRemainingTime from page CommingSoon
- Add UI for case remainingDays > 1
- Add UI for case remainingDays < 1 => Add new UI follow Figma https://www.figma.com/design/or3Ee8UGxJDsiWeMBPZFVk/IXS-App-(Canonical---Updated)?node-id=4719-6057&t=nIXABgcA3yTiYzwh-0
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1253
2. Documents:
=> Ixspd1-1253 fe dev lbp displaying the counter until lbp ends on the coming soon card is not correct

src/components/LBP/InvestmentList/LbpSaleStatusInfo.tsx
- Improve UX for loading after reloading the page.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1253
2. Documents:
=> IXSPD1-1253 Improve UX for loading after reloading the page.

src/components/LBP/Admin/AdminHeader.tsx, src/components/LBP/Admin/Modals/ConfirmStatusModal.tsx, src/components/LBP/Forms/SubmitSummary.tsx, src/pages/AppRoutes.tsx
- Made detail page restricted for only if isKycApproved
- adjust some UI in multiple pages
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1247
2. Documents:
=> some UI fixes and made detail page restricted for only if isKycApproved

src/components/LBP/PublicDetails/BuySellFields.tsx
- Fix The message "Insufficient balance" should be hidden when user clear the input
- Fix Base Token amount should be cleared when user clear the project token input and vice versa
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1254
2. Documents:
=> IXSPD1-1254 FE-Dev-LBP-Fix-some-validation-issue-on-Buy-an-Sell-panel

src/pages/LBP/components/Tokenomics.tsx
- Add validate isAddress for Project Token Address
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1244
2. Documents:
=> Ixspd1-1244 fe dev lbp display error message when user inputs invalid project token address

src/components/LBP/PublicDetails/PublicChart.tsx
Bug 138 fix lbp chart color
1. Jira ticket: bug 138
2. Documents:
=> Show grey color for deals that have completed

src/components/LBP/PublicDetails/StatisticData.tsx
- Show the correct volume data in LBP statistic component (get from subgraph)
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1255
2. Documents:
=> Ixspd1-1255 fe show the correct volume data in lbp statistic component

src/components/LBP/InvestmentList/LbpCard.tsx, src/components/LBP/PublicDetails/QuantitiesAndWeight.tsx, src/components/LBP/PublicDetails/StatisticData.tsx
- Fix for "Remove some fields that aren't needed in the Coming Soon LBP"
- Fix for "There is no design and requirement for the short information on LBP deal's card
-> Hide it temporary"
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1257
2. Documents:
=> Ixspd1-1257 fe dev lbp fix UI bugs in lbp detail page low priority

src/assets/images/sortingIcon.svg, src/components/LBP/Dashboard/InvestorInformation.tsx, src/components/LBP/PublicDetails/HistoryTable.tsx
Bug Fixes in the files related to data extraction and sorting trade history.
- Added "Wallet Address" column
- Improved the header names for better user understanding
- Updated the columns for the extracted file to include: Investor name, Investor Address, Balance
- Implemented sorting feature for the "Amount" column, sorting by Project Token
- Displayed sort buttons by default, enhancing user experience.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1258
2. Documents:
=> Fixed UI bugs for trade history, investment extraction

src/components/LBP/Dashboard/InvestorInformation.tsx, src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/PublicDetails/HistoryTable.tsx
The sorting problem in LBP Details Table has been resolved,
Furthermore, the logo issue within the summary modal has been rectified,
Additionally, the "boughtShares" column has been seamlessly integrated into the admin table,
These enhancements ensure a smoother and more efficient user experience
- The sorting problem in LBP Details Table has been resolved
- Logo issue within the summary modal has been fixed New function have been created that will rendered the logo image
- boughtShares column has been integrated into the admin table
1. Jira ticket: N/A 142 Issue number in Google Sheets
2. Documents:
=> LBP sorting issue have been fixed, additionally logo issue have been fixed in summary modal(142), and boughtShares column added in admin table.

src/components/LBP/PublicDetails/Ended.tsx
Fix purchased token amount formatting
2. Documents:
=> Fix purchased token amount formatting

src/components/LBP/PublicDetails/HistoryTable.tsx, src/components/LBP/PublicDetails/PublicChart.tsx, src/components/LBP/PublicDetails/StatisticData.tsx
- Fix page crashes if user disconnects wallet in LBP detail page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1259
2. Documents: 
=> IXSPD1-1259 - Page crashes if user disconnects wallet in LBP detail page

src/components/LBP/PublicDetails/RedeemedSideBar.tsx
- Fix for case LbpStatus.closed
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1259
2. Documents:
=> IXSPD1-1259: Fix for case LbpStatus.closed

src/components/LBP/InvestmentList/LbpList.tsx
Fix bug load more show draft LBPs
2. Documents:
=> Fix bug click load more button shouldn't show draft LBPs

src/components/LBP/types.ts, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/ProjectInfo.tsx, src/pages/LBP/components/Tokenomics.tsx
- Fix does not pre-fill "0" for optional fields in LBP creation form
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1260
2. Documents:
=> IXSPD1-1260 Do not pre-fill "0" for optional fields in LBP creation form

src/components/LBP/Dashboard/LbpsFull.tsx, src/pages/LBP/LbpForm.tsx
- Wrap lbp layout
- Add miss link admin-detail
2. Documents:
=> Wrap lbp dashboard layout

src/pages/LBP/layout.tsx
- Handle detect is connected and check role admin to access LBP dashboard
2. Documents:
=> Handle detect is connected and check role admin to access LBP dashboard

src/pages/LBP/AdminLbpDetail.tsx
- Fix check connect and role for admin lbp detail page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1263
2. Documents:
=> IXSPD1-1263 Handle for case admin lbp detail

src/pages/LBP/AdminLbpDetail.tsx, src/pages/LBP/layout.tsx
- Fix issue hooks render multiple when disconnect
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1261
2. Documents:
=> Fix issue hooks render multiple when disconnect

src/pages/LBP/AdminLbpDetail.tsx, src/pages/LBP/layout.tsx
- Revert check role
-
-
2. Documents:
=> Remove check role

src/constants/constants.ts, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Branding.tsx, src/pages/LBP/components/Graph.tsx, src/pages/LBP/components/ProjectInfo/AddSocialLinksModal.tsx, src/pages/LBP/components/ProjectInfo/AdditionalLinksModal.tsx, src/pages/LBP/components/ProjectInfo/index.tsx, src/pages/LBP/components/Tokenomics.tsx, src/utils/index.ts
- Add validation errors for LBP form
- Show Project Token name once the Token Address is provided
- Change Initital for StartWeight and EndWeight
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1265, https://investax.atlassian.net/browse/IXSPD1-1264
3. Documents:
=> Ixspd1 1264 add validation errors for lbp form

src/components/LBP/Forms/SubmitSummary.tsx, src/pages/LBP/components/ProjectInfo/index.tsx, src/pages/LBP/components/Tokenomics.tsx
- Fix startWeight
- Fix Insufficient balance
- Fix Message error: max 10mb of Upload Documents
2. Documents:
=> Fix some bugs in lbp form

src/pages/LBP/LbpForm.tsx
- Fix show popup unsaved change
-
-
2. Documents:
=> Don’t display the popup when user clicks “Save Progress” button.

src/components/LaunchpadIssuance/IssuanceCreateButton/index.tsx, src/pages/LBP/components/ProjectInfo/index.tsx
- Fix placeholder to Name of Asset
2. Documents:
=> Fix placeholder to Name of Asset

src/pages/LBP/components/Tokenomics.tsx
- Handle error validate for Tokenomics
-
-
2. Documents:
=> Handle check error validate for Tokenomics

src/pages/LBP/components/ProjectInfo/index.tsx, src/pages/LBP/components/Tokenomics.tsx, src/utils/index.ts
- Fix detect, not touch anything in the form
2. Documents:
=> Fix detect not touch anything in form

src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/QuantitiesAndWeight.tsx, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Tokenomics.tsx
- Fix share token symbol
2. Documents:
=> Fix share token symbol

src/components/LBP/Forms/SubmitSummary.tsx, src/components/LBP/types.ts, src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Tokenomics.tsx
- Add XTokenLiteProxy field to the form
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1279
2. Documents:
=> Ixspd1-1279 fe add x token lite proxy field to the form

src/pages/LBP/LbpForm.tsx
- Handle nullable xTokenLiteProxyAddress for transformDataForSaving
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1263
2. Documents:
=> IXSPD1-1263 Handle nullable xTokenLiteProxyAddress for transformDataForSaving

package.json, src/index.tsx, src/pages/App.tsx, src/state/index.ts, yarn.lock
- Handle persist and check role admin for LPB dashboard
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1263
2. Documents:
=> dIxspd1-1263 fe dev lbp don t allow users to access lbp dashboard and its child pages via links if they are not admin

src/pages/LBP/LbpForm.tsx, src/pages/LBP/components/Tokenomics.tsx
- Fix enable button Submit form
- Add hint for input xTokenLiteProxyAddress
2. Documents:
=> Fix enable button Submit form

src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/Remaining.tsx, src/components/LBP/PublicDetails/SideBar.tsx, src/constants/addresses.ts, src/hooks/useDecimals.ts, src/pages/LBP/components/Approvals.tsx, src/pages/LBP/components/Tokenomics.tsx
- Add useDecimals for get token decimals
- Optimize rerender in BuySellField
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1256
2. Documents:
=> IXSPD1-1256 Add useDecimals and optimize rerender BuySellField

src/components/Mobile-Menu/Menu.tsx, src/pages/Launchpad/Footer.tsx
Updated copy right year
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1275
2. Documents:
=> Updated copy right year

src/components/LBP/InvestmentList/LbpCard.tsx, src/pages/LBP/components/ProjectInfo/AddSocialLinksModal.tsx, src/pages/LBP/components/ProjectInfo/AdditionalLinksModal.tsx, src/pages/LBP/components/ProjectInfo/index.tsx, src/pages/LBP/components/Tokenomics.tsx
- Fix some bugs in Excel files
- Remove some un used in the Tokenomic File
2. Documents:
=> Fix some bugs of LBP

src/components/LBP/PublicDetails/PublicChart.tsx, src/pages/LBP/components/Graph.tsx
- Handle chart style for LBP
2. Documents:
=> Handle chart style for LBP

src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/Remaining.tsx, src/pages/LBP/components/Tokenomics.tsx
- Change the text Max button from Max to Max.
- Fix show remaining time in detail lbp
- Fix slider start weight and end weight and fix UI buy sell
2. Documents:
=> Fix bug in LBP

src/components/LBP/Dashboard/InvestorInformation.tsx, src/components/LBP/InvestmentList/LbpSaleStatusInfo.tsx, src/components/LBP/PublicDetails/Remaining.tsx, src/pages/LBP/AdminLbpDetail.tsx, src/pages/LBP/components/SummaryFields.tsx, src/utils/time.ts
- Refactor show time remaining
2. Documents:
=> Fix some bug in lbp page

src/components/LBP/PublicDetails/SideBar.tsx
- Handle set buy tab by default in SideBar.tsx
2. Documents:
=> Set buy tab by default in SideBar.tsx for LBP

src/components/Header/index.tsx, src/components/Web3Status/index.tsx, src/components/WhiteLabelFooter/CopyrightBlock.tsx, src/components/WhiteLabelFooter/InfoBlock.tsx, src/components/WhiteLabelFooter/LogoBlock.tsx, src/components/WhiteLabelFooter/ProductsBlock.tsx, src/components/WhiteLabelFooter/SocialBlock.tsx, src/components/WhiteLabelFooter/index.tsx, src/components/WhiteLabelFooter/styleds.tsx, src/pages/App.tsx, src/services/apiService.ts, src/state/whitelabel/hooks.ts
- Restyle for Footer and Header
- Get config from API get whitepaper
2. Documents:
=> Style for header and footer

src/components/CustomHeaders/index.tsx, src/components/Header/HeaderLinks.tsx, src/components/Launchpad/InvestmentList/index.tsx, src/components/Mobile-Menu/Menu.tsx, src/pages/App.tsx, src/pages/Launchpad/index.tsx, src/state/whitelabel/types.ts
- Update favicon and hide lbp
- Custom nav bar and change favicon
2. Documents:
=> Ixspd1-1315 fe saas navbar

src/components/KycReviewModal/Blocks/InvestorDeclaration.tsx, src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx, src/components/Mobile-Menu/Menu.tsx, src/components/PlaygroundModal/index.tsx, src/components/WalletModal/index.tsx, src/components/WhiteLabelFooter/InfoBlock.tsx, src/components/swap/SwapHeader.tsx, src/pages/Connect Wallet Modal/index.tsx, src/pages/KYC/EmailVerifyModal.tsx, src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/ResendEmailModal.tsx, src/pages/KYC/index.tsx, src/pages/Launchpad/Banner.tsx, src/pages/Launchpad/index.tsx, src/pages/Pool/LiquidityTitle.tsx, src/pages/Swap/SwapBanner/index.tsx
-  Handle integrate api for saas
2. Documents:
=> Handle integrate api for saas

src/components/LBP/PublicDetails/QuantitiesAndWeight.tsx, src/pages/LBP/components/SummaryFields.tsx
- Fix UI for the Quantities and Weight section, bug 176
2. Documents:
=> Fix UI for the Quantities and Weight section

src/components/SearchModal/CurrencyList.tsx, src/pages/CustodianV2/index.tsx
- Handle show hide tokens
https://investax.atlassian.net/browse/IXSPD1-1316
https://investax.atlassian.net/browse/IXSPD1-1314
2. Documents:
=> Handle show hide tokens

src/pages/KYC/SecondaryContactOption.tsx
Addressed long polling and 'Get OTP' button issues, along with updating the bot name for improved performance and clarity.
- long polling  start when user get the OTP
- added bot name from env variables
- updated the button name
2. Documents:
=> fixed issues on the long polling and get otp button and bot name

public/index.html, src/components/AccountDetails/index.tsx, src/components/CustomHeaders/index.tsx, src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx, src/components/LaunchpadOffer/InvestDialog/index.tsx, src/components/LaunchpadOffer/InvestDialog/utils/InvestFailedModal.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/connectors/index.ts, src/pages/App.tsx, src/state/index.ts, src/state/wallet/hooks.ts, src/state/wallet/index.ts, src/state/whitelabel/types.ts
- Handle metadata and disconnect button
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-993
2. Documents:
=> Handle metadata and disconnect button

src/components/Announcement/styleds.ts, src/components/Header/NetworkCard.tsx, src/components/Header/index.tsx, src/pages/Launchpad/index.tsx
There was a persistent issue where many elements on the page were being overridden if users did not close the disclaimer at the top of the page. The root cause of the issue was identified and addressed. The code was modified to ensure that the presence of the disclaimer text at the top of the page does not interfere with other page elements.
- Adjusted the CSS to prevent the disclaimer from affecting other elements
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-982
2. Documents:
=> IXSPD1-982 elements are overridden if the users don't close the disclaimer at the top of the page have been fixed

src/components/AccountDetails/index.tsx, src/components/Header/HeaderLinks.tsx, src/pages/Admin/Navbar.tsx, src/state/user/reducer.ts
- Handle header component when disconnecting and admin header logo
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1336
2. Documents:
=> IXSPD1-1336 Handle header component when disconnect and admin header logo

src/pages/KYC/IndividualKycFormV2.tsx
Open the same page when click on Verify Document button
2. Documents:
=> Open the same page when click on Verify Document button

src/components/KycReviewModal/IndividualFormV2.tsx, src/pages/KYC/IndividualKycFormV2.tsx, src/pages/KYC/SecondaryContactOption.tsx, src/pages/KYC/mock.ts, src/pages/KYC/schema.ts, src/state/kyc/hooks.ts, src/state/user/hooks.tsx
Added the referralCode the KYC V2 form and enhanced the user experience by suppressing error messages during user input. Error messages now display only after the input field loses focus. This PR resolves tickets [IXSPD1-1344] and [IXSPD1-1345].
- Added referralCode to the KYC V2 form payload.
- Improved user experience by suppressing error messages during user input.
- Ensured error messages only appear after input fields lose focus.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1344
https://investax.atlassian.net/browse/IXSPD1-1345
2. Documents:
[IXSPD1-1344]: https://investax.atlassian.net/browse/IXSPD1-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> fixed the issue display error message during user is inputting into the fields and referralCode added in KYC v2

package.json, src/chains.ts, src/components/AccountDetails/index.tsx, src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/components/Web3Status/index.tsx, src/connectors/coinbaseWallet.ts, src/connectors/index.ts, src/constants/wallet.ts, src/pages/App.tsx, src/utils/web3ReactUtils.ts, yarn.lock
- Handle integrate coinbase wallet
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1338
2. Documents:
=> Handle integrate coinbase wallet

src/components/LaunchpadIssuance/ManageOffer/index.tsx
IXSPD1-982 The Whitelist button and back button are hidden issue fixed
- Margin Added from top
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-982
2. Documents:
=> IXSPD1-982 The Whitelist button and back button are hidden issue fixed

package.json, public/index.html, src/components/AccountDetails/index.tsx, src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/connectors/index.ts, yarn.lock
- Fix header is moving when click on the wallet address, coinbase wallet doesnt work properly
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1358
2. Documents:
=> Ixspd1-1358 fe header is moving when click on the wallet address coinbase wallet doesnt work properly

src/assets/images/kyc_approve_icon.svg, src/assets/images/kyc_reject_icon.svg, src/components/KycReviewModal/IndividualFormV2.tsx, src/components/KycReviewModal/KycReviewModalV2.tsx, src/pages/KYC/SecondaryContactOption.tsx, src/pages/KYC/common.tsx, src/pages/KYC/schema.ts
This PR addresses multiple UI and validation issues within the KYC review screen and associated functionalities. Key improvements include enhanced input validation for personal information fields, display enhancements for referral and verification information, and dynamic behavior adjustments for email verification processes.
- Ticket IXSPD1-1350: Resolved UI bugs on the KYC review screen.
- Ticket IXSPD1-1359: Implemented display of referral information when the admin reviews KYC.
- Ticket IXSPD1-1337: Displayed the Resend Code button and time counter beneath the Verify Code button.
- Ticket IXSPD1-1352: Changed the "Verify Code" button to "Send Code" if the user changes their email.
- Ticket IXSPD1-1349: Adjusted validation conditions for personal information fields:
Allowed spaces in …
=> Kyc v2 bugs fixes for  IXSPD1-1350, IXSPD1-1359, IXSPD1-1349, IXSPD1-1337,IXSPD1-1352 Tickets

src/components/AdminAccreditationTable/index.tsx, src/components/AdminKyc/index.tsx, src/components/AdminSecurityCatalog/index.tsx, src/components/AdminTransactionsTable/index.tsx, src/components/UsersList/index.tsx, src/pages/Admin/index.tsx
-  Fix loading in admin page
- https://investax.atlassian.net/browse/IXSPD1-1356
- https://investax.atlassian.net/browse/IXSPD1-1357
3. Documents:
=> IXSPD1-1356 IXSPD1-1357 Fix loading in admin page

src/pages/KYC/IndividualKycFormV2.tsx, src/pages/KYC/SecondaryContactOption.tsx, src/pages/KYC/index.tsx
In This PR following fixes have been made to the KYC V2 process: removed the time counter and 'Get new Code' button in the Telegram section, updated the UI for rejected KYC cases, and resolved an issue where errors were displayed despite successful verification.
- Removed the time counter button in the Telegram section.
- Updated the UI for rejected KYC cases
- Fixed an issue where successful KYC verification still displayed errors.
https://investax.atlassian.net/browse/IXSPD1-1363
https://investax.atlassian.net/browse/IXSPD1-1360
https://investax.atlassian.net/browse/IXSPD1-1365
2. Documents:
=> Tickets IXSPD1-1360 IXSPD1-1363 IXSPD1-1365 bug fixes on kyc status page validation page and the resend code button

src/components/CustomHeaders/index.tsx, src/components/Launchpad/InvestmentList/index.tsx, src/index.tsx, src/pages/App.tsx, src/pages/CustodianV2/index.tsx, src/pages/Launchpad/Banner.tsx, src/pages/Launchpad/index.tsx
- Fix default value of whitelable
2. Documents:
=> Fix default value of whitelable

src/pages/App.tsx
- remove trigger host ixswap
2. Documents:
=> remove trigger host ixswap

src/components/SearchModal/CurrencyList.tsx
- Fix list token swap
2. Documents:
=> Fix list token swap

src/pages/KYC/SecondaryContactOption.tsx, src/pages/KYC/enum.ts
This PR addresses and fixes various UI issues related to the email verification process in the KYC V2. Additionally, it updates the Email Verification UI to enhance user experience before they click the "Send Code" button.
- Fixed UI issues that were impacting the email verification process.
- Updated the UI before the user clicks the "Send Code" button.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1367
https://investax.atlassian.net/browse/IXSPD1-1368
2. Documents:
=> KYC bug fixes tickets IXSPD1-1367 and IXSPD1-1368

package.json, src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/connectors/index.ts, src/pages/App.tsx, yarn.lock
- Update coinbase sdk
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1371
2. Documents:
=> Ixspd1-1371 fe wallet coinbase wallet stuck on connection if disconnect and reconnect second time

public/index.html, src/components/Header/index.tsx, src/pages/Admin/Navbar.tsx, src/pages/App.tsx, src/state/whitelabel/types.ts
- Fix link home and meta tags
-
-
2. Documents:
=> Fix link home and meta tags

package.json, src/components/CustomHeaders/index.tsx, src/index.tsx, yarn.lock
- Switch to react-helmet-async
2. Documents:
=> Switch to react-helmet-async

public/index.html, src/components/CustomHeaders/index.tsx, src/index.tsx
- Fix react-helmet-async
-
-
2. Documents:
=> Fix react-helmet-async

src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
- Change from useApproveCallback to useAllowance
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1355
2. Documents:
=> IXSPD1-1355 Change from useApproveCallback to useAllowance

src/components/SearchModal/CurrencyList.tsx, src/pages/CustodianV2/index.tsx
- Filter sec tokens based on whiteLabelConfig
2. Documents:
=> Filter sec tokens based on whiteLabelConfig

src/components/WhiteLabelFooter/SocialBlock.tsx
- Show social icons in the footer
2. Documents:
=> Show social icons in footer

src/constants/subgraph.ts
Add missing subgraph endpoint for LBP on prod environment
2. Documents:
=> hotfix: add subgrah prod endpoint for LBP

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx
- Optimize load time of invest component in launchpad
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1394
2. Documents:
=> Optimize load time of invest component in launchpad

src/constants/subgraph.ts
This PR meged a hot fix on production on 06/18/2024  https://github.com/IX-Swap/interface/pull/2414
2. Documents:
=> Merge hotfix: add missing lbp subgraph endpoint for production

src/pages/KYC/IndividualKycFormV2.tsx
Display Business Email after verifying successfully issue fixed
- enable business email field
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1404
2. Documents:
=> Display Business Email after verifying successfully issue fixed

src/components/LBP/PublicDetails/HistoryTable.tsx, src/components/LBP/PublicDetails/PublicChart.tsx, src/components/LBP/PublicDetails/QuantitiesAndWeight.tsx, src/components/LBP/PublicDetails/StatisticData.tsx, src/pages/LBP/components/SummaryFields.tsx
- Fix chart, icon usdt and format value
2. Documents:
=> Hotfix: chart, icon usdt and format value

src/components/LBP/PublicDetails/HistoryTable.tsx, src/components/LBP/PublicDetails/PublicChart.tsx, src/components/LBP/PublicDetails/QuantitiesAndWeight.tsx, src/components/LBP/PublicDetails/StatisticData.tsx, src/pages/LBP/components/SummaryFields.tsx
- Fix chart, icon token and format value
2. Documents:
=> Fix chart, icon token and format value

src/components/Header/index.tsx, src/pages/CustodianV2/index.tsx
- fix-logo-and-add-padding-custodian 
-
-
2. Documents:
=> fix-logo-and-add-padding-custodian 

src/components/LBP/PublicDetails/BuySellFields.tsx
- Refactor buy sell field
2. Documents:
=> Refactor buy sell field

src/components/Launchpad/Offers/index.tsx
- Fix break UI loading in lauchpad
2. Documents:
=> Fix break UI loading in lauchpad

public/index.html
- Fix padding scrollbar when open modal
-
-
2. Documents:
=> Fix padding scrollbar when open modal

public/index.html
Reverts IX-Swap/interface#2428
=> Revert "Fix padding scrollbar when open modal"

src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DirectorField.tsx
Supported  PDF upload when creating an Issuance
- minor changes in FileField added isDocument
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1409
2. Documents:
=> Supported  PDF upload when creating an Issuance

src/components/AdminKyc/index.tsx, src/components/UsersList/index.tsx, src/components/UsersList/styleds.ts, src/state/admin/actions.ts
Added tenant column for kyc and user admin pages
- Added tenant column for kyc and user admin pages
- some style updated
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1373
2. Documents:
=> Added tenant column for kyc and user admin pages

src/components/Header/index.tsx, src/pages/Admin/Navbar.tsx
- Fix ixs logo
-
-
2. Documents:
=> Fix ixs logo

src/components/Announcement/index.tsx, src/components/Announcement/styleds.ts, src/components/Header/HeaderLinks.tsx
- Fix announcement component
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1412
2. Documents:
=> Ixspd1-1412 fe dev saas overlapping of top nav bar and disclaimer text

README.md, src/components/LBP/PublicDetails/Links.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/sections/AdditionalInformation.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/types.ts, src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx, src/components/WhiteLabelFooter/SocialBlock.tsx, src/pages/Launchpad/Footer.tsx, src/state/launchpad/types.ts
Changed text Twitter to X everywhere on IXS
- Text Changes Only
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1178
2. Documents:
=> Changed text Twitter to X everywhere on IXS

src/components/Header/NetworkCard.tsx, src/components/Header/index.tsx, src/components/Web3Status/index.tsx, src/pages/Admin/Navbar.tsx, src/pages/Launchpad/Header.tsx
- Fix UI header
-
-
2. Documents:
=> Fix UI header

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx
-  Fix cannot fetch balance
-
-
2. Documents:
=> Fix cannot fetch balance

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/services/apiService.ts
- Add loading when open modal
-
-
2. Documents:
=> Add loading when open modal

src/pages/LBP/PublicDetails.tsx
- Fix show modal to ask user to switch chain if user is on the wrong chain
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1416
2. Documents:
=> Ixspd1-1416 lbp bug show modal to ask user to switch chain if user is on the wrong chain

src/components/LBP/Admin/Modals/ConfirmStatusModal.tsx, src/pages/LBP/AdminLbpDetail.tsx
…ose deal
- Styled loading in lbp page detail and handle show error toast when close deal
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1418
2. Documents:
=> Fix It doesn't show error toast when close failed

src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx
- show investing token balance in the invest modal
- styled UI
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1424
2. Documents:
=> Ixspd1-1424 fe launchpad show investing token balance in the invest modal

src/pages/KYC/IndividualKycFormV2.tsx, src/pages/KYC/SecondaryContactOption.tsx, src/pages/KYC/common.tsx
Business email validation added, some UI fixes and text fixes on send code component
- handled editable fields on business email
- fix the validations
- update the UI for disabled
- fix some minor text
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1419
2. Documents:
=> business email validation added some UI fixes and text fixes on send code component

src/components/Launchpad/KYCPrompt/index.tsx, src/components/UsersList/UserModal.tsx, src/components/UsersList/userMobileFilters.tsx, src/pages/KYC/CorporateKycForm.tsx, src/pages/KYC/common.tsx
- Dynamic get name from whitelabelconfig
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1426
2. Documents:
=> IXSPD1-1426 Get name from whitelabelconfig

src/components/AdminSecurityCatalog/index.tsx
- Enable button create issuer
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1414
2. Documents:
=> Ixspd1-1414 bug cant add token in security catalog

src/pages/KYC/IndividualKycFormV2.tsx, src/pages/KYC/SecondaryContactOption.tsx, src/pages/KYC/common.tsx
Business email validation added, some UI fixes and text fixes on send code component cherry pick from dev branch
- handled editable fields on business email
- fix the validations
- update the UI for disabled
- fix some minor text
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1419
2. Documents:
=> Business email validation added, some UI fixes and text fixes on send code component cherry pick from dev branch 

src/pages/LBP/PublicDetails.tsx
- Show modal to ask user to switch chain if user is on the wrong chain
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1416
2. Documents:
=> Show modal to ask user to switch chain if user is on the wrong chain

src/constants/subgraph.ts
- Update subgraph url
-
-
2. Documents:
=> Update subgraph url

src/pages/KYC/IndividualKycFormV2.tsx
IXSPD1-1447 The fields of Personal Information are empty after verifying Email is fixed
-  made the handleSuccess function async to ensure that fetchKYCData waits for completion, allowing proper state updates.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1447
2. Documents:
=> IXSPD1-1447 The fields of Personal Information are empty after verifying Email is fixed

src/components/Countdown/LegacyCountdown.tsx, src/components/Countdown/index.tsx, src/components/Countdown/utils.ts, src/components/LBP/InvestmentList/LbpCard.tsx, src/components/LBP/InvestmentList/LbpSaleStatusInfo.tsx, src/components/LBP/PublicDetails/Remaining.tsx, src/pages/LBP/components/SummaryFields.tsx, src/utils/time.ts
- Add new countdown and handle show time lbp
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1445
2. Documents:
=> IXSPD1-1445 Add new countdown and handle show time lbp

src/components/Vault/DepositPopup.tsx, src/components/Vault/DepositRequestForm.tsx, src/components/Vault/TransactionDetails.tsx
- Handle show balance and fix wrong network name
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1425
2. Documents:
=> IXSPD1-1425 Handle show balance and fix wrong network name

src/components/Vault/DepositRequestForm.tsx
- Handle delete sender and empty sender
2. Documents:
=> Ixspd1-1425 fe security vault prefill from address show token balance

src/components/Pagination/index.tsx
- Fix block click last page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1444
2. Documents:
=> IXSPD1-1444 Fix block click last page

src/components/LBP/Dashboard/LbpsFull.tsx, src/components/LBP/InvestmentList/LbpCard.tsx, src/components/LBP/LbpCreateButton/index.tsx, src/components/LBP/PublicDetails/Background.tsx, src/components/LBP/PublicDetails/BuySellFields.tsx, src/components/LBP/PublicDetails/Ended.tsx, src/components/LBP/PublicDetails/Links.tsx, src/components/LBP/PublicDetails/MiddleSection.tsx, src/components/LBP/PublicDetails/PublicChart.tsx, src/components/LBP/PublicDetails/QuantitiesAndWeight.tsx, src/components/LBP/PublicDetails/RedeemedSideBar.tsx, src/components/LBP/PublicDetails/SideBar.tsx, src/components/LBP/PublicDetails/SideBarPaused.tsx, src/components/LBP/PublicDetails/StatisticData.tsx, src/pages/KYC/SecondaryContactOption.tsx, src/pages/KYC/schema.ts, src/pages/LBP/LbpForm.tsx, src/pages/LBP/layout.tsx
Ixspd1 1413 Implemented Mobile UI for LBP on Launchpad on user side
- UI updated for mobile view
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1413
2. Documents:
=> Ixspd1 1413 Implemented Mobile UI for LBP on Launchpad on user side

src/components/AddressInputPanel/styleds.tsx
- Remove truncate
-
-
2. Documents:
=> Remove truncate

src/components/AddressInputPanel/AddressInput.tsx, src/components/AddressInputPanel/styleds.tsx
- Fix truncate
-
-
2. Documents:
=> Fix truncate

src/components/AccountDetails/index.tsx, src/components/AddressInputPanel/AddressInput.tsx, src/components/AddressInputPanel/styleds.tsx, src/components/Vault/AmountInput.tsx, src/components/Vault/DepositRequestForm.tsx
- Styled input in deposit form
- Update support email url
2. Documents:
=> Styled input in deposit form

src/components/Header/HeaderLinks.tsx, src/components/Mobile-Menu/Menu.tsx, src/pages/Launchpad/Header.tsx
XSPD1-1460 allowed users to access the issuance page if role is Offer manager and kyc is approved
- changed condition in route
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1460
2. Documents:
=> XSPD1-1460 allowed users to access the issuance page if role is Offer manager and kyc is approved

src/components/WhiteLabelFooter/CopyrightBlock.tsx, src/components/WhiteLabelFooter/InfoBlock.tsx, src/components/WhiteLabelFooter/LogoBlock.tsx, src/components/WhiteLabelFooter/SocialBlock.tsx, src/components/WhiteLabelFooter/index.tsx, src/components/WhiteLabelFooter/styleds.tsx
- Update new design for whitelabel footer
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1461
2. Documents:
=> IXSPD1-1461 Update new design for whitelabel footer

src/pages/AddLiquidityV2/index.tsx, src/pages/Pool/ConnectWallet.tsx, src/pages/RemoveLiquidity/index.tsx, src/pages/Swap/SwapButtons.tsx
- Add connect wallet modal to swap and pool page
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1467
2. Documents:
=> IXSPD1-1467 Add connect wallet modal to swap and pool page

src/pages/LBP/layout.tsx
- Protect lbp page if not connected wallet
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1429
2. Documents:
=> IXSPD1-1429 Protect lbp page if not connect wallet

src/components/WhiteLabelFooter/styleds.tsx
IXSPD1-1458 addressed the issue SAAS - The footer overrides the filter dropdown
- just minor fix(changed z-index)
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1458
2. Documents:
=> IXSPD1-1458 addressed the issue SAAS - The footer overrides the filter dropdown

src/pages/App.tsx
- Fix auto redirect when reload at insurance page with role Offer manager 
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1462
2. Documents:
=> IXSPD1-1462 Fix auto redirect when reload at insurance page with role Offer manager 

src/pages/KYC/IndividualKycFormV2.tsx
IXSPD1-1470 Made a telegram first option in secondary contact in individual KYC v2
- update auto selected logic and changed the position of the telegram option
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1470
2. Documents:
=> IXSPD1-1470 Made a telegram first option in secondary contact in individual KYC v2

src/pages/KYC/IndividualKycFormV2.tsx
IXSPD1-1470 made a telegram first option in secondary contact in invidual KYC v2
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1470
2. Documents:
=> IXSPD1-1470 made a telegram first option in secondary contact in invidual KYC v2

src/components/Launchpad/InvestmentCard/index.tsx, src/state/launchpad/types.ts
Updated the fields on the Deal cards fixed UI 
- UI have been fixed
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-308
2. Documents:
=> Updated the fields on the Deal cards

src/chains.ts, src/components/LBP/Admin/AdminHeader.tsx, src/components/UsersList/index.tsx, src/constants/chains.ts, src/utils/getExplorerLink.ts
Changed amoy oklink scan -> amoy polygon scan
The column in Users tab displays incorrect name is fixed 
- Changed amoy oklink scan -> amoy polygon scan
- update the name column name
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1097
https://investax.atlassian.net/browse/IXSPD1-1476
2. Documents:
=> Changed amoy oklink scan -> amoy polygon scan

src/components/Header/index.tsx, src/components/Launchpad/KYCPrompt/index.tsx, src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx, src/pages/Admin/Navbar.tsx, src/pages/KYC/index.tsx, src/state/launchpad/types.ts, src/utils/routes.ts
addressed the issue  Blank page displays when user clicks on the app logo
- changed the redirect url from / to /kyc
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1477
2. Documents:
=> addressed the issue  Blank page displays when user clicks on the app logo

.eslintrc.json, src/components/AdminKyc/index.tsx, src/state/admin/actions.ts
- Show Approver column on KYC admin page
1. Jira ticket: [IXSPD1-1478](https://investax.atlassian.net/browse/IXSPD1-1478)
2. Documents:
[IXSPD1-1478]: https://investax.atlassian.net/browse/IXSPD1-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ixspd1-1478] Show `Approver` column on KYC admin page

src/components/AdminKyc/index.tsx
- Remove middle name in approver column
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1478
2. Documents:
- [] The pull request doesn't affect existing feature
=> IXSPD1-1478 Remove middle name in approver column

src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
Hide checkboxes on the Invest Dashboard if there are no corresponding uploaded documents
- Conditionally render agreement checkboxes based on the existence of related documents.
- Update button disable logic to depend on the presence and agreement status of available documents.
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1485
2. Documents:
=> Hide checkboxes on the Invest Dashboard if there are no corresponding uploaded documents

src/components/AdminKyc/index.tsx, src/state/admin/actions.ts
- show dash on approver column if kyc is V1
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1483
2. Documents:
- [] The pull request doesn't affect existing feature
=> feat: IXSPD1-1483 show dash on approver column if kyc is V1

src/components/AccountDetails/index.tsx, src/components/Header/index.tsx, src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/components/LaunchpadIssuance/IssuanceForm/index.tsx, src/components/WalletModal/index.tsx, src/pages/App.tsx, src/pages/Launchpad/Banner.tsx, src/state/whitelabel/types.ts
- Fix banner mobile
- Load links from config
- Handle default route for home
- https://investax.atlassian.net/browse/IXSPD1-1308
- https://investax.atlassian.net/browse/IXSPD1-1479
2. Documents:
=> IXSPD1-1308, IXSPD1-1479 Fix banner mobile, load links from config, handle default route for home

src/components/Launchpad/Offers/Pinned.tsx
fixes for Pinned deal is not aligned vertically
- just changed the width to auto
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1495
2. Documents:
=> fixes for Pinned deal is not aligned vertically

src/constants/countriesList.ts, src/pages/App.tsx
Blocked user from North Korea at App Level
- Blocked user from KP country code that belongs to North Korea 
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1496
2. Documents:
=> Blocked user from North Korea at App Level

src/assets/images/otherMediaIcon.svg, src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx, src/pages/LaunchpadOffer/index.tsx
IXSPD1-1399 Social Media more icon added and UI fixed on launchpad
-  More icon added on social media 
- UI fixes on Launchpad page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1399
2. Documents:
=> IXSPD1-1399 Social Media more icon added and UI fixed on launchpad

src/components/Launchpad/NetworkNotAvailable/styled.tsx, src/components/NotAvailablePage/styled.ts, src/pages/App.tsx, src/pages/AppBody.tsx, src/pages/LaunchpadOffer/index.tsx
- Fix style space and wrong position back button
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1502
2. Documents:
=> IXSPD1-1502 Fix style space and wrong position back button

src/components/Header/NetworkCard.tsx, src/components/Launchpad/InvestmentCard/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx, src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx, src/pages/PoolFinder/CurrencyRow.tsx
fix some UI bugs on network cards lauchpad offer gallery and info form
- Simple UI change on multiples pages 
- Increase Token Ticker in Issuance to 11 letters
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1498
https://investax.atlassian.net/browse/IXSPD1-308
https://investax.atlassian.net/browse/IXSPD1-1399
https://investax.atlassian.net/browse/IXSPD1-1398
2. Documents:
=> fix some UI bugs on network cards lauchpad offer gallery and info form

public/index.html, src/components/ErrorBoundary/index.tsx
- Handle reload when chunk error
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1505
2. Documents:
=> IXSPD1-1505 Handle reload when chunk error

src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/components/Mobile-Menu/Menu.tsx, src/components/WhiteLabelFooter/CopyrightBlock.tsx
- Update the links of "Terms and Conditions" and "Privacy Policy"
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1479
2. Documents:
=> Ixspd1-1479 fe saa s update the links of terms and conditions and privacy policy

src/components/NotAvailablePage/index.tsx
- Hide the sentence on Connect Wallet screen if isIxSwap = false
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1508
2. Documents:
=> IXSPD1-1508 Hide the sentence on Connect Wallet screen if isIxSwap = false

src/state/admin/constants.ts
- Page size of admin page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1503
2. Documents:
=> hotfix: IXSPD1-1503 Admin KYC page is extremely slow on dev, production

src/components/Pagination/index.tsx
- Fix button prev always disabled
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1514
2. Documents: 
=> IXSPD1-1514 Fix button prev always disabled

src/pages/CustodianV2/index.tsx
-  Hide other securities section if is ixswap
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1509
2. Documents:
=> IXSPD1-1509 fe hide other securities section if is ixswap

src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
Removed 0 on the Register to Invest Dashboard when user submitted No
- handled conditions by ternary operators
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1511
2. Documents:
=> Removed 0 on the Register to Invest Dashboard when user submitted No

src/components/AdminAccreditationTable/index.tsx
country field updated on accreditation page
- changed the key address?.country to .individual?.nationality
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1515
2. Documents:
=> country field updated on accreditation page

src/components/AdminAccreditationTable/index.tsx
country field updated on accreditation page patch release to production
-
-
-
2. Documents:
=> country field updated on accreditation page patch release to production

src/pages/App.tsx
- 
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1462
2. Documents:
=> IXSPD1-1462 Trigger redirect with role offer manager when in insurance page

src/pages/App.tsx
- fix reload insurance page auto redirect to launchpad with role manage
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1462
2. Documents:
=> IXSPD1-1462 fix reload insurance page auto redirect to launchpad with role manage

src/components/Button/index.tsx, src/pages/Pool/ImportPool.tsx, src/services/apiService.ts
- Update  primary color for readi
2. Documents:
=> Update  primary color for readi

src/pages/App.tsx
- Handle case not OFFER_MANAGER role
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1519
2. Documents:
=> IXSPD1-1519 Handle case not OFFER_MANAGER role

src/pages/App.tsx
* Handle case not OFFER_MANAGER role
* add path /
-
-
-
2. Documents:
=> IXSPD1-1519 Handle case not OFFER_MANAGER role (#2513)

src/components/Mobile-Menu/Menu.tsx, src/constants/lists.ts
- Hide some item menu mobile for saas and remove old tokens list
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1524
2. Documents:
=> IXSPD1-1524 Hide some item menu mobile for saas and remove old tokens list

src/components/AdminAccreditationTable/index.tsx, src/components/AdminKyc/index.tsx, src/components/AdminSecurityCatalog/index.tsx, src/components/AdminTransactionsTable/index.tsx, src/components/UsersList/index.tsx
- Update padding
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1521
2. Documents:
=> IXSPD1-1521 Update padding

src/pages/Launchpad/Footer.tsx
IXS footer update some text changed and update the routes
- Update The Footer and fixed some routes
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1522
2. Documents:
=> IXSPD1-1522 IXS footer update some text changed and update the routes

src/components/AdminAccreditationTable/index.tsx, src/components/AdminKyc/index.tsx, src/components/AdminSecurityCatalog/index.tsx, src/components/AdminTransactionsTable/index.tsx, src/components/UsersList/index.tsx, src/pages/Admin/index.tsx, src/pages/App.tsx, src/pages/Launchpad/Footer.tsx
[Hide some item menu mobile for saas and remove old tokens list](https://github.com/IX-Swap/interface/commit/ecb8c51c645d68f3c3b0efe46e9b9ff0bfa9faa8)
[Merge pull request](https://github.com/IX-Swap/interface/commit/f6a98cb11f995dd57311022b6daa466fcdd0643a) https://github.com/IX-Swap/interface/pull/2517 [from IX-Swap/IXSPD1-1524-FE-SAAS-Hide-Charts…](https://github.com/IX-Swap/interface/commit/f6a98cb11f995dd57311022b6daa466fcdd0643a) 
[IXSPD1-1521 Overflowed change-requested status in KYC status column i…](https://github.com/IX-Swap/interface/commit/746f59bcb1ef64d46938077791c5f7827fe1990a) 
2. Documents:
=> UI fixes for v0.8

src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/react-app-env.d.ts
- Fix not detect chain id in first time connect
- Fix staging flashing after connecting metamask wallet on brave firefox 
2. Documents:
=> Ixspd1-1523 fe staging flashing after connecting metamask wallet on brave firefox

src/components/Launchpad/InvestmentCard/index.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx
IXSPD1-1534 changed a height to 300px on Launchpad images
- changed height from auto to 300px
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1534
2. Documents:
=> fixed the issue Cannot close the dialog when the error message is shown

src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx, src/components/Mobile-Menu/Menu.tsx, src/components/WhiteLabelFooter/CopyrightBlock.tsx
IXSPD1-1536 fixed the issue related to copyrights on footer
- changed the copyrights from dynamic value to hardcode
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1536
2. Documents:
=> IXSPD1-1536 fixed the issue related to copyrights on footer

src/components/Launchpad/InvestmentCard/index.tsx, src/components/Launchpad/Wallet/ConnectionDialog.tsx, src/components/Mobile-Menu/Menu.tsx, src/components/WhiteLabelFooter/CopyrightBlock.tsx, src/connectors/walletConnectV2.ts, src/react-app-env.d.ts
[Ixspd1-1523 fe staging flashing after connecting metamask wallet on b…](https://github.com/IX-Swap/interface/commit/88f0880d78074479a8b18b56ae99cc72a5e244e1) 
@[leonthuongto](https://github.com/IX-Swap/interface/commits?author=leonthuongto)
@thi-investax
leonthuongto authored and [thi-investax](https://github.com/IX-Swap/interface/commits?author=thi-investax) committed 14 minutes ago
[fixed banner image height to 300px](https://github.com/IX-Swap/interface/commit/9f6cc8c275e2ce8724c593706b155c23df5dcb56)
@[kapildave07](https://github.com/IX-Swap/interface/commits?author=kapildave07)
@thi-investax
kapildave07 authored and [thi-investax](https://github.com/IX-Swap/interface/commits?author=thi-investax) committed 14 minutes ago
[IXSPD1-1536 …
=> Release v0.8.1

src/connectors/walletConnectV2.ts
Hot fix wallet connect doesn't work for readi
-
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1540
2. Documents: 
=> Update wallet connector to allow read.ixswap.io domain

src/pages/KYC/index.tsx
- Fix the kyc page loads too slowly when it is auto directed
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1520
2. Documents:
=> Ixspd1-1520 fe the kyc page loads too slowly when it is auto directed

src/pages/App.tsx
- Fix coinbase connect in mobile app
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1539
2. Documents:
=> Ixspd1-1539 fe coin base mobile cannot connect at the first time user scans qr coinbase code

src/pages/KYC/index.tsx
- Fix page load slow in kyc page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1520
2. Documents:
=> IXSPD1-1520 Fix page load slow in kyc page

src/components/LaunchpadIssuance/ManageOffer/HeaderButtons.tsx, src/components/LaunchpadOffer/InvestDialog/utils/OfferLinks.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/constants/chains.ts
- Fix explorer link follow network get from offer data and chainid
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1476
2. Documents:
=> IXSPD1-1476 Fix explorer link follow network get from offer data and chainid

package.json, yarn.lock
- Fix no tokens shown in the swap model
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1563
2. Documents:
=> Ixspd1-1563 fe no tokens shown in the swap model

src/pages/KYC/IndividualKycFormV2.tsx, src/pages/KYC/SecondaryContactOption.tsx, src/pages/KYC/VerificationConfirmation.tsx
Implemented Mobile UI for KYC v2
- updated KYCv2 UI for mobile
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1449
2. Documents:
=> Implemented Mobile UI for KYC v2

src/components/Launchpad/InvestmentCard/InvestmentSaleStatusInfo.tsx, src/components/Launchpad/InvestmentCard/index.tsx
- Fix chain icons should have a consistent position on deal's card
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1561
2. Documents:
=> IXSPD1-1561 Fix chain icons should have a consistent position on deal's card

src/components/AdminSecurityCatalog/TokenPopup.tsx, src/components/Input/index.ts
- Add base to dropdown origin chain
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1569
2. Documents:
=> IXSPD1-1569 Add base to dropdown origin chain

src/constants/whitelisted-users.ts, src/state/wallet/constants.ts
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1580
2. Documents:
=> Fix bug clicking on deposit in security vault crashes due to missing address validation for base chain

src/pages/KYC/index.tsx
-  Fix show NotAvailablePage after connected
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1520
2. Documents:
=> Fix show NotAvailablePage after connected

src/pages/Launchpad/Footer.tsx
Removed Fractionalized-NFT Exchange from the footer
- Removed Fractionalized-NFT Exchange from the footer
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1581
2. Documents:
=> Removed Fractionalized-NFT Exchange from the footer

src/components/LBP/InvestmentList/LbpCard.tsx
Ixspd1 1565 Show network badge icon for LBP cards
- display network badge
- fixed some style
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1565
2. Documents:
=> Ixspd1 1565 Show network badge icon for LBP cards

src/pages/LBP/components/Tokenomics.tsx
IXSPD1-1584 added the Switch chain when user choose a different chain LBP form
- update the LBP form
- user can switch network 
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1584
2. Documents:
=> IXSPD1-1584 added the Switch chain when user choose a different chain LBP form

src/chains.ts, src/pages/LBP/PublicDetails.tsx, src/pages/SecTokenDetails/index.tsx
- Handle wrong chain for lbp detail and token detail
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1590
2. Documents:
=> Ixspd1-1500 fe ask user to switch to the right chain when click on launchpad lbp card

src/pages/Swap/AuthorizationButtons.tsx
button displays incorrect status when user input amount to swap
- Revert changes of this ticket https://investax.atlassian.net/browse/IXSPD1-672
- Fix authorization logic
1. Jira ticket:  https://investax.atlassian.net/browse/IXSPD1-1582
2. Documents:
=> Ixspd1 1582 fe dev base the button displays incorrect status when user input amount to swap

src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
update the API call when user select no at register to invest
- update the API call when user select no at register to invest
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1542
2. Documents:
=> update the API call when user select no at register to invest

src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx
update the logic of selecting date removed the date range picker from other presale
- Removed the date range picker from other presale
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1566
2. Documents:
=> update the logic of selecting date removed the date range picker from other presale

src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx, src/pages/LaunchpadOffer/index.tsx
- Improve UI launchpad detail
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1568
2. Documents:
=> IXSPD1-1568 Improve UI launchpad detail

src/pages/Launchpad/Footer.tsx
Update T&C at the footer
- Update T&C at the footer added Update box
2. Documents:
=> Update T&C at the footer

src/components/KycReviewModal/IndividualFormV2.tsx, src/components/KycReviewModal/KycReviewModalV2.tsx, src/components/Pagination/index.tsx, src/state/nft/hooks.ts
fixed UI bugs and paginations issue on KYC admin 
- fixed the margin on view modal
- update the pagination logic
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1538
2. Documents:
=> IXSPD1-1538 fixed UI bugs and paginations issue on KYC admin 

src/constants/subgraph.ts
- Update subgraph endpoint lbp
2. Documents:
=> Update subgraph endpoint lbp

src/components/CurrencyInputPanel/index.tsx, src/hooks/useApproveCallback.ts, src/pages/Swap/ApproveButtons.tsx, src/pages/Swap/SwapButtons.tsx, src/pages/Swap/useSwapApproval.ts
- use allowance in swap liquidity
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1603
2. Documents:
=> Ixspd1-1603 fe replace legacy use approve with use allowance in swap liquidity as it s slow and asks user to allow max uint256

src/chains.ts, src/utils/isEnvMode.ts
=> Update logic of checkWrongChain funciton

src/components/AdminKyc/index.tsx
- validate kyc status to display approver or rejector
- rename column approver to authorizer
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1535
2. Documents:
=> feat: show approver - if KYC V2 is Pending, show name of rejector if status is rejected, rename approver to authorizer

src/components/Vault/FeeStatus.tsx
- Don't hardcode fee precision
- Make native token symbol dynamic
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1612
2. Documents:
=> IXSPD1-1612 Fix withdrawal fee not shown

src/components/Header/index.tsx, src/components/MultipleFilters/index.tsx, src/components/TmMyTokens/TokenItem.tsx, src/components/UserPayoutEvents/Card.tsx, src/components/UsersList/UserModal.tsx, src/components/UsersList/userMobileFilters.tsx, src/constants/addresses.ts, src/pages/CreatePayoutEvent/PayoutForm.tsx, src/pages/PayoutItem/PayoutHeader.tsx, src/pages/SecurityTokens/index.tsx, src/state/lists/wrappedTokenInfo.ts, src/state/user/actions.ts, src/state/wallet/hooks.ts
- Enable payout feature
- Change the token type to be optional
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1517
2. Documents:
=> feat: [IXSPD1-1517] enable payout feature

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx
- dynamic decimal for payout purchase
-
-
1. Jira ticket: [IXSPD1-1586]
2. Documents:
[IXSPD1-1586]: https://investax.atlassian.net/browse/IXSPD1-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1586] dynamic decimal for payout purchase

src/pages/CustodianV2/MySecToken.tsx, src/pages/CustodianV2/SecTokenSection.tsx, src/pages/CustodianV2/Status.tsx, src/pages/CustodianV2/index.tsx, src/services/apiUrls.ts
- Show balances of tokens on different chain
2. Documents:
=> Ixspd1-1590 fe show balances of tokens on different chain

src/components/Launchpad/NetworkNotAvailable/index.tsx, src/components/NotAvailablePage/index.tsx, src/pages/KYC/index.tsx, src/utils/index.ts
- Fix text modal wrong network, hide loading first time in kyc page
-
-
1. Jira ticket:  https://investax.atlassian.net/browse/IXSPD1-1482
2. Documents:
=> Fix text modal wrong network, hide loading first time in kyc page

src/constants/chains.ts
- Fix Incorrect URL at Pool Adrdess
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1608
2. Documents:
=> Ixspd1-1608 fe lbp admin UI broken incorrect url at pool adrdess

src/components/LaunchpadIssuance/IssuanceForm/Information/schema.ts
- Allow these characters when inputing Token ticker " -" , "_"
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1626
2. Documents:
=> IXSPD1-1626 Allow these characters when inputing Token ticker " -" , "_"

src/components/Web3Status/index.tsx, src/pages/Launchpad/Banner.tsx
issue on Launchpad is covered on menu if user's KYC is not approved is fixed
- fixed some style
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1527
2. Documents:
=> issue on Launchpad is covered on menu if user's KYC is not approved is fixed

src/components/AdminKyc/index.tsx, src/components/Pagination/index.tsx
UI bugs on Admin-KYC review page fixed total pages issue fixed
- pass the total pages to parent componenet
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1538
2. Documents:
=> UI bugs on Admin-KYC review page fixed total pages issue fixed

src/components/Launchpad/InvestmentList/index.tsx, src/state/whitelabel/types.ts
- Update FE to enable LBP module based on whitelabelconfig.enableLbp
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1628
2. Documents:
=> IXSPD1-1628 Update FE to enable LBP module based on whitelabelconfig.enableLbp

src/components/LBP/Admin/AdminHeader.tsx, src/pages/LBP/AdminLbpDetail.tsx
-  Handle open link follow network in api
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1621
2. Documents:
=> IXSPD1-1621 fe lbp admin UI broken incorrect url at pool adrdess

src/pages/CustodianV2/MySecToken.tsx, src/pages/CustodianV2/SecTokenSection.tsx, src/pages/CustodianV2/index.tsx
…oading
- Implement skeleton loading for security vault page while content is loading
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1624
2. Documents:
=> IXSPD1-1624 Implement loading for security token page while content is loading

src/components/ChevronElement/index.tsx, src/components/Vault/HistoryTable.tsx, src/components/Vault/TransactionDetails.tsx, src/components/Vault/styleds.tsx, src/pages/CustodianV2/MySecToken.tsx, src/pages/CustodianV2/Status.tsx, src/pages/SecTokenDetails/index.tsx
UI bugs fixed on Security Tokens page
- UI bugs fixed on Security Tokens page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1587
2. Documents:
=> UI bugs fixed on Security Tokens page

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx, src/components/LaunchpadMisc/styled.ts
Ixspd1 1566 fixed the Issuance - Don’t fill in the invalid time selected from the calendar to the timeline fields in the form
- update the validations 
- handled errors
- fixed some UI
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1566
2. Documents:
=> Ixspd1 1566 fixed the Issuance - Don’t fill in the invalid time selected from the calendar to the timeline fields in the form

src/components/swap/AcceptChanges.tsx, src/components/swap/styleds.tsx
- Update Style on Swap Screen when the price is updated
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1620
2. Documents:
=> Ixspd1-1620 fe update style on swap screen when the price is updated

src/components/ChevronElement/index.tsx, src/components/Header/HeaderLinks.tsx, src/components/Vault/HistoryTable.tsx
- changed dropdown 
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1587
2. Documents:
=> Dropdown changed to old one on network and navbar and

src/constants/chains.ts, src/pages/AddLiquidityV2/index.tsx, src/state/pool/hooks.ts
- pass txHash when create liquidity pool
-
-
1. Jira ticket: [IXSPD1-1625]
2. Documents:
[IXSPD1-1625]: https://investax.atlassian.net/browse/IXSPD1-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1625] pass txHash when create liquidity pool

src/components/LaunchpadIssuance/IssuanceForm/shared/constants.ts, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx, src/components/LaunchpadIssuance/ManageOffer/edit/index.tsx
issue fixed on Add validation error on the date picker when admin selects invalid time to update timeline of a deal
- update some validations in edit issuance 
- handle some cases in try catch
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1640
2. Documents:
=> issue fixed on Add validation error on the date picker when admin selects invalid time to update timeline of a deal

src/state/secCatalog/hooks.ts
- Change max length of Ticker in Add Token form 11 character
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1595
2. Documents:
=> IXSPD1-1595 FIx change max length of Ticker in Add Token form

src/components/SearchModal/CurrencySearch.tsx, src/components/TransactionConfirmationModal/index.tsx, src/components/Vault/TransactionDetails.tsx, src/pages/AddLiquidityV2/ModalHeader.tsx, src/pages/AddLiquidityV2/PoolPriceBar.tsx, src/pages/AddLiquidityV2/PricesAndPoolShare.tsx
- UI bugs on Liquidity Pools page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1593
2. Documents:
=> IXSPD1-1593 Fix UI bugs on Liquidity Pools page

src/components/Launchpad/InvestmentCard/index.tsx
- Fix The chain icon overrides the information on deal's card
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1643
2. Documents:
=> Ixspd1-1643 fe the chain icon overrides the information on deal s card

src/components/AdminAccreditationTable/CustodianStatus.tsx
- Fix Approve button on Accreditation page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1597
2. Documents:
=> IXSPD1-1597 Fix Approve button on Accreditation page

src/pages/LBP/components/Tokenomics.tsx
IXSPD1 1614 fixed the issue Token balances are not reflected properly when switching chain in LBP admin page
- refactor the code 
- handled try and catch state
- update the token balances when chain switch
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1614
2. Documents:
=> IXSPD1 1614 fixed the issue Token balances are not reflected properly when switching chain in LBP admin page

src/connectors/walletConnectV2.ts
- Fix cannot connect MetaMask on mobile's browser
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1558
2. Documents:
=> Ixspd1-1558 fe dev wallet connect cannot connect meta mask on mobile s browser

src/chains.ts, src/components/Vault/DepositPending.tsx, src/components/Vault/WithdrawPopup.tsx, src/components/Vault/WithdrawRequestForm.tsx, src/utils/strings.ts
- Update the network name on Withdraw screen
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1644
2. Documents:
=> IXSPD1-1644 Update the network name on Withdraw screen

src/components/LaunchpadOffer/InvestDialog/content/Closed.tsx, src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx, src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx, src/components/LaunchpadOffer/InvestDialog/utils/ConvertationField.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferDetails.tsx, src/components/LaunchpadOffer/OfferSidebar/OfferSaleAllocation.tsx, src/state/launchpad/constants.ts
Display USDC name based on the active network and removed hardcoded USDC.e
- Removed hardcoded USDC.e
- Display USDC name based on the active network
- Created a function to render token symbol
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1642
2. Documents:
=> Display USDC name based on the active network

src/pages/LBP/components/Tokenomics.tsx
issue fixed not getting project token on switch chain
- added some dependancy 
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1614
2. Documents:
=> issue fixed not getting project token on switch chain

src/components/AdminAccreditationTable/CustodianStatus.tsx, src/components/LaunchpadOffer/InvestDialog/utils/InvestSubmitButton.tsx
- Change cursor to pointer
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1647
2. Documents:
=> Ixspd1-1647 fe change cursor to pointer

src/components/Mobile-Menu/Menu.tsx
- Charts page on menu is covered by Disclaimer text
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1635
2. Documents:
=> IXSPD1-1635 Charts page on menu is covered by Disclaimer text

src/components/LBP/PublicDetails/DocumentSec.tsx, src/components/LBP/PublicDetails/Links.tsx, src/components/LBP/PublicDetails/PublicChart.tsx
Implemented Mobile UI for LBP on Launchpad
- Implemented Mobile UI for LBP on Launchpad
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1413
2. Documents:
=> Implemented Mobile UI for LBP on Launchpad

src/hooks/useERC20Permit.ts
- Staging | Swap page crash when try swapping USDC -> IXS
2. Documents:
=> IXSPD1-1672 Staging | Swap page crash when try swapping USDC -> IXS

src/components/Header/IXSBalanceModal.tsx
- Fix UI bugs on Token information modal
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1667
2. Documents:
=> IXSPD1-1667 Fix UI bugs on Token information modal

src/components/Tabs/index.tsx, src/components/UserPayoutEvents/AllPayoutEvents.tsx, src/components/UserPayoutEvents/styleds.ts, src/pages/AppBody.tsx, src/pages/SecurityTokens/index.tsx
- Styles of security tokens/payout events page. Result: 
1. Jira ticket: [IXSPD1-1633]
2. Documents:
[IXSPD1-1633]: https://investax.atlassian.net/browse/IXSPD1-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1633] update css for tab in security tokens page

src/pages/PayoutItem/ActionBlock/UserView.tsx
- populate the security token name
1. Jira ticket: [IXSPD1-1663]
2. Documents:
[IXSPD1-1663]: https://investax.atlassian.net/browse/IXSPD1-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1663] populate particular token name of sec token

src/components/AccountDetails/KycStatus.tsx, src/components/AccountDetails/index.tsx
- toggleWalletModal
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1677
2. Documents:
=> IXSPD1-1677 handle nav kyc

src/pages/CreatePayoutEvent/PublishPayoutModal.tsx
- replace text "Insufficient token amount" by loading indicator when UI is fetching balance
1. Jira ticket: [IXSPD1-1664]
2. Documents:
[IXSPD1-1664]: https://investax.atlassian.net/browse/IXSPD1-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1664] show loading indicator when UI is fetching balance

src/chains.ts, src/pages/KYC/mock.ts, src/pages/LBP/components/Approvals.tsx, src/pages/LBP/components/Tokenomics.tsx, src/state/lbp/constants.ts
Ixspd1 1678  issue fixed Cannot approve We cannot approve the Base token until switching between the options
- Handle all asset token address values
- Create a dynamic dropdown with chainId for different environments
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1678
2. Documents:
=> Ixspd1 1678  issue fixed Cannot approve We cannot approve the Base token until switching between the options

src/components/PayoutItem/PreviewModal/Attachements.tsx, src/components/PayoutItem/PreviewModal/Attachment.tsx, src/components/TokenNetwork/index.tsx, src/pages/PayoutItem/InfoBlock.tsx, src/pages/PayoutItem/PayoutHeader.tsx, src/pages/PayoutItem/index.tsx, src/pages/PayoutItem/utils.ts, src/pages/SecurityTokens/index.tsx, src/state/admin/actions.ts, src/types/secToken.ts
- summary section of the payout event page
1. Jira ticket: [IXSPD1-1687]
2. Documents: 
[IXSPD1-1687]: https://investax.atlassian.net/browse/IXSPD1-1687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1687] re-work payout event summary section

src/components/AccountDetails/KycStatus.tsx, src/components/Header/HeaderLinks.tsx, src/components/Header/IXSBalance.tsx, src/components/Header/IXSBalanceModal.tsx, src/components/Header/index.tsx, src/theme/components.tsx
- Update style account detail modal and add token modal
- https://investax.atlassian.net/browse/IXSPD1-1667
- https://investax.atlassian.net/browse/IXSPD1-1677
3. Documents:
=> IXSPD1-1667, IXSPD1-1677 Update style account detail modal and add token modal

src/components/TransactionConfirmationModal/index.tsx, src/hooks/useV2Trade.ts, src/state/swap/hooks.ts
- combine 2 hooks to one
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1676
2. Documents:
=> IXSPD1-1676 combine 2 hooks to one

src/components/NotAvailablePage/index.tsx
- Handle wrong chain NotAvailablePage
-
-
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1645
2. Documents:
=> IXSPD1-1645 Handle wrong chain NotAvailablePage

src/components/Checkbox/index.tsx, src/components/FilePreview/index.tsx, src/components/FilePreview/styleds.tsx, src/components/Label/index.tsx, src/components/Select/index.tsx, src/components/Uploader/index.tsx, src/pages/CreatePayoutEvent/Info.tsx, src/pages/CreatePayoutEvent/PayoutEventBlock.tsx, src/pages/CreatePayoutEvent/PayoutForm.tsx, src/pages/CreatePayoutEvent/PayoutType.tsx, src/pages/CreatePayoutEvent/Summary.tsx, src/pages/CreatePayoutEvent/index.tsx, src/pages/CreatePayoutEvent/styleds.ts, src/pages/KYC/CorporateKycForm.tsx, src/pages/KYC/IndividualKycForm.tsx, src/pages/KYC/common.tsx, src/theme/index.tsx
XSPD1-1629 Update payout create form - Security tokens section UI upgradedull request.
- UI upgraded
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1629
2. Documents:
=> XSPD1-1629 Update payout create form - Security tokens section UI upgraded

src/assets/svg/arrow-head.svg, src/components/Pagination/index.tsx, src/components/UserPayoutEvents/Card.tsx, src/components/UserPayoutEvents/styleds.ts, src/pages/PayoutItem/ActionBlock/ManagerView.tsx, src/pages/PayoutItem/ActionBlock/UserView.tsx, src/pages/PayoutItem/ActionBlock/styleds.ts, src/pages/PayoutItem/History/index.tsx, src/pages/PayoutItem/MoreEventBlock.tsx, src/pages/PayoutItem/PayoutHeader.tsx, src/pages/PayoutItem/Timeline/PayoutTimeline.tsx, src/pages/PayoutItem/Timeline/TimelineDate.tsx, src/pages/PayoutItem/index.tsx
- started payout event page for user role
1. Jira ticket: [IXSPD1-1697]
2. Documents:
[IXSPD1-1697]: https://investax.atlassian.net/browse/IXSPD1-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1697] started page for user role

src/components/NotAvailablePage/index.tsx
-  Staging patch v0.9
-
-
2. Documents:
=> Staging patch v0.9

src/pages/PayoutItem/Timeline/PayoutTimeline.tsx, src/pages/PayoutItem/Timeline/TimelineDate.tsx, src/pages/PayoutItem/Timeline/TodayIndicator.tsx
- Styles for the announced payout event.
1. Jira ticket: [IXSPD1-1696]
2. Documents:
[IXSPD1-1696]: https://investax.atlassian.net/browse/IXSPD1-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1696] layout for announced payout event

src/components/CurrencyInputPanel/index.tsx, src/pages/AddLiquidityV2/index.tsx, src/pages/PoolFinder/CurrencyRow.tsx, src/pages/PoolFinder/index.tsx
- "Create Pool" button does not work the first time selecting a token pair
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1706
2. Documents:
=> IXSPD1-1706 "Create Pool" button does not work the first time selecting a token pair

src/components/DateInput/index.tsx, src/theme/muiTheme.tsx
Ixspd1 1650 Restyled date picker
- Restyled date picker
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1650
2. Documents:
=> Ixspd1 1650 Restyled date picker

src/components/AccountDetails/ReferFriend.tsx, src/pages/KYC/index.tsx
-  Referral link should always link to KYC page
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1719
2. Documents:
=> IXSPD1-1719 Fix Referral link should always link to KYC page

src/components/LaunchpadIssuance/IssuanceForm/Information/InformationForm.tsx, src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx
IXSPD1-1703 fixed the error when select minutes request.
- Removed some extra validations
- Removed toLowerCase extra function
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1703
2. Documents:
=> IXSPD1-1703 fixed the error when select minutes

src/components/UserPayoutEvents/AllPayoutEvents.tsx, src/components/UserPayoutEvents/MyPayoutEvents.tsx, src/components/UserPayoutEvents/styleds.ts, src/pages/SecurityTokens/index.tsx
- layout for my payout events page
1. Jira ticket: [IXSPD1-1695]
2. Documents:
[IXSPD1-1695]: https://investax.atlassian.net/browse/IXSPD1-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1695] layout for my payout events page

src/components/Button/index.tsx, src/components/DateInput/index.tsx, src/pages/CreatePayoutEvent/EditPayoutEvent.tsx, src/pages/CreatePayoutEvent/PayoutEventBlock.tsx, src/pages/CreatePayoutEvent/PayoutType.tsx, src/pages/CreatePayoutEvent/PublishPayoutModal.tsx, src/pages/CreatePayoutEvent/styleds.ts, src/pages/KYC/common.tsx
Updated payout Edit form
- Updated payout Edit form
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1716
2. Documents:
=> Updated payout Edit form

src/assets/svg/arrow-head.svg, src/pages/PayoutItem/ActionBlock/StatusBadge.tsx, src/pages/PayoutItem/ActionBlock/UserView.tsx, src/pages/PayoutItem/ActionBlock/styleds.ts, src/pages/PayoutItem/Timeline/PayoutTimeline.tsx, src/pages/PayoutItem/Timeline/TimelineDate.tsx, src/pages/PayoutItem/Timeline/TodayIndicator.tsx, src/pages/PayoutItem/utils.ts, src/theme/index.tsx, src/theme/styled.d.ts
- finalize the detail page of payout event
1. Jira ticket: [IXSPD1-1699]
2. Documents:
[IXSPD1-1699]: https://investax.atlassian.net/browse/IXSPD1-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1699] styles for payout event detail

src/components/UserPayoutEvents/AllPayoutEvents.tsx, src/components/UserPayoutEvents/MyPayoutEvents.tsx
…a on page
- fix flashing issue when switching tabs, remove overlay loading
1. Jira ticket: [IXSPD1-1679]
2. Documents:
[IXSPD1-1679]: https://investax.atlassian.net/browse/IXSPD1-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1679] avoid showing loading indicator when there is data

package.json, yarn.lock
Bump default token list to reflect Base IXS
2. Documents:
=> Bump default token list to reflect Base IXS

src/pages/PayoutItem/ActionBlock/UserView.tsx, src/services/apiUrls.ts, src/state/payout/hooks.ts
- retrieve claimable token amount from API and populate
1. Jira ticket: [IXSPD1-1661]
2. Documents:
[IXSPD1-1661]: https://investax.atlassian.net/browse/IXSPD1-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1661] populate claimable token amount from API

src/components/Launchpad/InvestmentList/index.tsx
- Force only show insurance tab when disable lbp
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1628
2. Documents:
=> IXSPD1-1628 Force only show insurance tab when disable lbp

src/constants/addresses.ts
- Update IXS token address for staging
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1736
2. Documents:
=> Ixspd1-1736 fe update ixs token address for staging

src/state/user/updater.tsx
issue fixed on Create payout form is auto-cleared
- issue fixed on Create payout form is auto-cleared
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1730
2. Documents:
=> issue fixed on Create payout form is auto-cleared

src/pages/Launchpad/Banner.tsx, src/pages/Launchpad/index.tsx
- Launchpad readi UI fixed
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1708
2. Documents:
=> Launchpad readi UI fixed

src/pages/Launchpad/Banner.tsx
Launchpad readi UI fixes for mobile
- update the width for mobile UI
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1708
2. Documents:
=> Launchpad readi UI fixes for mobile

src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx, src/components/LaunchpadOffer/OfferMainInfo/OfferGalleryViewer.tsx, src/pages/App.tsx
deal detail page UI updated and upgrade the launchpad background to white
- Deal detail page UI updated
- Upgrade the launchpad background to white
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1739
2. Documents:
=> deal detail page UI updated and upgrade the launchpad background to white

src/components/LaunchpadOffer/OfferMainInfo/OfferGallery.tsx, src/components/LaunchpadOffer/OfferMainInfo/OfferGalleryViewer.tsx
- Issue fixed on open image size on carousel
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1739
2. Documents:
=> Issue fixed on open image size on carousel

src/hooks/Tokens.ts
- populate the native tokens from all networks in useSafeCurrency hook
1. Jira ticket: [IXSPD1-1758]
2. Documents:
[IXSPD1-1758]: https://investax.atlassian.net/browse/IXSPD1-1758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IXSPD1-1758] populate the native token in useSafeCurrency hook

src/components/LaunchpadIssuance/IssuanceForm/shared/fields/DateRangeField.tsx, src/components/LaunchpadIssuance/ManageOffer/edit/index.tsx
- Fix incorrect time selected in the time picker dialog
- https://investax.atlassian.net/browse/IXSPD1-1543
- https://investax.atlassian.net/browse/IXSPD1-293
- https://investax.atlassian.net/browse/IXSPD1-1750
2. Documents:
=> Ixspd1-293 IXSPD1-1543 IXSPD1-1750 incorrect time selected in the time picker dialog

src/components/TmPayoutEvents/styleds.ts, src/components/TmPayoutHistory/index.tsx, src/components/TmPayoutHistory/styleds.ts, src/pages/App.tsx, src/pages/Launchpad/Footer.tsx, src/pages/TokenManager/index.tsx, src/utils/routes.ts
Ixspd1 1759  Update styling of payout event admin pages
- UI have been updated
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1759
2. Documents:
=> Ixspd1 1759  Update styling of payout event admin pages

src/components/Header/HeaderLinks.tsx, src/components/LaunchpadIssuance/ManageOffer/ConfirmClaimModal.tsx, src/components/LaunchpadIssuance/ManageOffer/index.tsx, src/components/Mobile-Menu/Menu.tsx, src/components/UsersList/UserModal.tsx, src/components/UsersList/userMobileFilters.tsx, src/pages/CustodianV2/Info.tsx, src/pages/CustodianV2/SecTokensTable.tsx, src/pages/CustodianV2/index.tsx, src/pages/Faucet/FaucetTokenDropdown.tsx, src/pages/Launchpad/Header.tsx, src/pages/SecurityTokens/index.tsx
Replace Security Tokens terminology by RWAs
- Replace Security Tokens terminology by RWAs
1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1632
2. Documents:
=> Replace Security Tokens terminology by RWAs
